### ISSUE TITLE
Getting resetDrmState in android when try to play local audio

### ISSUE THREAD

**Issue by thegayankalinga** [bluefireteam/audioplayers#1004]
Getting Below Error when try to play the local sounds in android  (app loads without issue)
The same code works without any issue in iOS
Also please note sounds are not coming for android

```
V/MediaPlayer( 4114): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 4114): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

**Full Description**
void playSound(int soundNumber) {
    final player = AudioCache();
    player.play('note$soundNumber.wav');
  }

**Code to Reproduce**
void playSound(int soundNumber) {
    final player = AudioCache();
    player.play('note$soundNumber.wav');
  }

**Screenshots**
If applicable, add screenshots or video recordings to help explain your problem. This is totally optional.

**Platforms**
OS: android
 ext.kotlin_version = '1.5.30'

* flutter version: 2.5 16th September 2021
* audioplayers version: 0.20.1

**Comment by raviteja213** [comment]
i want to know the file type that should be kept for audio files in assets folder

**Comment by raviteja213** [comment]
![image](https://user-images.githubusercontent.com/61491710/180594344-be53005e-0de0-452d-b555-60881a18d105.png)
please check this and tell me the error

**Comment by Gustl22** [comment]
@bg15407 @raviteja213 @Aphosishiro these logs are coming from native MediaPlayer and most likely don't have anything to do with not playing the sound.

Can you try with AudioPlayers > `1.x.x`? AudioCache also doesn't provide the `play` method anymore...
