### ISSUE TITLE
Wrong path on web

### ISSUE THREAD

**Issue by rickyok** [bluefireteam/audioplayers#1005]
If i enter URL 

audioPlayer.play("assets/sounds/paimon.mp3", isLocal: true);

The result on the browser will be looking the URL at domain.com/assets/sounds/paimon.mp3

The build result on the Web is actually on domain.com/assets/assets/sounds/paimon.mp3

So it cannot find the file

**Comment by mc10sw** [comment]
i have same issue.

**Comment by sorawee-midassoft** [comment]
same

version audioplayers: ^0.20.1

**Comment by pramodkr123** [comment]
same issue

**Comment by Gustl22** [comment]
Close in favor of #911
