### ISSUE TITLE
some of the network audio files are not being played even after setting up for playing via http

### ISSUE THREAD

**Issue by adamsyy** [bluefireteam/audioplayers#1007]
for example these links
http://sc-bb.1.fm:8017/;
http://node-14.zeno.fm/cm1fkgbv1ceuv?rj-ttl=5&rj-token=AAABa7Pm__WhrF8jIJ36of_AC5C-TeMcqPiHC5BJB1j1JxkowiWAyQ

**Comment by Gustl22** [comment]
Which platform? This is too few information, sorry.
