### ISSUE TITLE
Calling setPlaybackRate() unpauses the player but doesn't trigger onPlayerStateChangedd

### ISSUE THREAD

**Issue by StarBattle08** [bluefireteam/audioplayers#1008]
When calling `setPlaybackRate()`, it unpauses the player if it's paused. But `onPlayerStateChanged` doesn't get called. So we have to manually set the playerState to PlayerState.PLAYING after calling `setPlaybackRate()`

- Flutter 2.5.0
- audioplayers 0.20.0

**Comment by JeromeGsq** [comment]
Hi, any news about this issue?
After setting the playbackRate, I don't want to resume my audio.
Thank you

**Comment by Gustl22** [comment]
Which platform? Is it still a problem in `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
