### ISSUE TITLE
MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_UNSUPPORTED

### ISSUE THREAD

**Issue by shichunlei** [bluefireteam/audioplayers#1009]
futter

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)

audioplayers 0.20.1

Android device SM N9500

http://audio.wehanyu.com/bct%2F%E9%9D%99%E5%BF%83%E7%9D%A1%E7%9C%A0%28%E6%96%B0%29_15.mp3

If the audio exceeds 10 minutes, this error occurs when the audio is played for about 10 minutes

V/MediaPlayer-JNI(16323): getDuration: 980036 (msec)
V/MediaPlayer-JNI(16323): getCurrentPosition: 628307 (msec)
I/flutter (16323): WHY-LOG    d    onAudioPositionChanged===>0:10:28.307000
V/MediaPlayerNative(16323): getDuration_l
V/MediaPlayer-JNI(16323): getDuration: 980036 (msec)
V/MediaPlayer-JNI(16323): getCurrentPosition: 628510 (msec)
I/flutter (16323): WHY-LOG    d    onAudioPositionChanged===>0:10:28.510000
V/MediaPlayerNative(16323): getDuration_l
V/MediaPlayer-JNI(16323): getDuration: 980036 (msec)
V/MediaPlayer-JNI(16323): getCurrentPosition: 628714 (msec)
I/flutter (16323): WHY-LOG    d    onAudioPositionChanged===>0:10:28.714000
V/MediaPlayerNative(16323): getDuration_l
V/MediaPlayer-JNI(16323): getDuration: 980036 (msec)
V/MediaPlayer-JNI(16323): getCurrentPosition: 628916 (msec)
I/flutter (16323): WHY-LOG    d    onAudioPositionChanged===>0:10:28.916000
V/MediaPlayerNative(16323): message received msg=300, ext1=0, ext2=0
V/MediaPlayerNative(16323): Received SEC_MM_PLAYER_CONTEXT_AWARE
V/MediaPlayerNative(16323): callback application
V/MediaPlayerNative(16323): back from callback
V/MediaPlayerNative(16323): message received msg=100, ext1=1, ext2=-1010
E/MediaPlayerNative(16323): error (1, -1010)
V/MediaPlayerNative(16323): callback application
E/MediaPlayer(16323): Error (1,-1010)
V/MediaPlayerNative(16323): back from callback
V/MediaPlayerNative(16323): message received msg=200, ext1=10950, ext2=0
W/MediaPlayerNative(16323): info/warning (10950, 0)
V/MediaPlayerNative(16323): callback application
V/MediaPlayerNative(16323): back from callback
V/MediaPlayerNative(16323): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(16323): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(16323): callback application
V/MediaPlayerNative(16323): back from callback
I/flutter (16323): WHY-LOG    e    onPlayerError===> MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_UNSUPPORTED
V/MediaPlayer-JNI(16323): stop
V/MediaPlayerNative(16323): stop
E/MediaPlayerNative(16323): stop called in state 0, mPlayer(0x7d63ab6480)
V/MediaPlayerNative(16323): message received msg=100, ext1=-38, ext2=0
E/MediaPlayerNative(16323): error (-38, 0)
V/MediaPlayerNative(16323): callback application
V/MediaPlayerNative(16323): back from callback
V/MediaPlayer-JNI(16323): reset
V/MediaPlayerNative(16323): reset
V/MediaPlayerNative(16323): message received msg=8, ext1=0, ext2=0
V/MediaPlayer(16323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16323): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayerNative(16323): notify(8, 0, 0) callback on disconnected mediaplayer
V/MediaPlayer(16323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(16323): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI(16323): release
V/MediaPlayerNative(16323): setListener
V/MediaPlayerNative(16323): disconnect
V/MediaPlayerNative(16323): destructor
V/MediaPlayerNative(16323): disconnect
I/flutter (16323): WHY-LOG    d    播放完毕

**Comment by Gustl22** [comment]
This should be fixed in `audioplayers: ^1.1.0`
