### ISSUE TITLE
AudioPlayer is not working on iOS

### ISSUE THREAD

**Issue by escannorrr** [bluefireteam/audioplayers#1010]
AudioPlayers plugin is not working with fluttertts plugin in iOS, but both are used in different screens

**Full Description**
I'm using audioplayers plugin to build AudioPlayer in iOS. But audio file from url is not working as I found out fluttertts and audioPlayers plugin does not work in iOS. But both the plugins are used on different screens. Is there any solution?

**Comment by erickzanardo** [comment]
We are not familiar with that plugin, please follow the issue template and add all or most of the info we ask there, without any error log, minimal reproducible code, there isn't much we can do to help.
