### ISSUE TITLE
iOS player crash

### ISSUE THREAD

**Issue by RukshanJS** [bluefireteam/audioplayers#1011]
In iOS 15 emulator, whenever try to play an audio using a (network) url, the whole flutter application crashes.

**Full Description**
The audioplayers `play` method crashses the whole flutter app in iOS when try to play a url music. This worked without such an issue before upgrading the flutter version from 2.2 to 2.5. Also, I have upgraded the xcode to the latest version 13.0. But no such issue is present and perfectly works in android without issues.

I also did `flutter clean` and re ran a several times, but still the issue persists in iOS.

**Code to Reproduce**
`audioPlayer.play(url_from_network);`

**Logs**
```
audioplayers/WrappedMediaPlayer.swift:224: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.
```

**Platforms**
* OS: ios
* OS version: 15.0
* Device: emulator/simulator.
* flutter version: 2.5.1
* audioplayers version: 0.20.1
* release or not release: debug mode
* does the error occur and does it have any peculiarities: Works without any issue on Android emulator. The issue is only with iOS.

**Comment by RukshanJS** [comment]
I think the issue was with having spaces in the audio url. I'll close this once I can confirm this.

**Comment by DanielCardona** [comment]
In my case that was the problem, and make sure the file has extension, thanks RukshanJS!

**Comment by Gustl22** [comment]
@ahmed-raza-92 if you don't have a space in url, then probably it's another issue. Feel free to open one with your url.
