### ISSUE TITLE
Remote audio works on iOS but not on Android. Problem of the package because another package works.

### ISSUE THREAD

**Issue by rober-m** [bluefireteam/audioplayers#1012]
First of all, thank you for the package. Problem: Audioplayers plays remote audio on iOS but not on Android. Codecs aren't the problem because I tried another flutter package (just_audio) and it worked.

**Full Description**
I'm trying to reproduce radios from remote sources. After reading many issues in this library I tried the the solutions that apply to my problem:
- Followed the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/master/troubleshooting.md).
- Added ClearText to the Manifest.
- Tried different combinations of audioplayers versions (**0.20.1** and **0.18.3**) and Kotlin versions (**1.5.0** and **1.4.32**).
- LOW_LATENCY.
- Checked the [supported media formats](https://developer.android.com/guide/topics/media/media-formats#audio-formats)
- etc.

To check if my code was somehow the problem, I tried [this package example app](https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers/example) with my links. And it didn't work either.

Finally, to check if it was the package or the codecs, **I tried to reproduce the problem with another package ([just_audio package](https://github.com/ryanheise/just_audio)) and it worked as expected!** An obvious difference on both these packages is that **audioplayers uses only `android.media`** and **just_audio uses both `android.media` and `exoplayer2`** ([ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer)). I don't know if that means that by using ExoPlayer I have access to extra codecs or if it's something else entirely. 

Is there a way to use this knowledge and update audioplayers to reproduce a wider range of files? If I need to play these files, it means that I have to migrate to the other package? Or can I make some small modifications to the current one?

**Code to Reproduce**
- Clone the audioplayers repo and run the example app with the `kUrl1` and `kUrl1` values replaced with the URLs specified previously.
- Same with the [just_audio package](https://github.com/ryanheise/just_audio) to check that it works.

**Log Errors**
The error showed in both my app and on the audioplayers example is:
```
E/MediaPlayerNative(12607): error (1, -2147483648)
E/MediaPlayer(12607): Error (1,-2147483648)
E/MediaPlayerNative(12607): stop called in state 0, mPlayer(0xcb4bf840)
E/MediaPlayerNative(12607): error (-38, 0)
I/flutter (12607): audioPlayer error : MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_SYSTEM
```
Interestingly, the just_audio example shows some info that could be related:
`I/ACodec  (12247): codec does not support config priority (err -2147483648)`

**Files/URLs/Sources**
- http://live-bauerdk.sharp-stream.com/nova128.mp3
- http://live-bauerdk.sharp-stream.com/popfm128.mp3

**Platforms**
- iOS
    - iPhone 12 mini simulator, iOS 14.5 (host: macOS 11.5.2). -> Not a problem
- Android
    - Nexus 6 emulator, API 29 (host: macOS 11.5.2) -> Doesn't work -> just_audio tested and it works.
    - Xiaomi Mi 9, Android 10 -> Doesn't work
    - Redmi Note 9, Android 10 -> Doesn't work

* Flutter 2.2.3 • channel stable
* Dart 2.13.4
* audioplayers version: 0.20.1
* release or not release: App in debug mode

**Thank you!**

**Comment by Sthefanny** [comment]
I'm having the same problem trying to play an audio from a URL, it works for the iOS but not for the android:

`
E/MediaPlayerNative( 5841): error (1, -2147483648)
E/MediaPlayer( 5841): Error (1,-2147483648)
E/MediaPlayerNative( 5841): stop called in state 0, mPlayer(0x895ff660)
E/MediaPlayerNative( 5841): error (-38, 0)
V/MediaPlayer( 5841): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5841): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 5841): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5841): cleanDrmObj: mDrmObj=null mDrmSessionId=null
`

Any news on how to solve this?

**Comment by IIPatternII** [comment]
@bpaul7101 and @Sthefanny, I changed to the just_audio plugin for the reasons explained in my initial comment. Best of lucks!

**Comment by Gustl22** [comment]
I "recorded" the stream and analyzed it with a tool:

The underlying codec is `mp2` which is not supported by Android. Closing in favor of #1260
