### ISSUE TITLE
Audioplayer can't be used with Logger package

### ISSUE THREAD

**Issue by EngFoggy** [bluefireteam/audioplayers#1013]
Using audioplayers and logger packages together leads to this error:

"The name 'Logger' is defined in the libraries 'package:audioplayers/src/logger.dart (via package:audioplayers/audioplayers.dart)' and 'package:logger/src/logger.dart (via package:logger/logger.dart)'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports."

The current workaround is to add "hide Logger" after the import (import 'package:audioplayers/audioplayers.dart' hide Logger;), but i think it would be better to rename the Logger class inside audioplayers, since the Logger defined herein is different from the one defined in logger package.

**Comment by erickzanardo** [comment]
Class name clashes are common between packages, even inside flutter itself we have classes with the same and we need to use prefix.

I don't see this as a bug on our side, there are many packages out there and to think on unique names that won't clash is an impossible task.

So for this case the recommend way is to just add a prefix to your Audioplayers import, or the Logger one, like the error message suggest.
