### ISSUE TITLE
Android build: Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

### ISSUE THREAD

**Issue by cgs** [bluefireteam/audioplayers#1015]
Plugin version: 0.20.1
Flutter: 2.5.2

Getting a whole bunch of these errors when trying to build an apk. I see this has cropped up before and was supposed to be fixed in 0.20.0. I've tried manually setting the kotlin version in the plugin's build.gradle, but it has no effect. I've upgraded Android studio as well as the Kotlin plugin version as well.

**Comment by sherly26** [comment]
@cgs thank you so much.
