### ISSUE TITLE
how to play your audioplayers for long time in use of streaming url

### ISSUE THREAD

**Issue by rjshah1902** [bluefireteam/audioplayers#1028]
// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:radiotime/utils/ai_utils.dart';
import 'package:radiotime/utils/all_details.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:flash/flash.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:connectivity/connectivity.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

AudioPlayer audioPlayer = new AudioPlayer();

bool playing = false;

void playMusic() async {
  String url = "http://67.205.99.39/proxy/demo?mp=/stream";
  // await Future.delayed(Duration(seconds: 3));
  // audioPlayer.play(url);

  int result = await audioPlayer.play(url);
  if (result == 1) {
    print('played successfully');
    print(audioPlayer.state);
  } else {
    print('Something Went Wrong');
  }
}

void stopMusic() async {
  await audioPlayer.stop();
  print(audioPlayer.state);
}

final assetsSliderImage = [
  'assets/slider-1.jpg',
  'assets/slider-2.jpg',
  'assets/slider-3.jpg',
  'assets/slider-4.jpg',
];

class _HomePageState extends State<HomePage> {
  double x = 0, y = 0, z = 0, scale = 1.0;

  bool openMenu = false;

  @override
  void initState() {
    super.initState();

    if (playing == true) {
      playMusic();
    }
  }

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.of(context).size;

    return AnimatedContainer(
      duration: const Duration(milliseconds: 200),
      transform: Matrix4.translationValues(x, y, z)..scale(scale),
      decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(openMenu ? 30 : 0)),
      child: Stack(
        children: [
          VxAnimatedBox()
              .size(context.screenWidth, context.screenHeight)
              .withGradient(
                LinearGradient(
                  colors: [
                    AIColors.primaryColor1,
                    AIColors.primaryColor2,
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomLeft,
                ),
              )
              .make(),
          AppBar(
            title: maintitle.text.xl4.bold.letterSpacing(1).make().shimmer(
                  primaryColor: Vx.purple300,
                  secondaryColor: Colors.white,
                  duration: Duration(seconds: 3),
                ),
            backgroundColor: Colors.transparent,
            centerTitle: true,
            elevation: 0,
          ).h(100).p16(),
          Row(
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 45.0, left: 20),
                child: !openMenu
                    ? IconButton(
                        onPressed: () {
                          scale = 0.6;
                          x = size.width - 120;
                          y = (size.height - size.height * scale) / 3;
                          z = 300;
                          setState(() {
                            openMenu = true;
                          });
                        },
                        icon: Icon(
                          Icons.menu,
                          color: Colors.white,
                        ),
                      )
                    : IconButton(
                        onPressed: () {
                          scale = 1;
                          x = 0;
                          y = 0;
                          setState(() {
                            openMenu = false;
                          });
                        },
                        icon: Icon(
                          Icons.arrow_back_ios,
                          color: Colors.white,
                        ),
                      ),
              ),
            ],
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(
                height: 50,
              ),
              Flexible(
                flex: 5,
                child: CarouselSlider(
                  items: [
                    Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        image: DecorationImage(
                          image: AssetImage('assets/slider-1.jpg'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        image: DecorationImage(
                          image: AssetImage('assets/slider-2.jpg'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        image: DecorationImage(
                          image: AssetImage('assets/slider-3.jpg'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        image: DecorationImage(
                          image: AssetImage('assets/slider-4.jpg'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ],
                  options: CarouselOptions(
                    height: 220,
                    aspectRatio: 16 / 9,
                    viewportFraction: 0.95,
                    initialPage: 0,
                    enableInfiniteScroll: true,
                    reverse: false,
                    autoPlay: true,
                    autoPlayInterval: Duration(seconds: 3),
                    autoPlayAnimationDuration: Duration(milliseconds: 1000),
                    autoPlayCurve: Curves.fastOutSlowIn,
                    enlargeCenterPage: true,
                    onPageChanged: null,
                    scrollDirection: Axis.horizontal,
                  ),
                ),
              ),
              SizedBox(
                height: 20,
              ),
              Flexible(
                flex: 1,
                child: "Radio Life 90.4 FM"
                    .text
                    .bold
                    .xl2
                    .letterSpacing(1)
                    .make()
                    .shimmer(
                      primaryColor: Vx.black,
                      secondaryColor: Colors.white,
                      duration: Duration(seconds: 5),
                    ),
              ),
              SizedBox(
                height: 10,
              ),
              Flexible(
                flex: 3,
                child: InkWell(
                  child: Icon(
                    playing == false
                        ? Icons.play_arrow_outlined
                        : Icons.pause_circle_filled_outlined,
                    size: 150,
                    color: Colors.white,
                  ).shimmer(
                    primaryColor: Vx.purple300,
                    secondaryColor: Colors.grey,
                    duration: Duration(seconds: 3),
                  ),
                  onTap: () {
                    _checkInternetConnection();
                  },
                ),
              ),
              SizedBox(
                height: 20,
              ),
              Flexible(
                flex: 1,
                child: Container(
                  margin: EdgeInsets.only(top: 10),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      InkWell(
                        child: Icon(
                          FontAwesomeIcons.facebook,
                          color: Color(0xFF0F90F3),
                          size: 40,
                        ),
                        onTap: () {
                          launch("https://www.facebook.com/",
                              forceSafariVC: false);
                        },
                      ),
                      InkWell(
                        child: Icon(
                          FontAwesomeIcons.instagram,
                          color: Colors.white,
                          size: 40,
                        ),
                        onTap: () {
                          launch("https://www.instagram.com/",
                              forceSafariVC: false);
                        },
                      ),
                      InkWell(
                        child: Icon(
                          FontAwesomeIcons.youtube,
                          color: Color(0xFFF70000),
                          size: 40,
                        ),
                        onTap: () {
                          launch("https://www.youtube.com",
                              forceSafariVC: false);
                        },
                      ),
                      InkWell(
                        child: Icon(
                          FontAwesomeIcons.twitter,
                          color: Color(0xFF4DA6E9),
                          size: 40,
                        ),
                        onTap: () {
                          launch("https://www.twitter.com/",
                              forceSafariVC: false);
                        },
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  _checkInternetConnection() async {
    var result = await Connectivity().checkConnectivity();

    if (result == ConnectivityResult.none) {
      _showDialog('No Internet', "You're not connected to Network");
    } else {
      if (playing == false) {
        playMusic();
        _showBasicsFlash(
          duration: Duration(seconds: 2),
        );
        setState(() {
          playing = true;
        });
      } else {
        stopMusic();
        setState(() {
          playing = false;
        });
      }
    }
  }

  _showDialog(title, text) {
    showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: Text(title),
            content: Text(text),
            actions: [
              FlatButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text('ok'),
              ),
            ],
          );
        });
  }

  void _showBasicsFlash({
    Duration? duration,
    flashStyle = FlashBehavior.floating,
  }) {
    showFlash(
      context: context,
      duration: duration,
      builder: (context, controller) {
        return Flash(
          controller: controller,
          backgroundColor: Vx.orange400,
          behavior: flashStyle,
          position: FlashPosition.bottom,
          boxShadows: kElevationToShadow[4],
          horizontalDismissDirection: HorizontalDismissDirection.horizontal,
          child: FlashBar(
            content: Text(
              'Please Wait Few Seconds',
              style: TextStyle(color: Colors.white),
            ),
          ),
        );
      },
    );
  }
}

and My AndroidMainfest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.radio">

    <uses-permission android:name="android.permission.INTERNET" /> 
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    
   <application
        android:label="Radio"
        android:usesCleartextTraffic="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by rjshah1902** [comment]
> // ignore_for_file: prefer_const_constructors
> 
> import 'package:flutter/material.dart'; import 'package:font_awesome_flutter/font_awesome_flutter.dart'; import 'package:radiotime/utils/ai_utils.dart'; import 'package:radiotime/utils/all_details.dart'; import 'package:url_launcher/url_launcher.dart'; import 'package:velocity_x/velocity_x.dart'; import 'package:audioplayers/audioplayers.dart'; import 'package:flash/flash.dart'; import 'package:carousel_slider/carousel_slider.dart'; import 'package:connectivity/connectivity.dart';
> 
> class HomePage extends StatefulWidget { @OverRide _HomePageState createState() => _HomePageState(); }
> 
> AudioPlayer audioPlayer = new AudioPlayer();
> 
> bool playing = false;
> 
> void playMusic() async { String url = "http://67.205.99.39/proxy/demo?mp=/stream"; // await Future.delayed(Duration(seconds: 3)); // audioPlayer.play(url);
> 
> int result = await audioPlayer.play(url); if (result == 1) { print('played successfully'); print(audioPlayer.state); } else { print('Something Went Wrong'); } }
> 
> void stopMusic() async { await audioPlayer.stop(); print(audioPlayer.state); }
> 
> final assetsSliderImage = [ 'assets/slider-1.jpg', 'assets/slider-2.jpg', 'assets/slider-3.jpg', 'assets/slider-4.jpg', ];
> 
> class _HomePageState extends State { double x = 0, y = 0, z = 0, scale = 1.0;
> 
> bool openMenu = false;
> 
> @OverRide void initState() { super.initState();
> 
> ```
> if (playing == true) {
>   playMusic();
> }
> ```
> 
> }
> 
> @OverRide Widget build(BuildContext context) { var size = MediaQuery.of(context).size;
> 
> ```
> return AnimatedContainer(
>   duration: const Duration(milliseconds: 200),
>   transform: Matrix4.translationValues(x, y, z)..scale(scale),
>   decoration: BoxDecoration(
>       color: Colors.white,
>       borderRadius: BorderRadius.circular(openMenu ? 30 : 0)),
>   child: Stack(
>     children: [
>       VxAnimatedBox()
>           .size(context.screenWidth, context.screenHeight)
>           .withGradient(
>             LinearGradient(
>               colors: [
>                 AIColors.primaryColor1,
>                 AIColors.primaryColor2,
>               ],
>               begin: Alignment.topLeft,
>               end: Alignment.bottomLeft,
>             ),
>           )
>           .make(),
>       AppBar(
>         title: maintitle.text.xl4.bold.letterSpacing(1).make().shimmer(
>               primaryColor: Vx.purple300,
>               secondaryColor: Colors.white,
>               duration: Duration(seconds: 3),
>             ),
>         backgroundColor: Colors.transparent,
>         centerTitle: true,
>         elevation: 0,
>       ).h(100).p16(),
>       Row(
>         children: [
>           Padding(
>             padding: const EdgeInsets.only(top: 45.0, left: 20),
>             child: !openMenu
>                 ? IconButton(
>                     onPressed: () {
>                       scale = 0.6;
>                       x = size.width - 120;
>                       y = (size.height - size.height * scale) / 3;
>                       z = 300;
>                       setState(() {
>                         openMenu = true;
>                       });
>                     },
>                     icon: Icon(
>                       Icons.menu,
>                       color: Colors.white,
>                     ),
>                   )
>                 : IconButton(
>                     onPressed: () {
>                       scale = 1;
>                       x = 0;
>                       y = 0;
>                       setState(() {
>                         openMenu = false;
>                       });
>                     },
>                     icon: Icon(
>                       Icons.arrow_back_ios,
>                       color: Colors.white,
>                     ),
>                   ),
>           ),
>         ],
>       ),
>       Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>         children: [
>           SizedBox(
>             height: 50,
>           ),
>           Flexible(
>             flex: 5,
>             child: CarouselSlider(
>               items: [
>                 Container(
>                   decoration: BoxDecoration(
>                     borderRadius: BorderRadius.circular(10),
>                     image: DecorationImage(
>                       image: AssetImage('assets/slider-1.jpg'),
>                       fit: BoxFit.cover,
>                     ),
>                   ),
>                 ),
>                 Container(
>                   decoration: BoxDecoration(
>                     borderRadius: BorderRadius.circular(10),
>                     image: DecorationImage(
>                       image: AssetImage('assets/slider-2.jpg'),
>                       fit: BoxFit.cover,
>                     ),
>                   ),
>                 ),
>                 Container(
>                   decoration: BoxDecoration(
>                     borderRadius: BorderRadius.circular(10),
>                     image: DecorationImage(
>                       image: AssetImage('assets/slider-3.jpg'),
>                       fit: BoxFit.cover,
>                     ),
>                   ),
>                 ),
>                 Container(
>                   decoration: BoxDecoration(
>                     borderRadius: BorderRadius.circular(10),
>                     image: DecorationImage(
>                       image: AssetImage('assets/slider-4.jpg'),
>                       fit: BoxFit.cover,
>                     ),
>                   ),
>                 ),
>               ],
>               options: CarouselOptions(
>                 height: 220,
>                 aspectRatio: 16 / 9,
>                 viewportFraction: 0.95,
>                 initialPage: 0,
>                 enableInfiniteScroll: true,
>                 reverse: false,
>                 autoPlay: true,
>                 autoPlayInterval: Duration(seconds: 3),
>                 autoPlayAnimationDuration: Duration(milliseconds: 1000),
>                 autoPlayCurve: Curves.fastOutSlowIn,
>                 enlargeCenterPage: true,
>                 onPageChanged: null,
>                 scrollDirection: Axis.horizontal,
>               ),
>             ),
>           ),
>           SizedBox(
>             height: 20,
>           ),
>           Flexible(
>             flex: 1,
>             child: "Radio Life 90.4 FM"
>                 .text
>                 .bold
>                 .xl2
>                 .letterSpacing(1)
>                 .make()
>                 .shimmer(
>                   primaryColor: Vx.black,
>                   secondaryColor: Colors.white,
>                   duration: Duration(seconds: 5),
>                 ),
>           ),
>           SizedBox(
>             height: 10,
>           ),
>           Flexible(
>             flex: 3,
>             child: InkWell(
>               child: Icon(
>                 playing == false
>                     ? Icons.play_arrow_outlined
>                     : Icons.pause_circle_filled_outlined,
>                 size: 150,
>                 color: Colors.white,
>               ).shimmer(
>                 primaryColor: Vx.purple300,
>                 secondaryColor: Colors.grey,
>                 duration: Duration(seconds: 3),
>               ),
>               onTap: () {
>                 _checkInternetConnection();
>               },
>             ),
>           ),
>           SizedBox(
>             height: 20,
>           ),
>           Flexible(
>             flex: 1,
>             child: Container(
>               margin: EdgeInsets.only(top: 10),
>               child: Row(
>                 mainAxisAlignment: MainAxisAlignment.spaceEvenly,
>                 children: [
>                   InkWell(
>                     child: Icon(
>                       FontAwesomeIcons.facebook,
>                       color: Color(0xFF0F90F3),
>                       size: 40,
>                     ),
>                     onTap: () {
>                       launch("https://www.facebook.com/",
>                           forceSafariVC: false);
>                     },
>                   ),
>                   InkWell(
>                     child: Icon(
>                       FontAwesomeIcons.instagram,
>                       color: Colors.white,
>                       size: 40,
>                     ),
>                     onTap: () {
>                       launch("https://www.instagram.com/",
>                           forceSafariVC: false);
>                     },
>                   ),
>                   InkWell(
>                     child: Icon(
>                       FontAwesomeIcons.youtube,
>                       color: Color(0xFFF70000),
>                       size: 40,
>                     ),
>                     onTap: () {
>                       launch("https://www.youtube.com",
>                           forceSafariVC: false);
>                     },
>                   ),
>                   InkWell(
>                     child: Icon(
>                       FontAwesomeIcons.twitter,
>                       color: Color(0xFF4DA6E9),
>                       size: 40,
>                     ),
>                     onTap: () {
>                       launch("https://www.twitter.com/",
>                           forceSafariVC: false);
>                     },
>                   ),
>                 ],
>               ),
>             ),
>           ),
>         ],
>       ),
>     ],
>   ),
> );
> ```
> 
> }
> 
> _checkInternetConnection() async { var result = await Connectivity().checkConnectivity();
> 
> ```
> if (result == ConnectivityResult.none) {
>   _showDialog('No Internet', "You're not connected to Network");
> } else {
>   if (playing == false) {
>     playMusic();
>     _showBasicsFlash(
>       duration: Duration(seconds: 2),
>     );
>     setState(() {
>       playing = true;
>     });
>   } else {
>     stopMusic();
>     setState(() {
>       playing = false;
>     });
>   }
> }
> ```
> 
> }
> 
> _showDialog(title, text) { showDialog( context: context, builder: (context) { return AlertDialog( title: Text(title), content: Text(text), actions: [ FlatButton( onPressed: () { Navigator.of(context).pop(); }, child: Text('ok'), ), ], ); }); }
> 
> void _showBasicsFlash({ Duration? duration, flashStyle = FlashBehavior.floating, }) { showFlash( context: context, duration: duration, builder: (context, controller) { return Flash( controller: controller, backgroundColor: Vx.orange400, behavior: flashStyle, position: FlashPosition.bottom, boxShadows: kElevationToShadow[4], horizontalDismissDirection: HorizontalDismissDirection.horizontal, child: FlashBar( content: Text( 'Please Wait Few Seconds', style: TextStyle(color: Colors.white), ), ), ); }, ); } }
> 
> and My AndroidMainfest.xml
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" /> 
> <uses-permission android:name="android.permission.WAKE_LOCK" />
> ```

**Comment by Gustl22** [comment]
Can you post a proper issue with the issue template?
