### ISSUE TITLE
Unexpected logging from AudioCache player.play

### ISSUE THREAD

**Issue by jonny7737** [bluefireteam/audioplayers#1030]
### Discussed in https://github.com/bluefireteam/audioplayers/discussions/1026

<div type='discussions-op-text'>

<sup>Originally posted by **jonny7737** October 31, 2021</sup>
How can I stop these messages from appearing every time a player plays?

`"macOS => call play, playerId ae948c90-1108-4d14-96f5-2cbcd3a0982f"
""
`</div>

**Comment by luanpotter** [comment]
macOS will now respect changing the log level to NONE
