### ISSUE TITLE
ios 播放时，导致video_player卡住

### ISSUE THREAD

**Issue by lmx01** [bluefireteam/audioplayers#1031]
请问下，我在使用时，需要在播放视频的时候，同时播放音频，但是这个在ios下，进行音频播放的时候，会导致视频卡住，请问下，有办法解决吗？日志信息：
AVAudioSession_iOS.mm:1206  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
谢谢

**Comment by spydon** [comment]
You'll have to write the issue text in english, otherwise we won't understand.

**Comment by Wisdozzh** [comment]
> AVAudioSession_iOS.mm:1206 Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

我使用的版本是0.19.1

我查看了源码发现在WrappedMediaPlayer 182行
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/16459071/215302870-1dc9d131-1be2-401e-986f-b7a823975404.png">

SwiftAudioplayersPlugin 337行
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/16459071/215302895-5f5686a0-71fd-4203-a7a0-8852817f7396.png">

它将AudioSession设置为不可用，只用这一个插件是没有问题，但是如何和video_player一起使用 ，我理解他们共用一个VideoSession，所以导致video_player卡住，后面就没有声音了。

我的解决方法是：将代码download到本地，将SwiftAudioplayersPlugin 337行注释掉，目前没有发现有什么问题。

**Comment by Gustl22** [comment]
> The version I am using is 0.19.1
>
> I checked the source code and found that in WrappedMediaPlayer line 182

> It sets AudioSession to unavailable, there is no problem to use only this one plugin, but how to use it with video_player , I understand they share a VideoSession, so it causes video_player to be stuck and there is no sound behind it.
> 
> My solution is: download the code locally and comment out SwiftAudioplayersPlugin line 337, no problem found so far.

> Translated with www.DeepL.com/Translator (free version)

@Wisdozzh we don't support such old versions. Also try to translate in in english so everyone can participate in the conversation. DeepL can help you out here.
