### ISSUE TITLE
compile error, bad gateway

### ISSUE THREAD

**Issue by stoneLee81** [bluefireteam/audioplayers#1036]
https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml
This address cannot be found when compiling android app

**Comment by himanshu64** [comment]
`FAILURE: Build failed with an exception.




* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.core:core-ktx:+.
     Required by:
         project :app > project :audioplayers
      > Failed to list versions for androidx.core:core-ktx.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
`

**Comment by himanshu64** [comment]
@spydon is there any way to fix this issue?

**Comment by spydon** [comment]
This is an open Flutter issue https://github.com/flutter/flutter/issues/94400

**Comment by 78Ronin** [comment]
I tried absolutely every suggested solution to the problem, but alas, if the package is removed from the cache, then no option will help.
The service https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml completely closed the campaign, you will have to abandon audioplayers in my project and look for something new, or wait for bintray to come to life ...

**Comment by luanpotter** [comment]
We already migrated all instances of jcenter away: https://github.com/bluefireteam/audioplayers/issues/905
If you grep the repo there is no jcenter left.
So this should be fixed.
