### ISSUE TITLE
Always getting wrong duration

### ISSUE THREAD

**Issue by abhay-s-rawat** [bluefireteam/audioplayers#1039]
`AudioPlayer audioPlayer = AudioPlayer();`
`await audioPlayer.setUrl(path, isLocal: true);`
`await audioPlayer.getDuration();`

Above code always give 5963776 milliseconds for large files near 5-10 mb.

**Comment by abhay-s-rawat** [comment]
Adding `sleep(const Duration(milliseconds: 100));` before calling duration seems to work for me, is it a functionality of a workaround ?

**Comment by apoleo88** [comment]
if instead of `getDuration()` you use its listener
```
 player.onDurationChanged.listen((Duration d) {
    print('Max duration: $d');
    setState(() => duration = d);
  });
```
it works fine

**Comment by Gustl22** [comment]
Closing in favor of #1033
