### ISSUE TITLE
iOS notificationService  seek to time fail 

### ISSUE THREAD

**Issue by SinglTown** [bluefireteam/audioplayers#1040]
in NotificationsHandler file
line 177
let elapsedTime = Int(time.seconds)
the value of "time.seconds " is wrong
need change to, like this  "let elapsedTime = Int(time.seconds*1000)"
you can try

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by luanpotter** [comment]
The notification screen controls were separated from the main package and are now available using the [audio_service package](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#lock-screen-controls).
