### ISSUE TITLE
How do I pause/stop audio from AudioCache? There does not appear to be a method

### ISSUE THREAD

**Issue by MilesAdamson** [bluefireteam/audioplayers#1041]
```
  final player = AudioCache();
  player.play('song.mp3');
  // player.stop()  ??
  // player.pause()  ??
```

Must I play the entire file without the ability to stop it?

**Comment by erickzanardo** [comment]
You can stop, pause, etc. Check how to control with AudioCache on our docs: https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/doc/audio_cache.md

**Comment by wahyu-handayani** [comment]
@erickzanardo would you like to give an example how to do stop and pause by using ```AudioCache``` because I have read the source from the link you have given but I am still confused

**Comment by nashihu** [comment]
you should change

    final player = AudioCache();

to 

    final player = AudioCache(fixedPlayer: AudioPlayer());

to stop, you can call

    player.fixedPlayer?.stop();
