### ISSUE TITLE
Ability to save streamed file locally?

### ISSUE THREAD

**Issue by IrosTheBeggar** [bluefireteam/audioplayers#105]
I'm making an audio player app and I want to add an option to store streamed files locally in-case the user decides to play them again.

Is there any way to extract the data from the player and save it to disk?  Also is there a callback or way to determine when the entire file has been loaded?

Thanks for the great package!

**Comment by erickzanardo** [comment]
I think is a little out of scope from this package, but will keep this open as an enhancement for the future.

**Comment by emme10** [comment]
This would be a feature that woud be great to have. 

I use firebase to load the audios and it uses a lot of quota if every file has to be downloaded again and again.

**Comment by Gustl22** [comment]
I think it would be a nice addition in AudioCache to optionally cache url sources and play them as "local source".

**Comment by Gustl22** [comment]
Closing in favor of #374
