### ISSUE TITLE
assets_audio_flutter package..when I try to execute the code on visual cod...it stays for hours trying to execute without any result

### ISSUE THREAD

**Issue by subhiabdullah1999** [bluefireteam/audioplayers#1052]
welcome.. I need help..I'm working on flutter..when I embed the assets_audio_flutter package..when I try to execute the code on visual cod...it stays for hours trying to execute without any result..when I delete the package and go back to executing the app works

**Comment by himanshubalani** [comment]
Same here... Gradle Task assembleDebug takes forever, I have tried all methods of solving that available on StackOverflow but failed. when i delete the audioplayers, it starts working as intended

**Comment by luanpotter** [comment]
This is the `audioplayers` package; I am not sure what the `assets_audio_flutter` is as it does not seem to exist but this is not the place for this issue.
