### ISSUE TITLE
cant play local sound

### ISSUE THREAD

**Issue by shaco75** [bluefireteam/audioplayers#1054]
**when i press the sound button it show error :**
E/flutter (30513): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unable to load asset: assets/sound/1.mp3
E/flutter (30513): #0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:237
E/flutter (30513): <asynchronous suspension>
E/flutter (30513): #1      AudioCache.fetchToMemory
package:audioplayers/src/audio_cache.dart:89
E/flutter (30513): <asynchronous suspension>
E/flutter (30513): #2      AudioCache.load
package:audioplayers/src/audio_cache.dart:115
E/flutter (30513): <asynchronous suspension>
E/flutter (30513): #3      AudioCache.play
package:audioplayers/src/audio_cache.dart:159
E/flutter (30513): <asynchronous suspension>
E/flutter (30513):

**and i have been edited the pubspec.yaml already :**

flutter:

  uses-material-design: true
  assets:
    - sound/

**Comment by innerk** [comment]
i'm having the same issue, any update on this?

**Comment by shaco75** [comment]
> You're importing it wrong.
> 
> It's `- assets/sound/`.

@mkay-42069 
No i tried this too bad it's fault and its show red line under the "assets" its mean there is no folder named like that , thank you for you comment .

**Comment by shaco75** [comment]
@innerk no sorry , if you find the answer please let me know , thank you .

**Comment by innerk** [comment]
@shaco75 hey try this one [https://pub.dev/packages/just_audio](url) just import your assets and make sure it's the correct path, then use player.setAsset('assets/bird.mp3') or from url and voila

**Comment by mkay-42069** [comment]
> > You're importing it wrong.
> > It's `- assets/sound/`.
> 
> @mkay-42069 No i tried this too but it's fault and its show red line under the "assets" its mean there is no folder named like that , thank you for you comment .

Sorry for not being clearer.  You have to have it in the literal **assets** folder, because its hardcoded.
See: https://github.com/bluefireteam/audioplayers/blob/46816bf55859c9c88b204e3828cce6190ff87483/packages/audioplayers/lib/src/audio_cache.dart#L57

**Comment by luanpotter** [comment]
> Sorry for not being clearer. You have to have it in the literal assets folder, because its hardcoded.

Exactly.
Or you can change the prefix if you don't want to go with the convention.
