### ISSUE TITLE
Sound is degraded when local asset is played several times with AudioCache 

### ISSUE THREAD

**Issue by apleton** [bluefireteam/audioplayers#1058]
I use AudioCache with a fixedPlayer as my app must be able to play the same sound several times. When the audio file is played for the first time, it works fine. But when the file is played a second time, after a few seconds, the volume of the sound is lower, and the quality is degraded. All the subsequent playing will sound like that. If I don't play the sound during > 1 min, it will eventually come back to its original state and sounds OK again. 

I can repro the issue with this sample code : 

```
class _MyViewState extends State<MyView>{

  _MyViewState();
  final AudioCache _testAudioPlayer = AudioCache();

  @override
  void initState() {
    super.initState();
    _testAudioPlayer.fixedPlayer = AudioPlayer();
  }

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: (){
        _testAudioPlayer.play("audio/stick1.wav");
      },
      child: const Text('Play Sound'));
  }
}
```

Edit : this is tested on iOS

**Comment by Gustl22** [comment]
Which version? Can you test with `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
