### ISSUE TITLE
Add migration guide when changing APIs

### ISSUE THREAD

**Issue by ChristianKleineidam** [bluefireteam/audioplayers#1061]
The change to 0.19.0 makes breaking changes, but it seems like there's no place where a migration guide is documented that I can find linked in the changelog. 

What's the replacement for 'package:audioplayers/audio_cache.dart'?

**Comment by erickzanardo** [comment]
iirc 

package:audioplayers/audioplayers.dart'

Audio cache still there, just the import changed

**Comment by luanpotter** [comment]
I am working on one for v1 :)

**Comment by luanpotter** [comment]
[migration guide for v1](https://github.com/bluefireteam/audioplayers/blob/main/migration_guide.md)
