### ISSUE TITLE
Android - Volume of background music changes on notification

### ISSUE THREAD

**Issue by BrianDevOK** [bluefireteam/audioplayers#1063]
When certain buttons are clicked, a short 'click' sound is played.  However, if I have Pandora playing in the background, when the 'click' sound happens, the background volume is decreased until I pause and start it back in Pandora.  How can I prevent the volume of the background from decreasing.  Here's what I have.  Any improvements appreciated:

```
class AudioController extends GetxController {

  final AudioCache player = AudioCache(duckAudio: true, respectSilence: true, fixedPlayer: AudioPlayer(mode: PlayerMode.MEDIA_PLAYER));
  onButtonClick() {
    player.play('sounds/open.mp3', isNotification: true);
  }
}
```

Thanks

**Comment by luanpotter** [comment]
That is because you are setting `duckAudio` to true. It is doing exactly what it should be.
