### ISSUE TITLE
How can i use Android system sdk file directory to play audio?

### ISSUE THREAD

**Issue by xizan** [bluefireteam/audioplayers#1069]
Hello!
    How can i use Android system SD file directory to play audio? This audio files are downloaded and save to SD file.

**Comment by Gustl22** [comment]
I think so, if you have the permissions. But for external storage I'm not sure: https://github.com/flutter/flutter/issues/40504
Maybe you need a third party package to access it.

**Comment by xizan** [comment]
您好！   邮件已收到、 祝您生活愉快、 谢谢！
Hello! your mail is received,good luck to you.Thank you !
