### ISSUE TITLE
File *.wav can't play

### ISSUE THREAD

**Issue by wrjcs** [bluefireteam/audioplayers#1075]
Hello,
I used an wav file in assets, load by rootBundle.load('assets/ao.wav');
code like this:
wav = await rootBundle.load('assets/ao.wav');
audioPlayer = AudioPlayer();
await audioPlayer?.setReleaseMode(ReleaseMode.STOP);
await audioPlayer?.playBytes(wav!.buffer.asUint8List());
it works.

!~=============================================!!

But when I change to load by local file, it doesn't work.
File file = File("/storage/emulated/0/Download/alert.wav");
var bytes = file.readAsBytesSync();
var audioPlayer = AudioPlayer();
await audioPlayer?.setReleaseMode(ReleaseMode.STOP);
audioPlayer.play(result.files.single.path!, isLocal: true);

which difference?

Thanks.

**Comment by maxstubbersfield** [comment]
Hi there, 
I think you might want to try using `AudioCache` instead of `AudioPlayer` when loading the file from the assets directory.

Try this:
```
final audioCache = AudioCache();
audioCache.play('ao.wav'); // the assets prefix is already defined by default
```

You may also want to consider using Low Latency mode if that is applicable for your use case.
```
audioCache.play('ao.wav', mode: PlayerMode.LOW_LATENCY);
```

**Comment by wrjcs** [comment]
Hello,
I use the file is in external storage, and the path is allow use to define.
I use andioCache to play, I have this exception:
Unable to load asset: assets//data/user/0/fr.weshop.weshop_x/cache/file_picker/alert.wav

**Comment by wrjcs** [comment]
P.S.
I use the plugin "file_picker" to allow user to select the file of wav.

**Comment by mzohren** [comment]
Are you aware that the path in 
`audioPlayer.play(result.files.single.path!, isLocal: true);`

Is not what you are reading in your failing example ?!

You are creating _file_ , reading it's bytes and never use that, instead _play()_ is calling someting entirely different.
You may want to try :
`audioplayer.playBytes(bytes);`

**Comment by wrjcs** [comment]
I tried audioplayer.playBytes(bytes), but it didn't work.

Could you give me an exemple which can work correctly?

**Comment by luanpotter** [comment]
In the new version, you can load local assets via `setSource(AssetSource(asset))`.
Please see the example app for more details.

**Comment by metaces** [comment]
For me works like this:

AudioPlayer audioPlayer = AudioPlayer();
audioPlayer.play(AssetSource('note2.wav'));
