### ISSUE TITLE
AudioCache stop() or simular like playerID

### ISSUE THREAD

**Issue by Progressed36** [bluefireteam/audioplayers#1076]
Hi,

I created a custom function to my FlutterFlow when you click an image it plays a sound (from assets). There are multiple images and when tapping them they all play nicely, but i need it to stop when a new image is tapped.. According to your docs you need Audicache to be able to play local assets but its limited in the options.

So like the title suggests i would like to be able to stop the sounds when tapping a image OR like AudioPlayers a playerId that replaces the sound every time you play a sound.

`Future playSound(String sound) async {
  AudioCache player = AudioCache();
  var audio = 'audios/' + sound;
  player.play(audio);
}`

**Comment by mzohren** [comment]
Simply check the playerstate and call stop() before playing another sound.
I usually encapsulate AudioPlayer in a sigleton to have more tight control over the instance in these cases.

Eg.(PseudoCode, please check the documentation.)
```
var playerState = audioplayer.PlayerState;
if (playerState == PlayerState.PLAYING)  {
await audioplayer.stop();
}
audioplayer.play(newsound);

```

**Comment by TheStrongest** [comment]
I'm also experiencing the same problem. I can't stop AudioCache
