### ISSUE TITLE
Audio file name in Arabic can't be played

### ISSUE THREAD

**Issue by tajaouart** [bluefireteam/audioplayers#1077]
The audio does not play when it has a name in Arabic alphabets on iOS but work fine on Android.

**Full Description**
My app plays audios from the asset folder, i deployed the app on PlayStore and it works fine for Android, once i wanted the iOS version it does not work, when i try to read a file with a name in latin it works perfectly.

**Code to Reproduce**
file path : assets/audios/أبيض.mp3
```dart

final AudioPlayer _audio = AudioPlayer(playerId: 'playerID');
late AudioCache audioPlayer;

init state :
audioPlayer = AudioCache(
      prefix: 'assets/audios/',
      fixedPlayer: _audio,
    );

later in code..

audioPlayer.play('أبيض.mp3');
```

**Log Errors**
```dart
flutter: +++++++صفر.mp3++
"iOS => call setReleaseMode, playerId playerID"
"iOS => call play, playerId playerID"
flutter: event PlayerState.PLAYING
""
flutter: event PlayerState.STOPPED  // the playing and stopped state are printed instantly at the same time, no COMPLETED status
```

**Platforms**
Android: works fine.
iOS :  not working

* OS: iOS
* OS version: 14.6
* Device: physical device iPhone SE
* audioplayers version: 0.20.1
* release or not release: debug + profile mode
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale en-FR)
    • Flutter version 2.10.2 at /Users/aksel/fvm/versions/2.10.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (8 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/aksel/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio
    • Android Studio at /Users/aksel/Downloads/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio
    • Android Studio at /Users/aksel/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/aksel/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Devmobile’s iPhone (6) (mobile) • ------------------ • ios            • iOS 14.6 18F72

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by tajaouart** [comment]
When debugging, the final uri of the audio file looks like,
file:///var/mobile/Containers/Data/Application/7718976F-DD88-4E8B-AA68-90A8793EEDFF/Library/Caches/%D8%A3%D8%A8%D9%8A%D8%B6.mp3

so to overcome the issue while waiting for a good solution i made this in play method in packages/audioplayers/lib/src/audio_cache.dart:

```dart
uri.toString().replaceFirst(
            uri.toString().substring(
                  uri.toString().lastIndexOf('/'),
                ),
            '/$fileName',
          )


```

**Comment by Sundin** [comment]
Same issue as  #972

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/bluefireteam/audioplayers/issues/972

@tajaouart (or anyone) feel free to submit a PR if there is something that needs to be fixed on our current implementation
