### ISSUE TITLE
NULL Pointer exception on iOS when notoficationService.startHeadlessService()

### ISSUE THREAD

**Issue by t-m-z** [bluefireteam/audioplayers#1081]
audioCache.fixedPlayer?.notificationService.startHeadlessService(); causes NULL Pointer exception

**Full Description**
`if (Platform.isIOS) {
      audioCache.fixedPlayer?.notificationService.startHeadlessService();
    }`
causes a NULL-Pointer exception: NoSuchMethodError: The method 'startHeadlessService' was called on NULL. Receiver: null. Tried calling startHeadlessService()

Without this line no exception raised but no sound is to be heard or time data is provided.

**Code to Reproduce**
@override
  void initState() {
    super.initState();

    if (kIsWeb) {
      // Calls to Platform.isIOS fails on web
      return;
    }
    if (Platform.isIOS) {
      audioCache.fixedPlayer?.notificationService.startHeadlessService();
    }

**Log Errors**
NoSuchMethodError: The method 'startHeadlessService' was called on NULL. Receiver: null. Tried calling startHeadlessService()

**Files/URLs/Sources**
not applicable.

**Screenshots**
not applicable

**Platforms**
* OS: iOS, current version
* Device: Emulator iPhone 11 Max, and real iPhone 11 Max
* flutter version: flutter xcode 11.6
* audioplayers version: current version
* does the error occur and does it have any peculiarities: no

**Comment by luanpotter** [comment]
This is no longer an issue on v1 as this part was removed.
