### ISSUE TITLE
Flutter web, Audio is not playing after upload on the server.

### ISSUE THREAD

**Issue by pramodkr123** [bluefireteam/audioplayers#1090]
Flutter web, Audio is not playing after upload on the server.

**Comment by spydon** [comment]
Please elaborate what is not working and what you have tried.

**Comment by ekoRemDev** [comment]
I had a similar issue, an audio file is not being played on the browser. 
In my case, there were 2 different issues

1. assets you want to play are not in the correct place
2. Autoplay policy- browser-related issue. 
Chrome has an explanation for this. [Autoplay policy in Chrome](https://developer.chrome.com/blog/autoplay/)


@pramodkr123 do you get any error in the console that can help us to understand the issue

**Comment by pramodkr123** [comment]
In my case audio was playing in localhost but after upload on server audio was not playing.

**Comment by spydon** [comment]
> In my case audio was playing in localhost but after upload on server audio was not playing.
> 

You have to describe more in detail how you were playing the remote file, preferably posting the code, otherwise we can just guess what has gone wrong.
