### ISSUE TITLE
unable to play any audio

### ISSUE THREAD

**Issue by mhdaslam790** [bluefireteam/audioplayers#1092]
` [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`

so when i am trying to play sound it gives this exception . earlier i think in flutter version 2.5.0 it is working fine but after my project got update to 2.10.0 . it is not working.

**Comment by luanpotter** [comment]
Please update to follow the issue template.

**Comment by Gkemon** [comment]
Hi, @luanpotter  is it updated or still working?  I actually don't get the tag named "changes-requested"
