### ISSUE TITLE
[Windows] 1.0.0-rc.1 MissingPluginException(No implementation found for method setPlayerMode on channel xyz.luan/audioplayers)

### ISSUE THREAD

**Issue by Ephenodrom** [bluefireteam/audioplayers#1095]
Hello,

I tried out the new release candidate and build my app on Windows. While trying out the app I received the following error:

```
MissingPluginException(No implementation found for method setPlayerMode on channel xyz.luan/audioplayers)
```
Stacktrace
```
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
<asynchronous suspension>
#1      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:100)
<asynchronous suspension>
#2      AudioPlayersImpl.play (package:samplepad_live/src/models/AudioPlayersImpl.dart:34)
<asynchronous suspension>
```

This is the code used : 

```dart
await player!.play(DeviceFileSource( "path/to/my/file") ,volume: 100, mode: PlayerMode.mediaPlayer);
```

**Comment by luanpotter** [comment]
ah we probably need to add a no-op impl. good catch!

**Comment by luanpotter** [comment]
I think this should fix it: https://github.com/bluefireteam/audioplayers/pull/1096

I don't have access to a windows machine now to test it though, I can do it later, or feel free to take a look too @Ephenodrom

**Comment by Ephenodrom** [comment]
@luanpotter I testet it on Windows 10 within a VM and it worked fine. Waiting for the next rc release on pub.dev :)
