### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'Source'

### ISSUE THREAD

**Issue by cfuj** [bluefireteam/audioplayers#1098]
["one liner" - `AudioPlayer.play()` formerly worked with a String argument, but RC 1 requires a Source. `Source` is an abstract class, so I don't understand how to create one. Thanks!

**Full Description**
I'm sure that this is not a bug, but that the RC documentation is not up to date.

**Code to Reproduce**
`player.play('myFile.mp4");`

**Platforms**
I was using 20.1 for an Android/IOS/Windows application I'm developing, but I was having issues getting Windows to recognize `player.play();` so I tried to update to this, as other issues with windows and `player.stop()` and other functions had suggested that RC-1 should fix it.

Thank you so much for all your effort in this plugin.

**Comment by cfuj** [comment]
I found the solution, sorry:

`player.play(UrlSource("myFile.mp4));`

**Comment by Sarat-1997** [comment]
> I found the solution, sorry:
> 
> `player.play(UrlSource("myFile.mp4"));`

Thanks @cfuj . It works.
