### ISSUE TITLE
[1.0.0-rc.1] Won't play sound through Bluetooth speakers by default

### ISSUE THREAD

**Issue by Sundin** [bluefireteam/audioplayers#1101]
I noticed that when upgrading to the new version 1.0.0-rc.1, sound won't play through speakers/headphones connected via Bluetooth anymore. I reproduced this issue on several iOS devices, didn't try it out on Android yet. A working solution is provided further down for others experience this issue as well.

**Full Description**
The default behavior seem to have changed in at least two ways when upgrading to version 1.0.0-rc.1:
- External bluetooth speakers/headphones refuse to play sound coming from audioplayers. That sound is being played by the phone's internal speakers instead. Good ol' trusty wired headphones still work though.
- Audio from other applications are not stopped by default when starting to play from my own app anymore.

**Code to Reproduce**
```
AudioPlayer ambienceSound = new AudioPlayer(playerId: 'ambience');
await ambienceSound.play(AssetSource("noises/ambience_sound.mp3"), volume: 0.5, position: Duration());
```

**Log Errors**
- None -

**Platforms**
At least on iOS (both iPhone and iPad), didn't try on other platforms yet.

**Solution**
I figured the issue had to do with the default AudioContextConfig not being the same anymore. This might be intentional (or not), but in either case the documentation in the code is not up to date with the actual default behaviour. But providing my own config I was able to get the behaviour I'm after (same as how it worked in previous versions of audioplayers, at least in respect of bluetooth speakers and muting audio from other applications). Here's some code for a working solution/workaround to others who might encounter this issue:

    var conf = AudioContext(
        android: AudioContextAndroid(
          isSpeakerphoneOn: false,
          stayAwake: true,
          contentType: AndroidContentType.music,
          usageType: AndroidUsageType.game,
          audioFocus: AndroidAudioFocus.gain,
        ),
        iOS: AudioContextIOS(
          defaultToSpeaker: false,
          category: AVAudioSessionCategory.playback,
          options: <AVAudioSessionOptions>[],
        )
    );
    GlobalPlatformInterface.instance.setGlobalAudioContext(conf);

Note that I didn't verify the Android settings yet but the constructor require both.

**Comment by luanpotter** [comment]
Thanks for the detailed explanation, @Sundin.
My original goal was not to change the default values for AudioContext.
I will compare the current defaults with what you provided to see how we can fix this (forceSpeaker seems to already be false by default, must be something else).
And sorry by the lack of docs, as you saw, I am still working on that.

**Comment by xywai1993** [comment]
@Sundin   

`var conf = AudioContext(
    android: AudioContextAndroid(
      isSpeakerphoneOn: false,
      stayAwake: true,
      contentType: AndroidContentType.music,
      usageType: AndroidUsageType.game,
      audioFocus: AndroidAudioFocus.gain,
    ),
    iOS: AudioContextIOS(
      defaultToSpeaker: false,
      category: AVAudioSessionCategory.playback,
      options: <AVAudioSessionOptions>[],
    )
);
GlobalPlatformInterface.instance.setGlobalAudioContext(conf);`


I encountered the same problem, but I don't know this code where and when to be used . I'm a novice.I input this code to initState,but don't work.
