### ISSUE TITLE
Set volume for both earpieces (left and right) individually - setVolume Method

### ISSUE THREAD

**Issue by superwebarmy** [bluefireteam/audioplayers#1103]
Hi, Hope you are doing well. In android native, MediaPlayer has a method called setVolume which accepts two parameters, left volume and right volume. Basically, it lets you set the volume for both earpieces individually 

Can you please include such a feature in the audio player package? That would be great!

Thank you

**Comment by superwebarmy** [comment]
I looked into the code and found out that you are using setVolume but currently you are letting users to pass only one argument in setVolume, so it sets the same value to both left and right volume

It would be great if you allow users to pass both arguments for setMethod (one for left and other one for right volume)

**Comment by superwebarmy** [comment]
Thank you for answering my query :) it would be great if you let user set the volume for both volume scalars 

This would give us more freedom in terms of interacting with the volume functionality :)

I understood your concern that you need to consider every platform while publishing new features 

maybe you could create a separate function for setVoume (accepts both parameter)  that is specifically available for android platform

**Comment by superwebarmy** [comment]
Any update on this requested feature? @luanpotter :)

**Comment by Gustl22** [comment]
Closing in favor of #58
