### ISSUE TITLE
MissingPluginException(No implementation found for method open on channel assets_audio_player)

### ISSUE THREAD

**Issue by abhihasabe** [bluefireteam/audioplayers#1105]
- MissingPluginException(No implementation found for method stop on channel assets_audio_player)
- I/flutter ( 6657): MissingPluginException(No implementation found for method open on channel assets_audio_player)
- E/flutter ( 6657): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method open on channel assets_audio_player)

**Comment by F-BONAPARTA** [comment]
same here

**Comment by heshesh2010** [comment]
try to run flutter clean , then rebuild app again

**Comment by luanpotter** [comment]
There is no such channel, `assets_audio_player`?  why is that being used?

**Comment by Mae623** [comment]
I come across this problem too
flutter clean and rebuild doesn't work
is there any advices？

**Comment by Gustl22** [comment]
Can you provide a working code sample in a repository? This method doesn't exist in this package.

**Comment by komaxx** [comment]
Are you guys talking about this issue:
https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/523
?

You might be in the wrong repo here?

**Comment by Gustl22** [comment]
@komaxx I think so, thanks. Closing this :)
