### ISSUE TITLE
[1.0.0-rc.1] Volume value isn't passed down on first init

### ISSUE THREAD

**Issue by mkay-42069** [bluefireteam/audioplayers#1106]
While testing v1 I came across a bug which prevents a set volume value to be recognized by the player on init.

For example: I set the volume to 0.5 and on initializing the player it won't recognize the set value and will always default back to 1.0. Which is weird since playing that very same audio again, the player passes the value down and sets the volume accordingly.

**Code to Reproduce**
```dart
final player = AudioPlayer();

ElevatedButton(
            onPressed: () {
              player.play(
                AssetSource(
                  'nasa_on_a_mission.mp3',
                ),
                volume: 0.5,
              );
            },
            child: const Text('PLAY'),
          ),
```

**Log Errors**
- none

**Files/URLs/Sources**
- none

**Screenshots**
- none

**Platforms**
Tested on both iOS and macOS, where the bug shows up.
On Android it works accordingly.

**Comment by luanpotter** [comment]
Should be fixed on main (or RC3 soon)
