### ISSUE TITLE
setVolume method is not working

### ISSUE THREAD

**Issue by superwebarmy** [bluefireteam/audioplayers#1107]
The setVolume method of the audio player is not working. For example: When I set the volume value to 0, it should mute the volume, right? but I can still hear the volume despite setting the volume to 0

`
AudioPlayer audioPlayer = AudioPlayer();

void playMusic() async {
await audioPlayer.setVolume(0); // Not working
audioPlayer.play(url); // I can still hear the volume despite setting the volume value to zero
}
`

**Comment by jinosh05** [comment]
> AudioPlayer audioPlayer = AudioPlayer();
> 
> void playMusic() async { await audioPlayer.setVolume(0); // Not working audioPlayer.play(url); // I can still hear the volume despite setting the volume value to zero } `



Actually you haven't understood the play function. The default value of volume while playing the url is set to 1 by default and you have to set that particular volume like this .


  AudioPlayer audioPlayer = AudioPlayer();

  void playMusic(String url, double? volume) async {
    audioPlayer.play(url, volume: volume ?? 1);
    // Setting Volume 1 to play the music at full volume and
    // if you send value 0, it was muted
  }

**Comment by superwebarmy** [comment]
Sorry but I didn’t get your point! Can’t we use the setVolume method to set the volume instead of setting it inside the play method

you may ask why would you want to use the setVolume method 

because setVolume method allows you to set the volume for left and right volume scalar

**Comment by superwebarmy** [comment]
see (native code) it lets you set volume for both left and right volume scalar 

![BB1F6F25-DDA6-4423-A842-84122C0C7355](https://user-images.githubusercontent.com/94928609/163838226-6af961fd-d5c8-4b15-a267-36d9b4d610a4.jpeg)

**Comment by superwebarmy** [comment]
There could be one possibility on why setVolume isn't working

Maybe the volume value of setMethod is getting overwritten by the volume of the play method @jinosh05

**Comment by jinosh05** [comment]
> AudioPlayer audioPlayer = AudioPlayer();
> 
> void playMusic(String url, double? volume) async { audioPlayer.play(url, volume: volume ?? 1); // Setting Volume 1 to play the music at full volume by default and // if you send value 0, it was muted }



> There could be one possibility on why setVolume isn't working
> 
> Maybe the volume value of setMethod is getting overwritten by the volume of the play method @jinosh05

Actually, the default value of the play method is
 Future<int> play(
    String url, {
    bool? isLocal,
    double volume = 1.0,
    // position must be null by default to be compatible with radio streams
    Duration? position,
    bool respectSilence = false,
    bool stayAwake = false,
    bool duckAudio = false,
    bool recordingActive = false,
  }) async {....}

Here the volume is controlled manually, so we have to pass the volume override it.

To use the setVolume you can code like this.
AudioPlayer audioPlayer = AudioPlayer();

  void playMusic(String url, {double? volume}) async {
    audioPlayer.setUrl(url);
    audioPlayer.setVolume(volume ?? 1);
    audioPlayer.resume();
  }

**Comment by luanpotter** [comment]
good catch. I will make the volume parameter on play nullable and optional, instead of default to 1, it should default to no-op

**Comment by luanpotter** [comment]
Should be fixed on main (or RC3 soon)
