### ISSUE TITLE
Background Media Player Lock Screen and Notification Screen Android and IOS.

### ISSUE THREAD

**Issue by JayswalViraj** [bluefireteam/audioplayers#1108]
Have you best and easy example for Background Media Player Lock Screen and Notification Screen IOS and Android both platform?

**Comment by cgorka** [comment]
> Have you best and easy example for Background Media Player Lock Screen and Notification Screen IOS and Android both platform?

I also need a solution to play short sounds from an application in the background without pausing music, is that possible?
