### ISSUE TITLE
[v1 rc2] Send end status after 03:30 

### ISSUE THREAD

**Issue by poka-IT** [bluefireteam/audioplayers#1119]
Strange bug, but in remote playing, with audioplayer version, when I set the position after 03:30 of a track, even this track is 5 minutes long or more, it will send a end status and stop.

**Full Description**
This is a song exemple: https://vid.puffyan.us/latest_version?id=UZZo0KEa2Wo&itag=140&local=true&listen=1
Try to play it with audioplayer, then move the cursor to the 5th minute.
There is no problem if we don't try to set the position, the song continue to play until end, even after 03:30.
Problem is only when we set position after 03:30 (see gif above).

**Code to Reproduce**
https://git.p2p.legal/poka/fipy/src/branch/kplayer2audioplayer/lib/screens/home.dart#L308-L339

**Log Errors**
No errors in logs, just a `end` status event sent when set position after 03:30.

**Files/URLs/Sources**
https://git.p2p.legal/poka/fipy/src/branch/kplayer2audioplayer

**Screenshots**
![audioplayer_bug](https://user-images.githubusercontent.com/4574805/167299254-4638b001-f30f-430b-989a-b3af502d56d1.gif)

**Platforms**
Tried on Windows 10.

* flutter version: 
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.13.0-0.3.pre, on Microsoft Windows [version 10.0.19044.1645], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.13)   
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.67.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```
* audioplayers version: 1.0.0-rc.2
* release or not release: Release an debug
* does the error occur and does it have any peculiarities: On each song longer than 03:30.

**Comment by luanpotter** [comment]
What platform? what audio? Please follow the issue template to include necessary information.

**Comment by poka-IT** [comment]
I updated my issue.

**Comment by mohamadlounnas** [comment]
>  I tried to find a solution for it but a part of C++ code is behaving strangely SeekTo(uint64_t position)
> after 210 second when position passed to SeekTo(uint64_t position) the number be something different (exactly a very big integer)

![image](https://user-images.githubusercontent.com/22839194/167530271-d3b07945-2558-41a2-b328-616292eafd2f.png)
![image](https://user-images.githubusercontent.com/22839194/167530398-8eb45a56-fd91-499f-8b17-84785752e232.png)

**Comment by poka-IT** [comment]
Hum no this is not resolved.

**Comment by maintel** [comment]
This problem is caused by the out-of-bounds value set by seekto。
I fixed this error locally on my own and everything works fine so far。
The repair method can be found [here](https://github.com/bluefireteam/audioplayers/pull/1125/commits/101df46359937cbafdb274587f25ce39d4bb944b)
