### ISSUE TITLE
audioplayer.onDurationChanged not returning any audio duration in linux (Ubuntu)

### ISSUE THREAD

**Issue by tl2a** [bluefireteam/audioplayers#1126]
onPositionChanged is working as expected but the onDurationChanged is returning nothing or 0. Not sure what is wrong or is it an actual issue. Though the same code works in Android without any changes.

**Code to Reproduce**
```
void updateTime(audioplayer) {
    audioplayer.onDurationChanged
        .listen((Duration d) => {setState(() => duration = d)});

    audioplayer.onPositionChanged
        .listen((Duration p) => {setState(() => position = p)});
 }
```

**Log Errors**
AudioPlayers: Could not query current duration.

![Screenshot from 2022-05-13 14-45-04](https://user-images.githubusercontent.com/40720310/168252535-c1523135-9fa7-4868-96c1-e3142d906461.png)

**Platforms**
Platform: Linux
Ubuntu Version: 20.04.3 LTS
OS: Elementary OS 6.1 Jolnir
Audioplayers version: 1.0.0-rc.4
Flutter Version: 3.1.0-0.0.pre.666
Dart version: 2.18.0

**Dependencies Installed**
```sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad```

**Comment by eximius313** [comment]
Is Linux Platform officially supported? It's not listed in pub.dev
![image](https://user-images.githubusercontent.com/5578017/168843669-5d083af5-25a5-4f1b-b3be-5420705e0855.png)

**Comment by tl2a** [comment]
Thanks @Gustl22  for the fix and also freeing source helps me avoid having multiple instances now. Awesome :heart:
@eximius313 actually I am using the prerelease version.

**Comment by Feichtmeier** [comment]
Hi, I didn't want to open another issue so here is the question on the streams:

Created an [Ubuntu music player](https://github.com/ubuntu-flutter-community/musicpod) using your package(s) and everything is working fine so far
The only issue is that I get constantly this output when calling play 

```
AudioPlayers: Could not query current position.
AudioPlayers: Could not query current duration.
```

This is the file that creates, controls and diposes the AudioPlayer instance:

https://github.com/ubuntu-flutter-community/musicpod/blob/main/lib/app/player_model.dart

It is a ChangeNotifierProvider with a player-UI widget as child. Is there anything wrong in how I do this? Thanks in advance and thanks for creating this package :bow:

**Comment by Gustl22** [comment]
@Feichtmeier no there's nothing wrong. Some other methods require the `getDuration` method e.g. in order to determine, if it's a live stream and therefore this log is emitted. This may can be improved from our side, but nothing to worry about.

**Comment by Feichtmeier** [comment]
> @Feichtmeier no there's nothing wrong. Some other methods require the `getDuration` method e.g. in order to determine, if it's a live stream and therefore this log is emitted. This may can be improved from our side, but nothing to worry about.

Wow thank you! :) I was really worried! Great, 👍🙂 Ty for answering
