### ISSUE TITLE
audioPlayer dispose

### ISSUE THREAD

**Issue by LeeRHuang** [bluefireteam/audioplayers#1141]
**after init a audioPlayer instance in initState, and play a remote mp3 url audio successful，and then before close this page ,i called  audioPlayer?.dispose(); audioPlayer = null direct and on dispose(); override function ,but i find sometimes maybe the audioPlayer instance is not release when networking request is not response,because the audio is still in playing after this page is closed.it troubled me for long time,other conditions i hava tried,still the same result,hope to recevie help me slove this promble,thanks.**

**Comment by LeeRHuang** [comment]
modfiy

**Comment by Gustl22** [comment]
Can you check if it's fixed in `audioplayers: ^1.1.0`. Also provide a proper issue template with example repository.
