### ISSUE TITLE
Method 'play' is not defined for AudioCache

### ISSUE THREAD

**Issue by shady-ti** [bluefireteam/audioplayers#1142]
**Can't build app as method `play` is not defined.**

## Full Description
Not more than the one-liner, so I'll drop some screenshots instead.

- Assets folder:
  <img width="257" alt="image" src="https://user-images.githubusercontent.com/91265151/170874586-feda44e7-0550-4ff7-a517-a9056abf38b3.png">

- Error:
  <img width="1229" alt="image" src="https://user-images.githubusercontent.com/91265151/170874960-19783e52-a634-419e-8ead-122c28579c9f.png">

## Code to Reproduce

```dart
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';

void main() {
  final player = AudioCache();
  player.play('explosion.mp3');
}

class Main extends StatelessWidget {
  const Main({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(),
    );
  }
}
```

## Platforms

- Windows
- Linux

**Comment by Gustl22** [comment]
No need for Audiocache since 1.x.x, see [example](https://github.com/bluefireteam/audioplayers/blob/b523a39e253dd461b07c360d7547eef9bb54cd65/packages/audioplayers/example/lib/main.dart#L24)

**Comment by shady-ti** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/91265151/170884748-7e05e23a-cb94-48f6-a7a0-87a89eb33937.png">

**`AudioCache` is missing implementations for these members**

**Comment by faizanMayo786** [comment]
AudioPlayer Package is not for windows platform yet, you should try this package instead [audioplayers_windows](https://pub.dev/packages/audioplayers_platform_interface)
![image](https://user-images.githubusercontent.com/89972827/170885084-f36027c6-5589-4e8f-bcd4-065117dff585.png)

**Comment by shady-ti** [comment]
I'm using the pre-release version

<img width="605" alt="image" src="https://user-images.githubusercontent.com/91265151/170885295-81dbcedd-6859-41df-9abd-0555dc40b416.png">

**Comment by faizanMayo786** [comment]
ok, can you share your repository?

**Comment by shady-ti** [comment]
THis is the entirety of my code. I'm just messing around right now.

```dart
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';

void main() async {
  final player = AudioPlayer();
  await player.setSource(AssetSource('assets/river.mp3'));
  await player.resume();
}

class Main extends StatelessWidget {
  const Main({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(),
    );
  }
}
```

**Comment by faizanMayo786** [comment]
Ok I will check

**Comment by faizanMayo786** [comment]
Try this
```
void main() async {
  final player = AudioPlayer();

  await player.play(UrlSource('river.mp3'));

  // runApp(const MaterialApp(
  //   home: const BallPage(),
  // ));
}

```

**Comment by faizanMayo786** [comment]
let me know if it worked

**Comment by faizanMayo786** [comment]
You can visit my repository form complete code: [here](https://github.com/faizanMayo786/Labs_Assignments/blob/main/lab_5/lib/main.dart)

**Comment by shady-ti** [comment]
It didn't

```
FlutterError (Binding has not yet been initialized.

The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized. Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.

In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding. If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.)
```

**Comment by shady-ti** [comment]
> You can visit my repository form complete code: [here](https://github.com/faizanMayo786/Labs_Assignments/blob/main/lab_5/lib/main.dart)

Link doesn't work.

**Comment by faizanMayo786** [comment]
https://github.com/faizanMayo786/Labs_Assignments/blob/main/lab_5/lib/main.dart

> > You can visit my repository form complete code: [here](https://github.com/faizanMayo786/Labs_Assignments/blob/main/lab_5/lib/main.dart)
> 
> Link doesn't work.

**Comment by shady-ti** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/91265151/170886735-277d2894-57fd-4c09-9e17-8e4d2e7a2e99.png">

**Comment by faizanMayo786** [comment]
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized()
  final player = AudioPlayer();

  await player.play(UrlSource('river.mp3'));

  // runApp(const MaterialApp(
  //   home: const BallPage(),
  // ));
}

```

**Comment by faizanMayo786** [comment]
Sorry it was Private, Try now.

> <img alt="image" width="946" src="https://user-images.githubusercontent.com/91265151/170886735-277d2894-57fd-4c09-9e17-8e4d2e7a2e99.png">

**Comment by faizanMayo786** [comment]
https://github.com/faizanMayo786/Labs_Assignments/blob/main/lab_5/lib/question1.dart
also check this one

**Comment by shady-ti** [comment]
It works, thank you.

I had to make one more edit, int the pub-managed src code, `AudioCache` doesn't have a constructor, the constructor is named `cAudioCache` instead. I'm not sure why.

**Comment by faizanMayo786** [comment]
Great
