### ISSUE TITLE
Saved audio is not playing in IOS

### ISSUE THREAD

**Issue by shaheer47** [bluefireteam/audioplayers#1148]
I am recording audio and on next screen playing recorded audio. It works find on android but on IOS it didn't play I am getting the following in logs:

"iOS => call startHeadlessService, playerId cd52f66d-922e-4d38-986d-bb3e242812e8"
"calling start headless service (\n "-6035574777829228503"\n)"
"iOS => call play, playerId cd52f66d-922e-4d38-986d-bb3e242812e8"

But audio didn't play. I am using the path in audio_players to play audio.

**Comment by Gustl22** [comment]
Plz use propper issue template (version, reproducable code, etc.)

**Comment by Gustl22** [comment]
Closing as stale.
