### ISSUE TITLE
Example not work: The argument type 'List<dynamic>' can't be assigned to the parameter type 'List<String>'.

### ISSUE THREAD

**Issue by hc2088** [bluefireteam/audioplayers#1149]
audioplayers-main/packages/audioplayers/example/lib/components/tgl.dart: 

The argument type 'List<dynamic>' can't be assigned to the parameter type 'List<String>'.
Missing type arguments for generic method 'map<T>'.
The getter 'name' isn't defined for the type 'T'.

**Comment by luanpotter** [comment]
I just tried it locally, it is definitely working with no errors whatsoever

**Comment by Gustl22** [comment]
Also works for me. Try upgrading flutter...
