### ISSUE TITLE
Will play with remote url be guaranteed to partially download content for large audio files?

### ISSUE THREAD

**Issue by fzyzcjy** [bluefireteam/audioplayers#1153]
Hi thanks for the wonderful library! I want to play with remote audio URL. However, those audios are long and large, so it is very slow and not wise to download the whole file before start playing. Instead, the audio player should partially download files (e.g. download 30 seconds that are going to play, etc) and immediately start playing. 

I wonder whether such behavior is supported on Android and iOS?

P.S. I am using version 0.19.1. But if this requires a later version I will upgrade.

**Comment by fzyzcjy** [comment]
@luanpotter I am willing to contribute if it does have problem

**Comment by Gustl22** [comment]
This depends on the native players themselves:
I think Android [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.OnBufferingUpdateListener) and ios [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer) do this already.

**Comment by fzyzcjy** [comment]
Thank you!
