### ISSUE TITLE
earpieceOrSpeakerToggle possible bug? or eventual feature request maybe

### ISSUE THREAD

**Issue by Technorocker** [bluefireteam/audioplayers#1159]
Whenever I'm playing back some audio is starts in speaker mode, I setup a button to toggle but when i do it starts the audio file over from the start.

There no code to reproduce, Just dont know if this is the way its supposed to function or not.

but heres my little function I made for an IconButton's onPressed. Nothing fancy
```
  Future<void> toggleSpeaker() async {
    await audioPlayer.earpieceOrSpeakersToggle();
  }
```

IMHO the default should be earpiece and not speaker.

**Comment by luanpotter** [comment]
This was improved on v1.0.0 with `AudioContext`.
