### ISSUE TITLE
[macOS] Called not implemented method: setPlayerMode

### ISSUE THREAD

**Issue by Ephenodrom** [bluefireteam/audioplayers#1161]
Hello,

It seems that the implementation of the method got lost with the current version 1.0.0. It worked fine with 0.20.1. 

Due to the fact that the same implementation is used on iOS, i think the same problem exists there too.

Regards

**Comment by luanpotter** [comment]
Good catch. Player mode is irrelevant on iOS, but we should have a no-op handler to avoid errors.

https://github.com/bluefireteam/audioplayers/pull/1162

**Comment by Ephenodrom** [comment]
Hello,

Any chance for a release with this fix this or next week ?

Regards

**Comment by Ephenodrom** [comment]
Can confirm that this is fixed with version 1.0.1.
