### ISSUE TITLE
correcting name of existing getter error

### ISSUE THREAD

**Issue by boomx00** [bluefireteam/audioplayers#1163]
just tried to use the latest audioplayer 1.0.0 , get dependencies was fine but when i tried to run my app this message appeared, is this a bug?

`/D:/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart:242:28: Error: The getter 'name' isn't defined for the class 'AVAudioSessionCategory'.
 - 'AVAudioSessionCategory' is from 'package:audioplayers_platform_interface/api/audio_context_config.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
      'category': category.name,
                           ^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart:243:39: Error: The getter 'name' isn't defined for the class 'AVAudioSessionOptions'.
 - 'AVAudioSessionOptions' is from 'package:audioplayers_platform_interface/api/audio_context_config.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
      'options': options.map((e) => e.name).toList(),`

**Comment by A-little-white-cloud** [comment]
same question

**Comment by Gustl22** [comment]
Did you try `flutter clean`? Does the [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example) work for you? Do you have an example project?

**Comment by ruoyifan** [comment]
> Did you try `flutter clean`? Does the [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example) work for you? Do you have an example project? Also use the issue template!

I tried but still fail.

**Comment by ruoyifan** [comment]
I thought it was because AVAudioSessionCategory is an enum.   The enum doesn't have name getter util a certain version?

**Comment by Gustl22** [comment]
Again, does the [example work](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example)? We certainly don't have the time to debug someone elses code. 
If the example works, try to find the differences and update your code accordingly.

**Comment by liang-notes** [comment]
I met the same issue, Is there anyone solved it?

**Comment by jobypthomas** [comment]
I have the same issue. Any solution? @liang-notes?

**Comment by Gustl22** [comment]
@ruoyifan I think you're right. Dart [doesn't support](https://api.flutter.dev/flutter/dart-core/EnumName.html#instance-properties) `name` extension until version `2.15`

Ref: [AVAudioSessionCategory](https://github.com/bluefireteam/audioplayers/blob/6fad1cc4443e623e5c94519f130b4004b2dc3857/packages/audioplayers_platform_interface/lib/api/audio_context_config.dart#L459). So you need at least **Flutter 2.8.0**
