### ISSUE TITLE
first time is (await SoundMode.ringerModeStatus == RingerModeStatus.unknown).

### ISSUE THREAD

**Issue by ttb-inc** [bluefireteam/audioplayers#1177]
Hello.

When [await SoundMode.ringerModeStatus] is executed for the first time, an [RingerModeStatus.unknown] value is returned.
After that you get different values (normal, silent, vibrate).
So, when the app starts, I call once [await SoundMode.ringerModeStatus].

is this right?
Is there any other way?

Thank you.

**Comment by Gustl22** [comment]
Use the issue template! Also there is no such Mode `SoundMode.ringerModeStatus`
