### ISSUE TITLE
Is there a way to automatically stop playing the previous file and play the current selected 

### ISSUE THREAD

**Issue by Leonard-al** [bluefireteam/audioplayers#1181]
I have a lot of files from Urls in my List View i want to play them independently for instance if one is already playing and I click on the other one to play, the one which was playing should automatically stop and play the current selected.
how do i achieve this?

Thanks..

**Comment by Gustl22** [comment]
Just call stop on the current AudioPlayer and then call play. Also it should stop itself, if you load in a new url.
