### ISSUE TITLE
How does "audioplayers_web 1.0.0" work?

### ISSUE THREAD

**Issue by potter31** [bluefireteam/audioplayers#1188]
I was trying to use "audio players_web" instead of "audio players" as I need to add sounds to my PWA, but it appeared to be a total disaster for me and your help is my last chance to figure it out:)

First problem is that there isn't documentation for "audioplayers_web" as it was for "audioplayers". 
So... How can I play file? There isn't a function "play"))

I managed somehow to play file using this code:

```
  Future<void> doWork() async {
    player.getOrCreatePlayer("web");
    player.setSourceUrl("web", '/assets/sounds/1.mp3');
    player.players['web']!.start(0.0);
  }
```

And it even works when I run an app from VS Code, but if I compile it and upload to a server it doesn't:(

Could you write a short guide for dummies? Thank you:)

**Comment by Gustl22** [comment]
Why not just using `audioplayers`? What do you gain by using the native package? Note that some abstraction is also done in the main package, such as handling `AudioCache` or `_sanitizeURLForWeb`

**Comment by potter31** [comment]
As I could understand it doesn't work for web
```
Audio Cache
In order to play Local Assets, you must use the Audio Cache class. Audio Cache is not available for Flutter Web.
```
And I can't find any example of "How to play file from "assets" in web app":(

It works only before I build and upload it on the real server

**Comment by potter31** [comment]
[Gustl22](https://github.com/Gustl22), Thank you for the idea with `_sanitizeURLForWeb`

When I tried to use `player.play(DeviceFileSource('/assets/sounds/1.mp3'));` . It worked only for my local machine, but when I added additional '/assets/' it started working and for the web version too.

`player.play(DeviceFileSource('/assets/assets/sounds/1.mp3'));`

**Comment by Gustl22** [comment]
It just works in `audioplayers`, AudioCache is not used in the same way for web as for the other platforms. Local assets are stored on the server for the web implementation, as you have to download them anyway.
I recommed just using the `audioplayers` package (without `_web` suffix), which handles such cases. No need to make it harder than it is 😉
