### ISSUE TITLE
Unable to build in iOS : ld: framework not found audioplayers

### ISSUE THREAD

**Issue by melchorlapinigjr** [bluefireteam/audioplayers#1195]
Please help. Been solving this long enough. Thanks!

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

`
Showing All Errors Only
Ld /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
    cd /Users/melchorlapinig/Documents/Projects/my-book-habit1/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -L/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/lib/swift -L/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Flutter -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/AppAuth -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/FMDB -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/GTMAppAuth -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/GTMSessionFetcher -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/GoogleSignIn -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/appsflyer_sdk -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/audioplayers_darwin -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_keyboard_visibility -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_local_notifications -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_login_facebook -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_native_timezone -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_pdfview -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_sound -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/flutter_sound_core -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/google_sign_in_ios -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/in_app_purchase_storekit -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/launch_review -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/path_provider_ios -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/permission_handler_apple -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/shared_preferences_ios -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/sign_in_with_apple -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/sqflite -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/url_launcher_ios -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Pods/AppsFlyerFramework -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Pods/FBAEMKit/XCFrameworks -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Pods/FBSDKCoreKit/XCFrameworks -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Pods/FBSDKCoreKit_Basics/XCFrameworks -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Pods/FBSDKLoginKit/XCFrameworks -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppsFlyerFramework/Main -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBAEMKit -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBSDKCoreKit -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBSDKCoreKit_Basics -F/Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBSDKLoginKit -F/Users/melchorlapinig/Documents/Projects/my-book-habit1/ios/Flutter -filelist /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.swiftmodule -ObjC -lsqlite3 -lz -framework AVFoundation -framework AppAuth -framework AppsFlyerLib -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework FBAEMKit -framework FBSDKCoreKit -framework FBSDKCoreKit_Basics -framework FBSDKLoginKit -framework FMDB -framework Foundation -framework GTMAppAuth -framework GTMSessionFetcher -framework GoogleSignIn -framework LocalAuthentication -framework MediaPlayer -framework SafariServices -framework Security -framework SystemConfiguration -framework UIKit -framework appsflyer_sdk -framework audioplayers_darwin -framework flutter_keyboard_visibility -framework flutter_local_notifications -framework flutter_login_facebook -framework flutter_native_timezone -framework flutter_pdfview -framework flutter_sound -framework flutter_sound_core -framework google_sign_in_ios -framework in_app_purchase_storekit -framework launch_review -framework path_provider_ios -framework permission_handler_apple -framework shared_preferences_ios -framework sign_in_with_apple -framework sqflite -framework url_launcher_ios -weak_framework AuthenticationServices -ObjC -lsqlite3 -framework AVFoundation -framework AppsFlyerLib -framework CoreTelephony -framework FMDB -framework MediaPlayer -framework Security -framework SystemConfiguration -framework appsflyer_sdk -framework audioplayers -framework flutter_keyboard_visibility -framework flutter_local_notifications -framework flutter_native_timezone -framework flutter_pdfview -framework flutter_sound -framework flutter_sound_core -framework in_app_purchase_storekit -framework launch_review -framework path_provider_ios -framework permission_handler_apple -framework shared_preferences_ios -framework sqflite -framework url_launcher_ios -lc++ -framework Pods_Runner -framework StoreKit -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/melchorlapinig/Library/Developer/Xcode/DerivedData/Runner-eolfrzofymjkeedwymtgxiozfkvr/Build/Products/Debug-iphoneos/Runner.app/Runner

ld: framework not found audioplayers
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by melchorlapinigjr** [comment]
Fix by deleting audioplayers framework in Runner>Build Settings>Other linker flags

**Comment by ChristineWasike** [comment]
This suggestion does not work in my case (See error message below):

```
Parse Issue (Xcode): Module 'audioplayers_darwin' not found
```

Might you have any alternative suggestions?
