### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by LorenzSchueler** [bluefireteam/audioplayers#1197]
I'm not able to build the example app for linux because I get the following error:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:5 (include):
  include could not find load file:

    FetchContent
```

**Full Description**
I've read the troubleshooting guide and also installed the additional linux dependencies. However I'm not able to build the example because of the error above. 

**Code to Reproduce**
the example

**Log Errors**
```bash
flutter build linux
```
produces
```
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:5 (include):
  include could not find load file:

    FetchContent
```

**Platforms**
build for linux fails, build for android works

OS: linux
OS version: Debian sid
flutter version: 3.0.3
audioplayers version: 1.0.1
cmake: 3.23.2
release or not release: in debug and release mode

I'm not sure if this related to audioplayers or cmake itself. However I would appreciate any ideas what could cause this anyways :)

**Comment by berbagimadani** [comment]
Same error: CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:5 (include):
 include could not find load file:  FetchContent
note: buntu 21.10 5.13.0-52-generic

**Comment by Gustl22** [comment]
I recommend installing [Flutter manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually) instead of using [snap](https://github.com/canonical/flutter-snap/pull/61) which lacks of proper cmake support. Does this help?

**Comment by berbagimadani** [comment]
> I recommend installing [Flutter manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually) instead of using [snap](https://github.com/canonical/flutter-snap/pull/61) which lacks of proper cmake support. Does this help?

I've tried it. but i found another issue for Platforms android-31

V/MediaPlayer(18220): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18220): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(18220): error (1, -2147483648)
E/MediaPlayer(18220): Error (1,-2147483648)
V/MediaPlayer(18220): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18220): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(18220): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18220): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/flutter (18220): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_SYSTEM

**Comment by LorenzSchueler** [comment]
that solved it for me
thanks :)

**Comment by spydon** [comment]
I think that you should also be able to get it working by install it from snap too now if you manually set the channel:
`snap refresh --channel=edge/core20 flutter`
Since that is using this PR https://github.com/canonical/flutter-snap/pull/61
