### ISSUE TITLE
No implementation found for method setSourceBytes

### ISSUE THREAD

**Issue by Gnoucorp** [bluefireteam/audioplayers#1198]
I'm trying to find a workaround to #1158 since I need a JWT token to access the audio files on my server but using setSourceBytes with the response body does not work.

My code:
```
 http.get(Uri.parse(streamUrl), headers: getBaseHeaders()).then((response) {
        if (response.statusCode == 200) {
          Uint8List bytes = response.bodyBytes;
          player.setSourceBytes(bytes).then((value) => player.resume());
        }
      });
```

When I try, I have the following exception : `[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method setSourceBytes on channel xyz.luan/audioplayers)`

Cleaning/rebuilding the app did not change anything. I would appreciate any ideas to make it work

OS: windows 10 64bits
Device: windows emulator
flutter version: 3.0.3
audioplayers version: 1.0.1

Thanks

**Comment by luanpotter** [comment]
`setSourceBytes` is not currently supported on windows. this is already documented on the [feature parity table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md).

contributions are most welcome though :)
