### ISSUE TITLE
 audio players version: 1.0.1 build error 'category': category.name,

### ISSUE THREAD

**Issue by ruoyifan** [bluefireteam/audioplayers#1199]
**Full Description**

build failed

**Log Errors**
```
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.

      'category': category.name,
                           ^^^^
/srv/flutter/current/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart:243:39: Error: The getter 'name' isn't defined for the class 'AVAudioSessionOptions'.
- 'AVAudioSessionOptions' is from 'package:audioplayers_platform_interface/api/audio_context_config.dart' ('/srv/flutter/current/.pub-cache/hosted/pub.dartlang.org/audioplayers_platform_interface-1.0.0/lib/api/audio_context_config.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
      'options': options.map((e) => e.name).toList(),
                                      ^^^^
FAILURE: Build failed with an exception.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/66984785/176819514-b88c1394-23f0-4430-9bff-5fe918fbb4c3.png)

**Platforms**
Linux vscode

* OS: android
* OS version: 29
* Device:  debug with a physical device
* audio players version: 1.0.1

**Comment by Gustl22** [comment]
Plz use existing issue #1163.
Also try upgrading minimum flutter/dart version.
I recommend installing [Flutter manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually) instead of using [snap](https://github.com/canonical/flutter-snap/pull/61) which lacks of proper cmake support.

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/bluefireteam/audioplayers/issues/1163
