### ISSUE TITLE
Audio does not play: `AudioPlayers: Could not query current duration.`

### ISSUE THREAD

**Issue by matheusfillipe** [bluefireteam/audioplayers#1213]
I am testing on both android 10.0 and on linux and couldn't get to hear any audio from this library, tried both asset and url sources, multiple ways, but always same problem.

**Full Description**

I am not sure if it is because I am on the latest stable flutter and this might be a new issue. I am also on the latest pub.dev `audioplayers`. When I try to play a UrlSource on linux it will crash and on android it will simply not play. If i try an AssetSource then it wont crash but still wont play in any of these platforms.

**Local asset test**

**Code to Reproduce**

```dart
  @override
  void initState() {
    super.initState();
    openAudio();
    }

  Future openAudio() async {
    await AudioPlayer.global.changeLogLevel(LogLevel.info);
    var player = AudioPlayer();
    await player.play(AssetSource("test.mp3"));
    await player.dispose();
  }
```

**Log Errors**

With local asset on both linux and android:

```
AudioPlayers: Could not query current position.
AudioPlayers: Could not query current position.
AudioPlayers: Could not set playback to position 0 and rate 1.000000.
AudioPlayers: Could not query current duration.
```

Repo and where this code is: https://github.com/matheusfillipe/gasconchat/blob/6e4149eb97e20ef2a82929e8a1979d3e80c7dc67/lib/screens/homePage.dart#L32

My end goal is to use this lib to provide preview for url audio files there.

**Local asset test**

If I use a url (Url: https://ttm.sh/w7_.mp3) on linux it will crash flutter completely and close the app on linux only. For android it still doesn't play.

```dart
  @override
  void initState() {
    super.initState();
    openAudio();
    }

  Future openAudio() async {
    await AudioPlayer.global.changeLogLevel(LogLevel.info);
    var player = AudioPlayer();
    await player.play(UrlSource("https://ttm.sh/w7_.mp3"));
    await player.dispose();
  }
```

Linux crash output:

```
AudioPlayers: Could not query current position.
Bail out! GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
**
GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Lost connection to device.
```

**Files/URLs/Sources**

Url: https://ttm.sh/w7_.mp3

I downloaded this file as well and also tried with other `.mp3`.

**Platforms**

OS: Archlinux, android 10.0
audioplayers: ^1.0.1

```
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (10 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```

**Comment by Gustl22** [comment]
I tried and the problem seems to be that the audio cannot be played as long no context is available:

Try:
```
WidgetsBinding.instance
        .addPostFrameCallback((_) async {
      await player.play(UrlSource("https://ttm.sh/w7_.mp3"));
    });
```
Also calling `player.dispose` immediately after playing cannot work (this would block the UI and also long async waiting periods are done via the callbacks, e.g. `onPlayerStateChanged` ). `player.play` does not wait for the audio sample to be finished playing, it only waits for the source to be loaded.

The `GLib-GIO:ERROR` should not occur. But I could not reproduce it.

**Comment by matheusfillipe** [comment]
Thanks! Indeed all I was lacking was calling this from within a context.

**Comment by Juihibi** [comment]
Please do you solve this issue by just replacing:

  await player.play(AssetSource("test.mp3"));
  
  by :
  
  WidgetsBinding.instance
        .addPostFrameCallback((_) async {
      await player.play(UrlSource("https://ttm.sh/w7_.mp3"));
    });
    
    ??
    
    Please help me , I have the same issue.  the audio file is not playing
