### ISSUE TITLE
Can not get duration before audio play

### ISSUE THREAD

**Issue by VCasecnikovs** [bluefireteam/audioplayers#1215]
After setting the source I am trying to get the duration of the audio file. Unfortunately, the answer is zero.

The code:
```
    await player.setSource(event.source);
    var duration = await player.getDuration();
```

**Platforms**
OS: Windows & Android

**Comment by Gustl22** [comment]
This cannot be guaranteed in all cases. The problem is e.g. for mp3 the duration is estimated which only will precisely work if playing the audio. But I didn't experience that on Android/Windows yet...

**Comment by tffajari** [comment]
I have the same issue here, just_audio offer get duration before we play audio, but there is already to much code I implement using audio_player

**Comment by Gustl22** [comment]
Closing in favor of #1033
