### ISSUE TITLE
iOS: By default, the player is played by earpiece. How can I switch to loudspeaker?

### ISSUE THREAD

**Issue by Rogue24** [bluefireteam/audioplayers#1219]
By default, the player is played by earpiece. How can I switch to loudspeaker?

**Comment by GoodAndBeautiful** [comment]
I think this is a duplicate of: https://github.com/bluefireteam/audioplayers/issues/1194

**Comment by Rogue24** [comment]
@GoodAndBeautiful thank you so much.
