### ISSUE TITLE
Can't play audio from http URL in audioplayers flutter package

### ISSUE THREAD

**Issue by TahaAhvazi** [bluefireteam/audioplayers#1220]
Hello 👋
when I try to play audio from the internet I face this error in debug console 
any solution?

V/MediaPlayer( 2137): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 2137): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 2137): MediaHTTPService(android.media.MediaHTTPService@7a89a6): Cookies: null
V/MediaHTTPService( 2137): makeHTTPConnection: CookieManager created: java.net.CookieManager@6815fe7
V/MediaHTTPService( 2137): makeHTTPConnection(android.media.MediaHTTPService@7a89a6): cookieHandler: java.net.CookieManager@6815fe7 Cookies: null

**Comment by Gustl22** [comment]
Plz use issue template :)
