### ISSUE TITLE
Can't clear cache over local file

### ISSUE THREAD

**Issue by guivr** [bluefireteam/audioplayers#1225]
## Checklist
- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

I'm building a voice changer app, therefore, I'm generating different effects for an audio and saving under the same file name. `audioplayers` will play it right on the first time, but when I click on my app's buttons to generate the audio with another voice tone, even if the file is updated on `getApplicationDocumentsDirectory`, `audioplayers` will play the same first audio again, it won't update.

All the files are local and saved in the application documents directory under the name `audio-modified.wav`.

I've tried doing ```
await audioPlayer.stop();
await audioPlayer.release();```
and then ```
await audioPlayer.play('${docsDir.path}/audio-modified.wav',
            isLocal: true);```
            again but it doesn't work.

When I share the audio file using `share_plus`, it share the updated audio.

How can I clear the cache of this local file so that the player plays the most updated version?

## Current bug behaviour
Even though I call `.stop`, `.resume`, and `.play`, local file played is not the most updated one.

## Expected behaviour
A way to clear the audio cache and play the new audio under the same file name.

**Comment by guivr** [comment]
Any help? Please :( Been stuck on this issue

**Comment by Gustl22** [comment]
Which platform? Try to load another source in between or hand over null. But it's likely that this doesn't work, too, because the file is copied into the cache directory and not updated if already there. The best way is to rename the file and set it as source.

**Comment by guivr** [comment]
Thanks for the help, @Gustl22 . Can I achieve something like a "clear cache" using AudioCache from this library? Or is it something different?

**Comment by guivr** [comment]
PS: AudioCache worked! :D

**Comment by Gustl22** [comment]
Yes, `player.audioCache.clear('/my/url/or/path');` should be enough. Can I close this?

**Comment by guivr** [comment]
Yes, thanks :)
