### ISSUE TITLE
Some problems about set position on play and play effect sound on Web in iOS

### ISSUE THREAD

**Issue by Syooian** [bluefireteam/audioplayers#1228]
First question about set position on play.
This's what I do.

```
OutlinedButton(
  onPressed:(){
     myPlayer.play(AssetSource('Music.mp3'),position:Duration(minutes: 1));
  },
),
```

On Web everytime I click the button It's will play from start, you need to call "stop()" once and it will play from specified position, but if you play other music file the issue will begin.
But on iOS and Android devices it will happen only at first time, no need to call stop().

Second question is about Flutter Web
For some reason I need to run Flutter Web on iOS browser, need to play a button effect sound when click the button, first time click it's work good, but after that it's sound like been cut half, if change other sound file the issue come again. Same whatever using Chrome or Safari. (Latest version), but seens work good for a long music file.
And this issue only happen on Flutter Web on iOS, another platform are work fine.

My iPad : iPad Air 4 (macOS 15.6)

```
AudioPlayer soundPlayer = AudioPlayer();

@override
void initState() {
  super.initState();
  soundPlayer.setReleaseMode(ReleaseMode.stop);
}

soundPlayer.play(AssetSource('Button.mp3'));
```

```
Flutter : 3.0.4
Dart : 2.17.5
AudioPlayer : 1.0.1
```

Want to know did I just miss something to do for these 2 question? thank you very much.

**Comment by Gustl22** [comment]
Can you check again with `audioplayers: ^1.1.0` ? Also please don't mix two issues in one. Then create two separate issues, with its own issue template. Thx :)
