### ISSUE TITLE
Future<Duration> AudioPlayer.getDuration() is working but AudioPlayer.onDurationChanged Stream<Duration> isn't

### ISSUE THREAD

**Issue by busslina** [bluefireteam/audioplayers#1233]
Platform: Flutter Desktop on Windows

Description: While playing an audio the stream listen() method never gets any update. I'm subscribing before playing the sound (maybe changing it will solve the issue)

UPDATE: Subscribing to the stream after playing the audio doesn't solve the issue

**Comment by Gustl22** [comment]
Plz use issue template
