### ISSUE TITLE
[QUESTION]: What does this mean: "AudioCache is dead, long live Sources"

### ISSUE THREAD

**Issue by under3415** [bluefireteam/audioplayers#1234]
Prior to version 1 we had an option to pre-loading files (from different sources) into an "AudioCache".

This made a lot of sense. My app has 5 audio sound effects that play often. So it makes sense to pre-load them into a cache (from assets in my case) and play them from there instead of reading from storage every time. This is even more important if the sound is loaded from a remote network location.

When you say "AudioCache is dead", does that mean that the file is read form source every time? Or are you doing some caching in the background without developer having to manage it?

**Comment by rpungin** [comment]
I have the same question.

**Comment by Gustl22** [comment]
Cache further exists, but is handled by the plugin.

**Comment by Gustl22** [comment]
Also `AudioCache` is only used for AssetSource. @luanpotter maybe we should explain this [here ](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#audiocache)in more detail, that this isn't needed for the AssetSource anymore.

For the network, we don't provide a mechanism (yet), to cache them, and audioplayers never did. This should be handled here: #374

**Comment by Gustl22** [comment]
Closing in favor of #1256
