### ISSUE TITLE
Play wav asset on web: Error: UnimplementedError

### ISSUE THREAD

**Issue by arnirichard** [bluefireteam/audioplayers#1244]
## Current bug behaviour
Not able to play wav file from assets on web (resulting in UnimplementedError)

## Expected behaviour
Should play wav as it does on Android

## Steps to reproduce
1. Create audio player: `AudioPlayer player = AudioPlayer();`
2.Playing wav file using the following code:

`String audioasset = 'assets/sounds/' + filename+ '.wav';
        ByteData bytes = await rootBundle.load(audioasset);
        player.play(BytesSource(bytes.buffer.asUint8List(0, bytes.lengthInBytes)));`

3. This works on Android, but on web (debugging on Edge, Chrome) there is error:

Error: UnimplementedError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/audioplayers_web/audioplayers_web.dart 101:5                                                                      setSourceBytes
packages/audioplayers/src/audioplayer.dart 221:22                                                                          setSourceBytes
packages/audioplayers/src/source.dart 58:18                                                                                setOnPlayer
packages/audioplayers/src/audioplayer.dart 191:18                                                                          setSource
packages/audioplayers/src/audioplayer.dart 111:11                                                                          play
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/audioplayers/src/audioplayer.dart 92:20                                                                           play
packages/learn_words/utils/play.dart 23:14                                                                                 _play
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

## Alternative code
Using the following code:

`player.play(AssetSource(/sounds/' +filename + '.wav'));`

seems to work only on web if filename has English-only characters
If the file name is i.e. กิน.wav then the above code does not work, resulting in error:

Error: NotSupportedError: Failed to load because no supported source was found.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1378:11                                          callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

## Audio Files/URLs/Sources
https://www.easythai.net/assets/assets/sounds/gin.wav
(renamed to กิน.wav)

## Environment information

* audioplayers: ^1.0.1

Platform 1: web, Windows 11 Pro, Chrome 104.0.5112.81
Platform 2: Android 12, Galaxy S10,

## Flutter doctor
[√] Flutter (Channel master, 3.1.0-0.0.pre.2268, on Microsoft Windows [Version 10.0.22000.856], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by Gustl22** [comment]
Byte Arrays are only supported on Android. See [parity table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#main-features)
If you find a way to implement this for web, feel free to open a Merge Request.
