### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by adrianvintu** [bluefireteam/audioplayers#1251]
Hello, my app crashes on iOS with the following stack. Is the crash caused by audioplayers?

```
Crashed: com.apple.main-thread
0  ???                            0x1bc1b6990 (Missing)
1  audioplayers_darwin            0xa6f4 $s19audioplayers_darwin29SwiftAudioplayersDarwinPluginC8register4withySo07FlutterF9Registrar_p_tFZ + 60
2  audioplayers_darwin            0xa6f4 $s19audioplayers_darwin29SwiftAudioplayersDarwinPluginC8register4withySo07FlutterF9Registrar_p_tFZ + 60
3  audioplayers_darwin            0xa980 $s19audioplayers_darwin29SwiftAudioplayersDarwinPluginC8register4withySo07FlutterF9Registrar_p_tFZTo + 56
4  audioplayers_darwin            0x4170 +[AudioplayersDarwinPlugin registerWithRegistrar:] + 76
5  Runner                         0x5140 +[GeneratedPluginRegistrant registerWithRegistry:] + 206 (GeneratedPluginRegistrant.m:206)
6  Runner                         0x5a88 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 15 (AppDelegate.swift:15)
7  Runner                         0x5d58 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 196 (<compiler-generated>:196)
8  ???                            0x1b9ab5f88 (Missing)
9  ???                            0x1b9c9cda4 (Missing)
...
41 ???                            0x1b9ca4e88 (Missing)
42 ???                            0x1b9a265ec (Missing)
43 Runner                         0x6194 main + 7 (AppDelegate.swift:7)
44 ???                            0x1008cdce4 (Missing)
```
![2022-08-24 08_42_31-Stop Anxietate - GeneratedPluginRegistrant m line 206 - Firebase console — Mozil](https://user-images.githubusercontent.com/33379688/186339768-9ebf211a-0318-46ec-b25e-a36d0bb68ee4.png)

Cannot send code debug, unfortunately.

**Comment by Gustl22** [comment]
Can you provide a reproducable example? Plz use issue template!

**Comment by adrianvintu** [comment]
Can't do, sorry. It happened for only a few users. You may close this ticket.

Thank you for your amazing work!

**Comment by Gustl22** [comment]
Ok sorry for that, unfortunately we can only fix reproducible bugs. Feel free to open again, if you gain more information.

**Comment by ZXCheng** [comment]
audioplayers:4.1.0,

**Comment by ZXCheng** [comment]
audioplayers:4.1.0,
build ipa release for AdHoc,
![截屏2023-06-02 16 50 16](https://github.com/bluefireteam/audioplayers/assets/17699101/0ea2a166-6411-4bc7-912a-b02e4165fd9a)

**Comment by Gustl22** [comment]
@ZXCheng do you have a reproducible example?

**Comment by Gustl22** [comment]
Without a reproducible example, it's hard to debug. Feel free to open again, if it's reoccuring :)

**Comment by T-P-F** [comment]
I had this problem and this was the solution: ensure that you're running a release build on the device.

`flutter run --release -d <iOS device id>`
