### ISSUE TITLE
Having issue when handling error

### ISSUE THREAD

**Issue by mahmudbabakusa** [bluefireteam/audioplayers#1252]
Hello, Good morning. Please am having error when playing a radio stream that is not working . I having problem handling the error.  If I try the method you use that using the if statement to compare it to 1 it is saying it is an integer. it is a future void function.

**Comment by spydon** [comment]
Closing this as stale, I think that this is the same as #1271.
Are you following a tutorial or something, since two people now have made that same mistake?
