### ISSUE TITLE
Android: AudioPlayer.Play not working

### ISSUE THREAD

**Issue by MohammedGoder** [bluefireteam/audioplayers#1258]
Nothing seems to happen when I invoke AudioPlayer.Play

It behaves as intended on Windows but not Android

Problematic Implementation:
```
audioPlayer.play(
    DeviceFileSource(widget.filePath),
    mode: PlayerMode.mediaPlayer,
);
```

Hacky Solution:
```
if (Platform.isAndroid) {
  audioPlayer.setSource(DeviceFileSource(widget.filePath)).then((_) {
    if (disposing) return Future.value();
    return audioPlayer.setPlayerMode(PlayerMode.mediaPlayer).then((_) {
      if (disposing) return Future.value();
      return audioPlayer.setPlaybackRate(1).then((_) {
        if (disposing) return Future.value();
        return audioPlayer.resume();
      });
    });
  });
} else {
  audioPlayer.play(
    DeviceFileSource(widget.filePath),
    mode: PlayerMode.mediaPlayer,
  );
}
```

**Comment by Gustl22** [comment]
I tested by [replacing](https://github.com/Gustl22/audioplayers/blob/9865ae4e138bd43bc5f4287b1d944f09f9d830b4/packages/audioplayers/example/lib/tabs/sources.dart#L32) `setSource` with `play` in [my example](https://github.com/Gustl22/audioplayers/tree/feat/extended-tests) (where I have added a FilePicker) and didn't experience such behavior. 

Can you retest with the example. Please use issue template to better isolate your problem.

**Comment by MohammedGoder** [comment]
It's replicable through the Android Emulator API version 32.

**Comment by Gustl22** [comment]
Still working with API 32. Did you try [my example](https://github.com/Gustl22/audioplayers/tree/feat/extended-tests/packages/audioplayers/example). You can also clone it and replicate your problem there. Plz use proper **issue template** to better determine the source of the problem.
