### ISSUE TITLE
Byte array audio source (BytesSource, setSourceBytes) on iOS, MacOS, Linux and Web.

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [bluefireteam/audioplayers#1269]
## Checklist
- [Yes] I made sure that the feature I am proposing doesn't already exist
According to the [Feature Parity Table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#main-features) it doesn't.

## Use case / Problem
Which problem would be solved with this feature? 
In general, it would enable us to play audio that's already in memory, which would also enable the use of sound fonts through [dart_melty_soundfont](https://pub.dev/packages/dart_melty_soundfont)
Why it fits in this package (and not a standalone package for example) 
Audio sources seem to fit best in this package, but a standalone package would be fine as well.

## Proposal / Solution
What do you propose as a solution? Add as much information as you can! 
Adding byte arrays as audio source to the yet missing platforms.

What API changes that are necessary?
Given the fact that it's already supported on Android, the changes in API will most likely be minimal.

Are there any breaking changes expected? 
     Is it a new flag to pass through to android/ios?
     Is it just manageable with some built in functions?
Not that I can think of.

## Platforms
Make sure to identify for which platforms this must be implemented
According to the [Feature Parity Table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#main-features) it's missing on iOS, MacOS, Windows, Linux and Web.

Affected Platforms: 
According to the [Feature Parity Table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#main-features) it's missing on iOS, MacOS, Windows, Linux and Web.

This feature would make sense on all platforms. 

Are you interested in working on a PR for this? 
Sorry, can't.

**Comment by YoussefLasheen** [comment]
Is there a technical difficulty to why this feature is not implemented in dart instead of platform specific code?

**Comment by Gustl22** [comment]
@YoussefLasheen probably not, haven't looked into it. Maybe one can try to implement this for web and see how it goes. This could be more easily applied to all platforms, I think. We just need more developers who contribute to open source :)

**Comment by ahmednfwela** [comment]
I recently came across this and found an easy solution, but I am not sure if it works for all platforms.
it's using `data:` url source
e.g.:
```dart
UrlSource urlSourceFromBytes(Uint8List bytes,{String mimeType= "audio/mpeg"}) {
  return  UrlSource(Uri.dataFromBytes(bytes, mimeType: mimeType).toString());
}
```
however I noticed that `mimeType` is a requirement here for it to work correctly, also I only tried this for `mp3` format.

**Comment by animator** [comment]
+1

**Comment by lcw99** [comment]
> I recently came across this and found an easy solution, but I am not sure if it works for all platforms. it's using `data:` url source e.g.:
> 
> ```dart
> UrlSource urlSourceFromBytes(Uint8List bytes,{String mimeType= "audio/mpeg"}) {
>   return  UrlSource(Uri.dataFromBytes(bytes, mimeType: mimeType).toString());
> }
> ```
> 
> however I noticed that `mimeType` is a requirement here for it to work correctly, also I only tried this for `mp3` format.

What platform did you tested? It's not working on iOS.

**Comment by ahmednfwela** [comment]
mainly web

**Comment by doubleLLL3** [comment]
Hi, why it threw an exception on iOS:

```
flutter: \^[[31mAudioPlayers Exception: AudioPlayerException(
	UrlSource(url: data:audio/mpeg;base64,UklGRiTUBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQDUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
```

I use this code:

> I recently came across this and found an easy solution, but I am not sure if it works for all platforms. it's using `data:` url source e.g.:↳
> 
> ```dart
> UrlSource urlSourceFromBytes(Uint8List bytes,{String mimeType= "audio/mpeg"}) {
>   return  UrlSource(Uri.dataFromBytes(bytes, mimeType: mimeType).toString());
> }
> ```
> 
> however I noticed that `mimeType` is a requirement here for it to work correctly, also I only tried this for `mp3` format.

**Comment by Grafritz** [comment]
> I recently came across this and found an easy solution, but I am not sure if it works for all platforms. it's using `data:` url source e.g.:
> 
> ```dart
> UrlSource urlSourceFromBytes(Uint8List bytes,{String mimeType= "audio/mpeg"}) {
>   return  UrlSource(Uri.dataFromBytes(bytes, mimeType: mimeType).toString());
> }
> ```
> 
> however I noticed that `mimeType` is a requirement here for it to work correctly, also I only tried this for `mp3` format.

Moi ca marche pour moi...
