### ISSUE TITLE
module audioplayers_darwin not found on IOS device

### ISSUE THREAD

**Issue by ThuyenPV** [bluefireteam/audioplayers#1270]
## Checklist
- [ ] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

## Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by Gustl22** [comment]
Plz fill the template. How are we supposed to help?

**Comment by spydon** [comment]
I'm closing this since not enough effort have been put into following the template, the checkboxes haven't even been checked.

**Comment by ThuyenPV** [comment]
I'm sorry, my bad pull request :3

**Comment by womandroid** [comment]
I have the same issue, but I found this occurs in the Release mode.
