### ISSUE TITLE
This expression has a type of 'void' so its value can't be used. Try checking to see if you're using the correct API; there might be a function or call that returns void you didn't expect. 

### ISSUE THREAD

**Issue by suhashollakc** [bluefireteam/audioplayers#1271]
Future<void> _play(int index) async {
    int result =  await _audioPlayer.play(_songsList[index].previewUrl,
        volume: _currentVolume);
    // Means AudioPlayer plugin has been successful in starting to play.
    if (result == 1) {
      setState(() {
        _showMusicControlsBar = true;
      });
     
    }
    

  }

How to fix this?

**Comment by Gustl22** [comment]
Plz use issue template to properly determine where the bug is located.

**Comment by spydon** [comment]
`AudioPlayer.play` returns a `Future<void>`, so after it has been awaited it is simply void, you can't assign void to a variable.
