### ISSUE TITLE
Log debug

### ISSUE THREAD

**Issue by letungcntt** [bluefireteam/audioplayers#1277]
`avcore\audiocore\client\audioclient\audioclientvolume.cpp(193)\AUDIOSES.DLL!00007FFABD82A8CE: (caller: 00007FFABD82A9CE) ReturnHr(1) tid(a4c) 80004003 Invalid pointer`

I find this log when use Visual Studio 2019 debug

![image](https://user-images.githubusercontent.com/46608407/190124372-0ecdca7a-079e-4c50-a650-3040506ac67f.png)
![image](https://user-images.githubusercontent.com/46608407/190124508-c70ffda4-410e-4971-8448-2a23ac42b417.png)

**Comment by Gustl22** [comment]
Plz use issue template, we cannot fix, if its not reproducible. Provide a step by step example...
