### ISSUE TITLE
Cross Fade between music tracks within a playlist

### ISSUE THREAD

**Issue by flmuse** [bluefireteam/audioplayers#1278]
## Checklist
- [x] I made sure that the feature I am proposing doesn't already exist

## Use case / Problem

Whilst listening to a playlist using this plugin, moving to the next music track in a playlist sounds really jarring.

This is due to the silence and dip in volume between music tracks because most music files fade-out to silence as they reach their end and fade-in from silence. As a result, there is no smooth transition between music tracks.

## Proposal / Solution

Crossfading between music tracks to make a mixed playlist sound much more seamless and natural-sounding transitions.

Would like to be able to set the duration of crossfades, such as 10 seconds.
In this case, a crossfade duration setting of 10 seconds would start to fade-out the current music track and fade in the next track in the playlist. This would result in a continuous mix and flow of music.

Crossfade function would be used when switching between music tracks such as when choosing the previous or next track, stop or start playing a music track.

I have working crossfade code in jquery syntax. If a developer knows both jquery and dart, they may utilize this to convert and implement the new functionailty into this plugin.

## Platforms

Affected Platforms: all

## More information (optional)
Further clarification about Crossfade is available here https://www.howtogeek.com/57252/how-to-use-crossfade-in-audacity-for-seamless-transitions-between-audio-tracks/

I will provide the crossfade jquery script for conversion to Dart and integrating into this plugin.

I will donate $100 when this feature request is accepted.

**Comment by Gustl22** [comment]
This could be done by using two audio players simultaneously and lower the volume of the first track by a specified duration before the track duration ends. At the same time start another player with the next track and slowly fade in via volume. 

I don't think this will be part of this library, as its too specific and exceeds the scope of this library. We can think about adding an additional package with such features. But the easiest is to implement for yourself. It's really not that hard, I think.

**Comment by Gustl22** [comment]
Closing, see #945
