### ISSUE TITLE
stayAwake not working as expected in Android.

### ISSUE THREAD

**Issue by admincode1** [bluefireteam/audioplayers#1295]
Audioplayers v1.1.0.

> final AudioContext audioContext = AudioContext(
      iOS: AudioContextIOS(
        defaultToSpeaker: true,
        category: AVAudioSessionCategory.playAndRecord,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
        ],
      ),
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.music,
        usageType: AndroidUsageType.media,
        audioFocus: AndroidAudioFocus.gain,
      ),
    );
    AudioPlayer.global.setGlobalAudioContext(audioContext);

Android : Music stops working when screen locked/ background after period of time (for example, after 2 or 3 songs) with  stayAwake: true.
I have `<uses-permission android:name="android.permission.WAKE_LOCK"/>` in AndroidManifest.

iOS: Music stops working when the screen is locked/ background, when current playing song finishes.

Tested with v0.20.1 and never had a problem, play continuously in the background.

**Comment by Gustl22** [comment]
See https://github.com/bluefireteam/audioplayers/blob/516085a692624fa08d3d866b114ea6d25cc8b0e4/troubleshooting.md?plain=1#L84
And #788
