### ISSUE TITLE
Nuget.exe not found, trying to download or use cached version.

### ISSUE THREAD

**Issue by luojt** [bluefireteam/audioplayers#1303]
Running projects on Windows 11 will get stuck.
`Nuget.exe not found, trying to download or use cached version.`

**Comment by luojt** [comment]
move nuget.exe to  C:\Windows\  ,Run successfully.

**Comment by Gustl22** [comment]
Which version of Windows SDK do you use? See #1114

**Comment by Gustl22** [comment]
Closing in favor of #1319
