### ISSUE TITLE
.play not working in version 1.1.1

### ISSUE THREAD

**Issue by abhay99199** [bluefireteam/audioplayers#1308]
## Checklist
- [ ] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

## Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by Gustl22** [comment]
Plz fill issue template ;)

**Comment by Cofinlord** [comment]
I have a similar issue. Dr Angela Yu course uses this package to build her xylophone beginner application. I am unable to play using audiocache 
 await player.setSource(AssetSource('sounds/coin.wav')); 
Forgive me if i apprached this the wrong way. I am new to github.

**Comment by Gustl22** [comment]
@Cofinlord can you open a separate issue and filling the template. Otherwise we cannot help.
Regardless of that, usually you don't need to deal with audiocache anymore. The library takes care of that.

**Comment by matatoMatata94** [comment]
@Cofinlord 
I'm doing the same course from her and I found a solution for it.
In your pubspec.yaml file you have to set audioplayers to ^0.20.1, run pub get and then I created following method from a code that I found:

void playSound(String note) async {
    ByteData bytes = await rootBundle.load('assets/$note.wav');
    Uint8List soundbytes = bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes);
    int result = await note1.playBytes(soundbytes);
    if (result == 1) {
      //play success
     print("Sound playing successful.");
    } else {
      print("Error while playing sound.");
    }
  }

Inside your Xylophonebutton you call it in the onPressed Method like this:
Expanded(
     child: MaterialButton(
                  onPressed: () async {
                    playSound('note1');
                  },
                  color: Colors.red,
                ),
              ),

**Comment by Cofinlord** [comment]
Thanks alot man. appreciate it.

**Comment by enochviewu95** [comment]
Future<void> playSound() async {
    final player = AudioPlayer();
    await player.play(AssetSource('note1.wav'));
  }

Solved mine by using this approach

**Comment by Cofinlord** [comment]
This is what worked for me for individuals who may have problems in the future.
<img width="1440" alt="Screenshot 2022-11-10 at 9 29 22 AM" src="https://user-images.githubusercontent.com/97654709/201105211-c75e020f-7c17-4c94-80b9-8f973b739680.png">
