### ISSUE TITLE
How to handle missing remote files?

### ISSUE THREAD

**Issue by Sundin** [bluefireteam/audioplayers#1314]
Hello! Anyone knows if there's a way to handle missing files when playing from a remote (https) source?
I.e., either checking if the file exist, or catching the error when it occurs. The use case could be for example to play a fallback file in that case.

Sample code:

```
await narration.play(UrlSource(soundPathUrl));
```

I get this error in the log whenever I pass in a faulty `soundPathUrl`:

`flutter: Unexpected platform error: AVPlayerItem.Status.failed`

A simple try-catch does not seem to do the trick. Any other ideas?

**Comment by Sundin** [comment]
Possibly related to https://github.com/bluefireteam/audioplayers/issues/1266

**Comment by Gustl22** [comment]
Yeah let's close it in favor of #1266

**Comment by Sundin** [comment]
To anyone looking for a workaround: you can make a HEAD request to the URL in question before trying to play the file. Based on the response code you will know if the file exists or not.
