### ISSUE TITLE
Failed to build windows release. Always get some error about NuGet WindowsImplementLibrary

### ISSUE THREAD

**Issue by chkecopy** [bluefireteam/audioplayers#1319]
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1

**Comment by kfpv** [comment]
I had this issue because of a misconfigured NuGet package source. Fixed it by opening Visual Studio 2022, going to Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources and making sure the NuGet source link is https://api.nuget.org/v3/index.json

**Comment by exts** [comment]
Was having this issue, I fixed it by uninstalling everything then installing Visual Studio Community 2022 and it worked.

**Comment by munsterlander** [comment]
Was having different issue using `flame_audio` bridge package but the issue was in `audioplayers` except it wasn't an issue, my C++ toolchain was way too out of date.  Using https://github.com/bluefireteam/audioplayers/issues/1319#issuecomment-1298481295 got me going.  I would think that information should be added to the Build Issues section of https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md as it doesn't really mention windows.

**Comment by cybrox** [comment]
Just as a heads up, this currently always fails because Microsoft is having server issues.

```
An error occurred while retrieving package metadata for 'Microsoft.Windows.ImplementationLibrary.1.0.210803.1' from source 'nuget.org'.
  Der Antwortstatuscode gibt keinen Erfolg an: 504 (Gateway Timeout).
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1
```

Is there any way of improving caching on this?

I'm not a huge fan of having my build process be completely dependent on a third party vendors' servers.

**Comment by Gustl22** [comment]
Sorry @cybrox I think you're at the wrong address here, I think it's more a problem of flutter and what they are deciding what to do (for legal or other reasons). Also I don't quite get your point: pub.dev and github.com are also proprietary, which we also heavily depend on 😅

**Comment by Gustl22** [comment]
@cybrox I checked again and I could build and run the flutter app even without internet connection, as long as I run it once successfully without internet connection before.
So I think in your case the package wasn't installed yet, or the response you got from the server confused the `nuget install` command. So I don't really know what to solve, it also is a very edgy case, which I can't really test.

**Comment by cybrox** [comment]
@Gustl22 Thanks for the update! I was also never able to reproduce this again. I assume you are right, that it was the specific response that MS served during that time that caused an issue with NuGet.
