### ISSUE TITLE
Build 1.1.1 - Crash on Android 6.0.1

### ISSUE THREAD

**Issue by p3pp8** [bluefireteam/audioplayers#1322]
Player crashes on Android 6.0.1:

`
E/AndroidRuntime(11475): java.lang.IllegalStateException
E/AndroidRuntime(11475): 	at android.media.MediaPlayer._prepare(Native Method)
E/AndroidRuntime(11475): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1164)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.prepare(MediaPlayerPlayer.kt:89)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.WrappedPlayer.stop(WrappedPlayer.kt:185)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.WrappedPlayer.onCompletion(WrappedPlayer.kt:248)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda-5$lambda-1(MediaPlayerPlayer.kt:17)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.$r8$lambda$3fK1i48Yert5dbg2Q8ZiB5tiKHg(MediaPlayerPlayer.kt)
E/AndroidRuntime(11475): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer$$ExternalSyntheticLambda1.onCompletion(D8$$SyntheticClass)
E/AndroidRuntime(11475): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2883)
E/AndroidRuntime(11475): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11475): 	at android.os.Looper.loop(Looper.java:152)
E/AndroidRuntime(11475): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
E/AndroidRuntime(11475): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11475): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(11475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/AppTracker(11475): App Event: crash
`

**Comment by rpungin** [comment]
I get a similar crash once in a while as well, but on Android 13. It seems to be unrelated to Android version and more related to the actual audioplayers plugin.

```
E/AndroidRuntime(23559): java.lang.IllegalStateException
E/AndroidRuntime(23559): 	at android.media.MediaPlayer._prepare(Native Method)
E/AndroidRuntime(23559): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.prepare(MediaPlayerPlayer.kt:89)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.WrappedPlayer.stop(WrappedPlayer.kt:185)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.WrappedPlayer.onCompletion(WrappedPlayer.kt:248)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda-5$lambda-1(MediaPlayerPlayer.kt:17)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.lambda$3fK1i48Yert5dbg2Q8ZiB5tiKHg(Unknown Source:0)
E/AndroidRuntime(23559): 	at xyz.luan.audioplayers.player.-$$Lambda$MediaPlayerPlayer$3fK1i48Yert5dbg2Q8ZiB5tiKHg.onCompletion(Unknown Source:2)
E/AndroidRuntime(23559): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3542)
E/AndroidRuntime(23559): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23559): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(23559): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(23559): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(23559): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23559): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(23559): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Gustl22** [comment]
Reproduction sample? Thank you :)

**Comment by Pitazzo** [comment]
I do not think neither is related to the OS version, @rpungin. Have you thought about the state of silent mode or do not disturb mode? I could not find any correlation, but are good candidates. Btw, sometime I also get this slightly different trace:

```
PlatformException(Unexpected error!, null, java.lang.IllegalStateException
	at android.media.MediaPlayer._setDataSource(Native Method)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1314)
	at xc.a.b(Unknown Source:7)
	at wc.h.k(MediaPlayerPlayer.kt:2)
	at wc.l.J(WrappedPlayer.kt:4)
	at vc.d.o(AudioplayersPlugin.kt:14)
	at vc.d.e(Unknown Source:0)
	at vc.d$c.b(Unknown Source:14)
	at vc.d$c.invoke(Unknown Source:4)
	at vc.d$e.invokeSuspend(AudioplayersPlugin.kt:2)
	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:4)
	at cc.q0.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.k.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.k.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.a.n(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.d(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.n(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
, null)
```
