### ISSUE TITLE
No package 'gstreamer-1.0' found: While building for Linux

### ISSUE THREAD

**Issue by jyotirmoy-paul** [bluefireteam/audioplayers#1326]
Though I made sure Gstreamer is installed (followed [this guide](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c#install-gstreamer-on-ubuntu-or-debian)), Still cannot build for Linux because of the following error

Just to provide context, this is the pipeline logs: [Linux Build Logs](https://github.com/jyotirmoy-paul/planets/actions/runs/3472807492/jobs/5804095478)

``` 
No package 'gstreamer-1.0' found
[   +1 ms] CMake Error at /snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
[   +1 ms]   A required package was not found
[        ] Call Stack (most recent call first):
[        ]   /snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
[        ]   flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:25 (pkg_check_modules)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/root/parts/planets-puzzle/build/build/linux/x64/release/CMakeFiles/CMakeOutput.log".
[  +18 ms] Building Linux application... (completed in 2,480ms)
[        ] "flutter linux" took 3,021ms.
[   +3 ms] Unable to generate build files
```

Any resolution will be highly appreciated. Thanks!

**Comment by Gustl22** [comment]
@jyotirmoy-paul did you follow these steps?
https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers_linux/requirements.md

**Comment by jyotirmoy-paul** [comment]
Yes @Gustl22 I have tried these as well, but I think I got the issue, instead of installing the dependency in the pipeline machine, I need to install it inside the linux container which builds the snap. I have asked the same question to [them](https://github.com/snapcore/action-build/issues/48). If you have any idea please let me know?

In the meantime, I will keep checking for solutions. Thanks for the reply!

**Comment by jyotirmoy-paul** [comment]
I got the solution, it's just adding the build-packages part in the snapcraft.yaml file

```
parts:
  planets-puzzle:
    build-packages: [libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart```

Thanks!

**Comment by Gustl22** [comment]
Ok didn't know you want to build your own snap :sweat_smile:
