### ISSUE TITLE
Can't play audio files stored on firebase storage while running the app on web

### ISSUE THREAD

**Issue by mostafaAbdelazim** [bluefireteam/audioplayers#1327]
I can't play [this](https://firebasestorage.googleapis.com/v0/b/instaflutter-85faa.appspot.com/o/audio%2F967fd652-43ea-4178-ba23-aa038fdf49d5.mp3?alt=media&token=6e8c8850-c358-4882-8d87-f54530205fae) on web i'm getting 
Error: NotSupportedError: Failed to load because no supported source was found.

## Steps to reproduce
try to play this [audio](https://firebasestorage.googleapis.com/v0/b/instaflutter-85faa.appspot.com/o/audio%2F967fd652-43ea-4178-ba23-aa038fdf49d5.mp3?alt=media&token=6e8c8850-c358-4882-8d87-f54530205fae)

## Logs
Error: NotSupportedError: Failed to load because no supported source was found.

<details>
  <summary>Full Logs</summary>
`Error: NotSupportedError: Failed to load because no supported source was found.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1378:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>`
  Flutter doctor:
  ```
doctor --verbose
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-EG)
    • Flutter version 3.3.8 on channel stable at /Users/mostafaabdelazim/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/mostafaabdelazim/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/mostafaabdelazim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/mostafaabdelazim/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 8B38BB7F-5DC7-45CE-8F63-696A19FA6275 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
</details>

## Audio Files/URLs/Sources
https://firebasestorage.googleapis.com/v0/b/instaflutter-85faa.appspot.com/o/audio%2F967fd652-43ea-4178-ba23-aa038fdf49d5.mp3?alt=media&token=6e8c8850-c358-4882-8d87-f54530205fae

## Environment information

* audioplayers version: ^1.1.1

Platform 1: web
* OS name and version: Google chrome Version 107.0.5304.110 (Official Build) (arm64)
* Device: MBA M1

* build mode: `debug`

Platforms tested without any issue (optional): iOS, macOS

**Comment by Gustl22** [comment]
You can't even play it natively on the web browser: Unsupported meme type.

I downloaded and played it with VLC media player:
![image](https://user-images.githubusercontent.com/18537755/203649748-a82bb07c-920d-4b62-807b-99df996acda9.png)

But I think the browser does not support this format (I think it's `.mp4a` /  `.m4a`) as mime type `mp4`
https://en.wikipedia.org/wiki/Audio_file_format
https://sites.google.com/a/chromium.org/dev/audio-video

```html
<!DOCTYPE html>
<html>
  <body>

  <audio controls>
    <source src="audio-file.m4a" type="audio/mp4">
Your browser does not support the audio element.
  </audio>

  </body>
</html>
```

So there's nothing we can do about
