### ISSUE TITLE
After introducing dependencies, iOS starts to report an error

### ISSUE THREAD

**Issue by fengerwoo** [bluefireteam/audioplayers#1328]
After the introduction of dependencies, nothing has changed, and an error is reported when iOS starts

Flutter version 3.3.5
Audioplayers Version 1.1.1
Device iPhone7  iOS14.7.1

OC selected by iOS language when creating Flutter project

```
Launching lib/main.dart on 988的iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: T6924M2DC5
Running pod install...
Running Xcode build...
Xcode build done.                                           34.2s
Installing and launching...
(lldb) dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/B0310FBD-0ACA-43BD-9E6D-79D3D324B4EE/Runner.app/Runner
  Reason: image not found
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x0000000102cb6b64 dyld`__abort_with_payload + 8
dyld`:
->  0x102cb6b64 <+8>:  b.lo   0x102cb6b80               ; <+36>
    0x102cb6b68 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x102cb6b6c <+16>: mov    x29, sp
    0x102cb6b70 <+20>: bl     0x102cb5168               ; cerror_nocancel
Target 0: (Runner) stopped.
Error launching application on 988的iPhone.
```

**Comment by fengerwoo** [comment]
Just found a solution. The official will see if there is a better solution

My solution is to add these two paths to the "Runpath Search Paths" of the iOS project

```
/usr/bin/swift
/usr/lib/swift
```

As shown in the figure
<img src="https://tva1.sinaimg.cn/large/008vxvgGly1h8du8ab0psj312u0p1tbl.jpg"/>

**Comment by Gustl22** [comment]
Can you compare with our example? 
https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example/ios

Does the error also occur on a fresh project?
