### ISSUE TITLE
Sound in iOS  very low

### ISSUE THREAD

**Issue by dhrubajyoti** [bluefireteam/audioplayers#1341]
## Checklist
- [ ] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

## Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by Gustl22** [comment]
See #1194
