### ISSUE TITLE
when I click on the buttons , there is a sound , but it is not running smoothly (I included mp4 file so you can hear) , in the beginning it is bad , but then becomes good

### ISSUE THREAD

**Issue by MiladZarour** [bluefireteam/audioplayers#1345]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour

- my current code is : 
```
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';

void main() => runApp(XylophoneApp());

class XylophoneApp extends StatelessWidget {
  Future playSound(int soundNumber) async {
    final player = AudioPlayer();
    await player.setSource(AssetSource('note$soundNumber.wav'));
    player.resume();
  }

  Expanded buildKey({Color color, int soundNumber}) {
    return Expanded(
      child: TextButton(
        style: TextButton.styleFrom(backgroundColor: color),
        onPressed: () {
          playSound(soundNumber);
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              buildKey(color: Colors.red, soundNumber: 1),
              buildKey(color: Colors.orange, soundNumber: 2),
              buildKey(color: Colors.yellow, soundNumber: 3),
              buildKey(color: Colors.green, soundNumber: 4),
              buildKey(color: Colors.teal, soundNumber: 5),
              buildKey(color: Colors.blue, soundNumber: 6),
              buildKey(color: Colors.purple, soundNumber: 7),
            ],
          ),
        ),
      ),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/50852900/206896908-f69372ca-bb24-43aa-a673-e6b119884a94.png)

it is creating a 7 wedgits and it is working , but whenever I play it is coming the sound with some iterrupting (hicking) behaviour 
, and the output whenever I click is :
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 1 of 921 libraries in 219ms (compile: 19 ms, reload: 74 ms, reassemble: 75 ms).
V/MediaPlayer( 5408): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5408): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 5408): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5408): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 5408): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5408): cleanDrmObj: mDrmObj=null mDrmSessionId=null

```
https://user-images.githubusercontent.com/50852900/206897052-b981b8a5-6bd2-489c-ba6f-dea9c0b69d08.mp4

## Expected behaviour

- I expect that it will play smoothly 

## Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

<details>

<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by Gustl22** [comment]
This is most likely a performance issue. We can't do much about it, as we rely on the native implementation, which is done by Google / Android themselves. It should work fine on a real device though. Can you confirm?

**Comment by MiladZarour** [comment]
I just test it on my device 
I build the app.apk , and downloaded , and yes it works fine !!!
As I am new in flutter,I never thought trying it in phisical device 
but I will do it in the future ofcourse
Thx for the hint !

**Comment by Gustl22** [comment]
Nice that it works smoothly now. I'll close, as this is not an issue our library could solve.

**Comment by MiladZarour** [comment]
Yes 
Thx a lot for your help
