### ISSUE TITLE
Audio Cache

### ISSUE THREAD

**Issue by xortrike** [bluefireteam/audioplayers#1346]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour
Doesn't clear cache and doesn't delete files

## Expected behaviour
Clear all cache and files

## Steps to reproduce
<details>
<summary>Code sample</summary>

```dart
final AudioPlayer _audioPlayer = AudioPlayer();
final AssetSource _assetSource = AssetSource('intro.wav');

_audioPlayer.play(_assetSource);

_audioPlayer.audioCache.clearAll();
}
```

</details>

## Environment information

* audioplayers version: 1.1.1

Platform 1:
* OS name and version: Windows 10
* Device: Desktop
* build mode: `debug`
* error peculiarities (optional):

Platforms tested without any issue (optional): 
* test peculiarities:

## More information

File: audio_cache.dart:54

Function **clear** does not delete the record (from loadedFiles) and the file, because deletion requires the key to be passed.
Function **clearAll** also passes a value, but it needs a key.

```dart
Future<void> clear(Uri fileName) async {
    final uri = loadedFiles.remove(fileName);
    if (uri != null && !kIsWeb) {
      await File(uri.toFilePath()).delete();
    }
}

/// Clears the whole cache.
Future<void> clearAll() async {
    await Future.wait(loadedFiles.values.map(clear));
}
```

**Comment by spydon** [comment]
Good catch, should be solved in #1347
