### ISSUE TITLE
Play sound with alarm stream

### ISSUE THREAD

**Issue by pbouttier** [bluefireteam/audioplayers#135]
Android have multiple streams for sounds, media, alarm, etc.

Can you implement a new parameter for handle this ? I would like to play my sound like a alarm, to play the sound regardless of the current user's volume for media/songs.

Thanks in advance, and sorry for my bad english

**Comment by erickzanardo** [comment]
@pbouttier does the `respectSilence` flag does not works for what you want? It is false by default: https://github.com/luanpotter/audioplayers/blob/master/lib/audioplayers.dart#L168

**Comment by pbouttier** [comment]
It does not work, if the current volume if 0, no sounds are played. If the volume is low, and i want it to act like a alarm, the sound is barrely audible.

I tested with AudioAttributes.USAGE_ALARM and AudioManager.STREAM_ALARM and it worked as i want.

**Comment by erickzanardo** [comment]
You can add the `volume` parameter on the play method, this should increase the volume, and I think solve your problem.

But I think we should have a better solution to this instead of the `respectSilence` flag.

**Comment by LinderPi** [comment]
> 
> 
> It does not work, if the current volume if 0, no sounds are played. If the volume is low, and i want it to act like a alarm, the sound is barrely audible.
> 
> I tested with AudioAttributes.USAGE_ALARM and AudioManager.STREAM_ALARM and it worked as i want.

How exactly do you use those two Android attributes?

**Comment by jja08111** [comment]
Same issue for me.

I'm making alarm app using this plugin in flutter. But this can't play alarm mode, just play media mode.

I also think `AudioAttributes.USAGE_ALARM` and `Context.ALARM_SERVICE` will work for this.

**Comment by Gustl22** [comment]
It should work with #1388 via:

```dart
var audioContext = const AudioContext(
  android: AudioContextAndroid(
    usageType: AndroidUsageType.alarm,
  ),
);
await AudioPlayer.global.setGlobalAudioContext(audioContext);
await player.setAudioContext(audioContext);
```
