### ISSUE TITLE
onAudioPositionchanged 

### ISSUE THREAD

**Issue by 18BG** [bluefireteam/audioplayers#1351]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by 18BG** [comment]
Je veux savoir si le onAudioPositionchanged marche

**Comment by Gustl22** [comment]
@18BG
1. Plz try to ask your questions in english
2. Fill the issue template with all the information asked in there. Otherwise we cannot help.
3. You most likely don't use the current version of Audioplayers. Try to upgrade it.

**Comment by 18BG** [comment]
Okay I'll send it tomorrow

**Comment by Gustl22** [comment]
@18BG marking as `stale`

**Comment by 18BG** [comment]
> @18BG marking as `stale`

what , don't understand !
