### ISSUE TITLE
Audio has a delay after resume to start to play

### ISSUE THREAD

**Issue by gustoliveira** [bluefireteam/audioplayers#1359]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

Sometimes, when I press to play the audio, it has a big delay to start to play. The `PlayerState` it's `playing` right after press play, the file it's already downloaded.

## Current bug behaviour
1. Set source from deviceFile.
2. `audioPlayer.onPlayerStateChanged` dispatch `isReady` state.
3. Press play button, that calls `audioPlayer.resume()` method.
4. `audioPlayer.onPlayerStateChanged` dispatch `playing` state.
5. Wait until the audio starts to play, sometimes wait more then 1 minute.

## Expected behaviour
1. Set source from deviceFile.
2. `audioPlayer.onPlayerStateChanged` dispatch `isReady` state.
3. Press play button, that calls `audioPlayer.resume()` method.
4. `audioPlayer.onPlayerStateChanged` dispatch `playing` state.
5. Play right after press the button since the state it's ready.

## Reproducing
https://user-images.githubusercontent.com/50436424/209859752-e24fda51-eaee-4547-ab29-0614e38b4229.mp4

## Environment information

* audioplayers version: 1.1.1

Platform 1: Ubuntu 22.10, Ubuntu 22.04 LTS, Ubuntu 18.04 LTS
* build mode: debug and release mode

Platforms tested without any issue:  Windows 10

**Comment by Gustl22** [comment]
Okay seems a very long delay, but as I see the source is a video, so I expect this is quite large. We would need to implement #361 to better tackle this.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
