### ISSUE TITLE
onDurationChanged called constantly on Android

### ISSUE THREAD

**Issue by tantzygames** [bluefireteam/audioplayers#136]
This is reported to have been solved in [#107 ](https://github.com/luanpotter/audioplayers/issues/107) but it's happening to me in 0.10.0.

Also occurring in 0.10.1

**Comment by luanpotter** [comment]
@Kretin1 , that seems to be by design. The method is called every position update.

I believe it might be because while the audio buffers the duration might change.

Is it causing any problems to you though? If so, we can consider changing that. But it seems to me that you could just not listen to that event hahaha

**Comment by subhash279** [comment]
@luanpotter I think onDurationChanged should be called just once to know the entire length of the audio. This is how it works even with html5 audio. 
Also it might be useful to have another listener onLoad to perform any task like moving the position of the audio before playing it. It would be interesting to know your view on this. Currently I am doing this in onDurationChanged but if its called repeatedly it won't be possible.

Also onDurationChanged is not called after setUrl() on android but it is called on ios. Is this something you are looking into?

**Comment by Kretin1** [comment]
I agree. I expected to use onDurationChanged to know when a clip has been loaded or changed. Currently I need to keep my own variable, and check if it's changed... something that I expect would be more efficient if done in the native code.

But most importantly, whatever you choose it should not working differently for Android and iOS.

**Comment by saviourdog** [comment]
same problem

**Comment by nt4f04uNd** [comment]
Same here

**Comment by pierrea** [comment]
+1

**Comment by erickzanardo** [comment]
@luanpotter this discussion is still valid? Is this still something that we want to add?

**Comment by fdietze** [comment]
What I hear from the comments here, is that an async mechanism is needed to know when the player is ready.

**Comment by Gustl22** [comment]
This should be easy to fix by moving the [`onDuration` event](https://github.com/bluefireteam/audioplayers/blob/ff78a42f842e146df7dc98d6d00ae27821355653/packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt#L215) to when `prepared` was called.
