### ISSUE TITLE
bug: use absolute urls in Markdown files to ensure links are valid in sub packages

### ISSUE THREAD

**Issue by pohuing** [bluefireteam/audioplayers#1367]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

This is an issue with the documentation on pub.dev. It links to https://github.com/bluefireteam/audioplayers/blob/master/packages/audioplayers/getting_started.md which is a dead link. 

## Expected behaviour

The project description on pub.dev should instead link to https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md

**Comment by pohuing** [comment]
PS: not sure if this is considered a bug, but it also isn't a feature request so I went with that

**Comment by Gustl22** [comment]
@pohuing yes that's a problem. We use symlinks in our sub projects, so they link to a file which only exists on root level. We should use absolute urls in our markdown files to tackle this problem. Are you interested in a PR?

**Comment by pohuing** [comment]
I'll try to track them down. They're supposed to be a direct link to the repo then?
