### ISSUE TITLE
Move AudioPool from flame_audio to AudioPlayers

### ISSUE THREAD

**Issue by spydon** [bluefireteam/audioplayers#1368]
## Checklist
- [x] I made sure that the feature I am proposing doesn't already exist

## Use case / Problem

AudioPool is useful in more cases than only for Flame games, and there is no longer a reason to not move it over.

## Proposal / Solution

Move `AudioPool` from flame_audio to `AudioPlayers`.

## Platforms

Affected Platforms: all

## More information (optional)
https://github.com/flame-engine/flame/blob/main/packages/flame_audio/lib/audio_pool.dart

**Comment by Gustl22** [comment]
Implemented via #1403
