### ISSUE TITLE
Error with build on IOS device

### ISSUE THREAD

**Issue by Fudal** [bluefireteam/audioplayers#1370]
## Checklist
- [x ] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour
When I archive iOS app version, archive is failed with error:
**Module 'audioplayers_darwin' not found**

## Expected behaviour
Archive iOS app is successful

## Steps to reproduce
1. use audioplayers: 1.2.0 in pubspec.yaml
2. try archive iOS app

<details>
If I use the latest version of audioplayers - 1.2.0 I cannot build a production version of the application. When building the version for appstore via archive option in xCode I get the above error. I cannot build this version of the app.

</details>

## Logs
```
/ios/Runner/GeneratedPluginRegistrant.m:12:9 Module 'audioplayers_darwin' not found

```

<details>

  Flutter doctor:
  ```
[!] Flutter (Channel unknown, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale pl-PL)
    ! Flutter version 3.3.10 on channel unknown at /Users/mac1/fvm/versions/3.3.10
    ! Upstream repository unknown
    • Framework revision 135454af32 (3 tygodnie temu), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mac1/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/mac1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/mac1/Desktop/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
  ```
</details>

## Environment information

* audioplayers version:
  1.2.0

Platform 1: ios
* OS name and version: iOS 16.2
* Device:  
  * physical device: iPhone

* build mode: `release`

Platforms tested without any issue (optional): android

**Comment by Gustl22** [comment]
Can you post the exact command that you use to ~archive~ the app? `flutter build ipa`?
Did you try a `flutter clean` and `flutter pub get` before. Did you run the app successfully before e.g. on your simulator?

**Comment by Fudal** [comment]
@towcar no, i had to use another library in my project.

**Comment by Gustl22** [comment]
@towcar @Fudal that's weird, there are plenty of users who can build successfully for iOS and macOS. It's also used for [flame](https://pub.dev/packages/flame). If you provide more details (especially the exact steps and what command you used), we may are able to help.
