### ISSUE TITLE
[audioplayers_web] Error: "@staticInterop" classes should not contain any generative constructors

### ISSUE THREAD

**Issue by JonasJW** [bluefireteam/audioplayers#1378]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour
Building web application fails with this error: `Error: "@staticInterop" classes should not contain any generative constructors.`(Full error below)

The odd part is that  this error only occurs when I'm trying to deploy on Vercel, not when I'm building it locally. I have no idea what the difference in the environment is but Vercel builds the application just as I would locally. (More below at Steps to reproduce)

When searching this error, I found this issue: https://github.com/flutter/flutter/issues/115988, which says one should use `external factory ...` instead of `external ...`, which is thecase in `web_audio_js`.

To test this solution, I forked the repo and applied these changes: https://github.com/JonasJW/audioplayers/blob/main/packages/audioplayers_web/lib/web_audio_js.dart

Using my fork, the errors are fixed.

````
../.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/lib/web_audio_js.dart:8:12:
--
22:32:48.873 | Error: `@staticInterop` classes should not contain any generative constructors.
22:32:48.873 | external JsAudioContext();
22:32:48.873 | ^
22:32:48.873 | ../.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/lib/web_audio_js.dart:24:12:
22:32:48.873 | Error: `@staticInterop` classes should not contain any generative constructors.
22:32:48.873 | external AudioNode();
22:32:48.873 | ^
22:32:48.874 | ../.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/lib/web_audio_js.dart:34:12:
22:32:48.874 | Error: `@staticInterop` classes should not contain any generative constructors.
22:32:48.874 | external AudioParam();
22:32:48.874 | ^
22:32:48.874 | ../.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/lib/web_audio_js.dart:44:12:
22:32:48.874 | Error: `@staticInterop` classes should not contain any generative constructors.
22:32:48.874 | external StereoPannerNode();
22:32:48.874 | ^
22:32:48.874 | ../.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/lib/web_audio_js.dart:54:12:
22:32:48.874 | Error: `@staticInterop` classes should not contain any generative constructors.
22:32:48.874 | external MediaElementAudioSourceNode();
22:32:48.874 | ^
22:32:48.874 | Error: Compilation failed.
22:32:48.874 |  
22:32:48.874 | #0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:237:7)
22:32:48.875 | <asynchronous suspension>
22:32:48.875 | #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
22:32:48.875 | <asynchronous suspension>
22:32:48.875 | #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
22:32:48.875 | <asynchronous suspension>
22:32:48.875 | #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
22:32:48.876 | <asynchronous suspension>
22:32:48.876 | #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
22:32:48.876 | <asynchronous suspension>
22:32:48.876 | #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
22:32:48.876 | <asynchronous suspension>
22:32:48.876 | #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
22:32:48.876 | <asynchronous suspension>
22:32:48.876 | #7      buildWeb (package:flutter_tools/src/web/compile.dart:54:32)
22:32:48.876 | <asynchronous suspension>
22:32:48.877 | #8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:139:5)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1275:27)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:290:9)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
22:32:48.877 | <asynchronous suspension>
22:32:48.877 | #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
22:32:48.877 | <asynchronous suspension>
22:32:48.878 | #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
22:32:48.878 | <asynchronous suspension>
22:32:48.878 | #17     main (package:flutter_tools/executable.dart:91:3)
22:32:48.878 | <asynchronous suspension>
22:32:48.878 |  
22:32:48.878 | Compiling lib/main_platform.dart for the Web...                    19.6s
22:32:48.878 | Exception: Failed to compile application for the Web.
22:32:48.896 | Error: Command "flutter/bin/flutter build web —release -t lib/main_platform.dart --web-renderer=canvaskit" exited with 1
````

## Expected behaviour
Build successfully

## Steps to reproduce
As mentioned I don't encounter this error locally but only when deploying my web application on vercel.

To deploy a flutter application on vercel you provide access to the github repo and enter an install and build command.

Install command: `if cd flutter; then git pull && cd .. ; else git clone https://github.com/flutter/flutter.git; fi && ls && flutter/bin/flutter doctor && flutter/bin/flutter clean && flutter/bin/flutter config --enable-web`

Build command: `flutter/bin/flutter build web —release --web-renderer=canvaskit`

As you can see, it installs flutter first, then builds the web application. Unfortunatly, I do not understand why this error only occurs on Vercel but I could not reproduce it when building locally.

Never the less, I still think this is an issue worth fixing with a simple fix as provided above.

I'm happy to create a PR with the fix.

**Comment by spydon** [comment]
Doesn't seem like there is any downside to changing that?

> I'm happy to create a PR with the fix.
Sounds good!

**Comment by Gustl22** [comment]
I think this has to do with the dart version, but despite the description in flutter/flutter#115988 it does not occur in the current stable branch of flutter, as it is still using 2.18 or something. The limitation was introduced in [2.19.0-319.0.dev](https://github.com/dart-lang/sdk/releases/tag/2.19.0-319.0.dev)
https://github.com/dart-lang/sdk/commit/b6526beeab59ffd2ecc6a48a60a08b6508c22047 

As you download the master branch of flutter on Vercel you use also these dart versions and come to that error.

**Comment by spydon** [comment]
> I think this has to do with the dart version, but despite the description in flutter/flutter#115988 it does not occur in the current stable branch of flutter, as it is still using 2.18 or something. The limitation was introduced in [2.19.0-319.0.dev](https://github.com/dart-lang/sdk/releases/tag/2.19.0-319.0.dev)
> https://github.com/dart-lang/sdk/commit/b6526beeab59ffd2ecc6a48a60a08b6508c22047 
> 
> As you download the master branch of flutter on Vercel you use also these dart versions and come to that error.

Would it still work on Dart 2.18, or would this be breaking?

**Comment by Gustl22** [comment]
> Would it still work on Dart 2.18, or would this be breaking?

@spydon no regression noticable in Dart 2.18 :)

**Comment by spydon** [comment]
> > Would it still work on Dart 2.18, or would this be breaking?
> 
> @spydon no regression noticable in Dart 2.18 :)

Maybe worth merging it then so we don't have to care about it later? :)
