### ISSUE TITLE
Android, call `pause` while in `prepare` status cause PlatformException

### ISSUE THREAD

**Issue by realli** [bluefireteam/audioplayers#139]
When I try to call `pause` after `play` I got PlatformException
And I checked the android code, find that during `prepare`, `pause` is not a valid operation.
And this Exception cann't be catched by flutter side.

I think we can add a preparing state or loading state, or make `play` resolved only when loading is finished.

**Comment by luanpotter** [comment]
The WrappedPlayer java class should have methods that deal with those nasty states from android's mediaplayer. We need to check on pause method what's it's doing, but basically it should delay execution of the pause request until everything is prepared. The idea is that the user of the WrappedPlayer api doesn't need to be aware of these state changes and locks.
