### ISSUE TITLE
Unable to play Audio file from Asset folder under my project

### ISSUE THREAD

**Issue by Actalwar** [bluefireteam/audioplayers#1397]
I have been trying to run some audio files from asset folder but they are not playing at all. Below is my code snippet: There is no error, the audio just does not play if I click on the button. The audio file is in assets folder under project.  Also, the getting started documentation link is not working. 

`import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';
import 'package:audioplayers/audioplayers.dart';

void main() => runApp(XylophoneApp());

class XylophoneApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: TextButton(
                onPressed: () async {
                  final player = AudioCache();
                  // player.load('note1.wav');
                  await player.load('note1.wave');
                },
                child: Text('Click me')),
          ),
        ),
      ),
    );
  }
}
`

**Comment by Actalwar** [comment]
Thank you. The Getting started explains that we need to use **AudioCache** to play audio from within project. That is the reason I used that.

**Comment by Gustl22** [comment]
`AudioCache` is further used under the hood, and can be replaced if wanted. But in 99% it's not the case.

**Comment by Actalwar** [comment]
Thank you @Gustl22 for your assistance . I was able to run my app using following but on **ElevatedButton**. This can be closed. 

`final player = AudioPlayer();
    player.play(AssetSource('note$a.wav'));`
