### ISSUE TITLE
'audioProcessing' deprecated in iOS 10

### ISSUE THREAD

**Issue by MauroDiamantino** [bluefireteam/audioplayers#1402]
Hi, I'm getting the error "'audioProcessing' was deprecated in iOS 10.0: No longer supported" from `xcrun xcresulttool` when I try to build ipa file to publish my app to App Store. The build command was `flutter build ipa --obfuscate --split-debug-info=debug -v`.

## Current bug behaviour
It seems the package is using the `audioProcessing` property which is deprecated from iOS 10, as you can see [here](https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616564-audioprocessing).

## Expected behaviour
I ask you to help me to find a workaround (like changing the audio file format) or to update the package in such a way that it no uses anymore that property.

## Steps to reproduce
The following code can help you to see the problem. Be sure to install the package 'audioplayers' and to add the audio file to the assets folder and to pubspec.yaml.

```dart
import 'package:audioplayers/audioplayers.dart';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'dart:async';

void main() {
	runApp(const A());
}

class A extends StatefulWidget {
  @override
  AS createState() => AS();
}

class AS extends State<A> {
	final reproductor = AudioPlayer();
    final alert = AssetSource('alert.mp3');


	@override
	void initState() {
		reproductor.setPlayerMode(PlayerMode.lowLatency);
	}

	@override
	Widget build(BuildContext context) {
		return Scaffold(
	      appBar: AppBar(
	        title: Text('A'),
	      ),
	      body: Center(
	            const Text(
	              'Press button to play sound alert',
	            ),
	      ),
	      floatingActionButton: FloatingActionButton(
	        onPressed: ()=>reproductor.play(alert),
	        tooltip: 'Alert',
	        child: const Icon(Icons.add),
	      ),
	    );
	}
}
```

## Logs
Fragments of output of `flutter build ipa`:
...
[        ] Xcode archive done.                                         134,1s
[   +2 ms] executing: xcrun xcresulttool get --path /var/folders/rw/rbzvfvfd0n3_rkk06kq4h9y00000gn/T/flutter_tools.xUeHD0/flutter_ios_build_temp_dirEHefBz/temporary_xcresult_bundle --format json
[ +145 ms] {
                      "_type" : {
                        "_name" : "ActionsInvocationRecord"
                      },

....
`
"warningSummaries" : {
                                  "_type" : {
                                    "_name" : "Array"
                                  },
                                  "_values" : [
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "documentLocationInCreatingWorkspace" : {
                                        "_type" : {
                                          "_name" : "DocumentLocation"
                                        },
                                        "concreteTypeName" : {
                                          "_type" : {
                                            "_name" : "String"
                                          },
                                          "_value" : "DVTTextDocumentLocation"
                                        },
                                        "url" : {
                                          "_type" : {
                                            "_name" : "String"
                                          },
                                          "_value" :
                                          "file:\/\/\/Users\/guillermodanielortizcarmona\/flutter\/.pub-cache\/hosted\/pub.dev\/audioplayers_darwin-3.0.0\/ios\/Classes\/AudioContext.swift#CharacterRangeLen=0&EndingColumnNumber=20&EndingLineNumber=77&StartingColumnNumber
                                          =20&StartingLineNumber=77"
                                        }
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Deprecation"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "'audioProcessing' was deprecated in iOS 10.0: No longer supported"
                                      }
                                    }
                                  ]
                                }
                              },`

## Environment information

* audioplayers version: "3.0.0"

Platform 1: ios
* OS name and version: iOS >11.0
* build mode: `release`
* error peculiarities (optional): --obfuscate flag

**Comment by Gustl22** [comment]
That's odd: [AVAudioSessionCategory](https://github.com/bluefireteam/audioplayers/blob/ab15cb02cf939347772ac9fc961b5f01d7bad94b/packages/audioplayers_platform_interface/lib/api/audio_context_config.dart#L534) does not include this option.
But it is defined [here](https://github.com/bluefireteam/audioplayers/blob/ab15cb02cf939347772ac9fc961b5f01d7bad94b/packages/audioplayers_darwin/ios/Classes/AudioContext.swift#L77), but never actually called. And on initialization `playAndRecord` is used as default. 
Maybe you can set the global `AudioContext` and see, if it helps:

```
  AudioPlayer.global.setGlobalAudioContext(AudioContextConfig(/*...*/).build());
```

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
