### ISSUE TITLE
GitHub CI doesn't support rendering on metal for MacOS

### ISSUE THREAD

**Issue by spydon** [bluefireteam/audioplayers#1405]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour

This is not a bug from our side, but from GitHub CI.
They don't support rendering on metal for their MacOS CI hosts which makes it impossible to use Flutter 3.7.0, so currently we've had to pin the version to 3.3.10.

## Expected behaviour

It should work with the 3.7.0, once GitHub CI has fixed that issue we should remove the version pinning here:
https://github.com/bluefireteam/audioplayers/pull/1399/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R186

## More information

https://github.com/actions/runner-images/issues/1779#issuecomment-707071183

**Comment by Gustl22** [comment]
See also 
https://github.com/flutter/flutter/issues/108304
https://github.com/flutter/engine/pull/37733
https://github.com/actions/runner-images/issues/183

**Comment by Gustl22** [comment]
We may can get the tests running with latest Flutter on M1 mac as stated here:
https://github.com/flutter/flutter/issues/118469#issuecomment-1406604477
Maybe Github supports metal graphics for these, or some other magic is happening.

**Comment by spydon** [comment]
We have no option of choosing to run on M1s on GitHub yet:
https://github.com/actions/runner-images/issues/2187
https://github.com/github/roadmap/issues/528

**Comment by Gustl22** [comment]
Ah that explains, why it worked. Of course self-hosted runners have GPU support.

**Comment by spydon** [comment]
If anyone would be keen to set up a MacOS runner on Codemagic maybe @erickzanardo would be willing to spend some of his credit on there, because if I remember correctly he won an insane amount of those credits on a hackathon 😅

**Comment by erickzanardo** [comment]
Sure thing!

**Comment by Gustl22** [comment]
Maybe GH is doing something about it: 
https://github.com/actions/runner-images/issues/183#issuecomment-1408417086
We are not in a hurry, as I expect, support for Flutter 3.3.x will at least be a year or so.

**Comment by erickzanardo** [comment]
Is there any other instances on GH that would allow that? If so, and if we want to keep all our actions running on a single CI service, we may be able to pay for it with Blue Fire's fund

**Comment by spydon** [comment]
> Is there any other instances on GH that would allow that? If so, and if we want to keep all our actions running on a single CI service, we may be able to pay for it with Blue Fire's fund

There is not, possibly Q3 2023 according to their roadmap.

**Comment by erickzanardo** [comment]
Got ya!

We can use codemagic then, the only thing is that, as you said, my insane amount of credits are tied to Cherry Bit's team, so I would need to put AP under that team instead of creating a Blue Fire team for example.

If you don't mind it, I am ok with it too

**Comment by Gustl22** [comment]
I would recommend waiting for like 2 to 3 month. Afterwards, Flutter reintroduces OpenGL support or GH has something up in their sleeve, and we would do the transfer / rewriting actions for nothing. Especially cause we have the time and also credits are also exhausted some day in the far future (?).

**Comment by erickzanardo** [comment]
Alright, makes sense IMO.

About the credits exhausted, indeed they will! But I am fine with spending part of the income that Blue Fire gets from Patreon and sponsors into something like this.

Anyway, lets wait then, but feel free to reach me if we decide to move to codemagic.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
