### ISSUE TITLE
Not sound in iOS

### ISSUE THREAD

**Issue by always-together12** [bluefireteam/audioplayers#1407]
How are you?
Audio Sound does not work in iOS. (working well in Android).
it seems like play. (i can get the total duration and position changed event).
but i am not able to listen the sound in iOS.
i added this to the info.plist file.
`	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>`
Could you please let me know what i am missing?
Thank you.

**Comment by Gustl22** [comment]
Have a look at #1194
