### ISSUE TITLE
Massive audio play on ios lead to memory leaks

### ISSUE THREAD

**Issue by feroult** [bluefireteam/audioplayers#141]
It refers to a bug opened in `Flame`: https://github.com/luanpotter/flame/issues/70

Digging into the code I realized that `AudioCache` does unnecessary instantiations of `AudioPlayer` for the same audio file.

```
AudioPlayer _player(PlayerMode mode) {
    return fixedPlayer ?? new AudioPlayer(mode: mode);
}
```

It is only a guess. Can't assure that this is the problem.

**Comment by luanpotter** [comment]
@feroult, that must be done, otherwise the files can't be played simultaneously. At least on android, each media player instance can play only one audio at a time, that's why each call from play creates a brand new player by default (ofc you can change that using the fixedPlayer). The thing is, the file data per se is cached in memory because of audio cache's operations (or at least is should). I don't know if that is a good rationale for ios, though.

**Comment by amfangYahoo** [comment]
Checked [flame-engine/flame#70](https://github.com/flame-engine/flame/issues/70), with refer [audioplayers/Resource leak? #56](https://github.com/luanpotter/audioplayers/issues/56).

I made below limited AudioCache to play game sounds simultaneously, 
I think this can be interim workground for avoid Memory leaks on Ios, And I tested, that's fine to work for use, hope can help others:

class GameAudioPool {

  List<AudioCache> audioCaches = [];

  List<String> files;
  int maxPlayers;

  GameAudioPool(this.maxPlayers, {this.files}) {}

  Future init() async {
    for (int i = 0; i < maxPlayers; i++) {
      audioCaches.add(await _createNewAudioCache());
    }
  }

  Future<AudioPlayer> play(String file, {volume = 1.0}) async {
    for(int i = 0; i < maxPlayers; i++){
      if(audioCaches[i].fixedPlayer.state != AudioPlayerState.PLAYING){
        return audioCaches[i].play(file, volume: volume, mode: PlayerMode.LOW_LATENCY);
      }
    };
  }

  Future<AudioCache> _createNewAudioCache() async {
    final AudioCache audioCache = AudioCache(prefix: 'audio/', fixedPlayer: AudioPlayer());
    await audioCache.fixedPlayer.setReleaseMode(ReleaseMode.STOP);
    await audioCache.loadAll(files);
    return audioCache;
  }
  /// Clears all the audios in the cache
  void clearAll() {
    audioCaches.forEach((audioCache){
      audioCache.clearCache();
    });
  }

  /// Disables audio related logs
  void disableLog() {
    audioCaches.forEach((audioCache){
      audioCache.disableLog();
    });
  }
}

main() async{
  GameAudioPool myAudio = GameAudioPool(5, files: songs);
  myAudio.init();
  ...
  myAudio.play("xxxxx.wav");
}

**Comment by Gustl22** [comment]
Seems like this is less about AudioPool, but more an issue of ios, which should be solved in the mean time.
https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/lib/src/audio_pool.dart
