### ISSUE TITLE
Audio can not be played (CORS error, can't get the media file)

### ISSUE THREAD

**Issue by balabablu** [bluefireteam/audioplayers#1410]
Hi, I found an issue about web application when playing audio. I used both chrome and edge for testing, the results are the same.

Here is the flow:
(1) After setting up source url to AudioPlayer(), I tried to play the audio but nothing happen. 
(2) I take a look for audioPlayer.getDuration(), it shows 0 duration.
(3) I press F12 to enter dev mode of chrome, press "Network" and saw that one row about audio file
Name: xxx.mp3
Status: CORS error
Type: media
Initiator: Other
Size: 0B

The URL is end with .mp3, it is accessible and not a redirect. 

```dart
final audioPlayer = AudioPlayer();
await audioPlayer.setSourceUrl(url);  
print(await audioPlayer.getDuration()); // 0:00:00.000000
```
Tested version: v1.1.1 or above.

**Comment by Gustl22** [comment]
Did you find #693? You must enable Cors on your server, or [disable web security](https://stackoverflow.com/a/74783428/5164462) e.g. in your chrome browser.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
