### ISSUE TITLE
setSourceBytes is not currently implemented on iOS ? Will it be soon ? 

### ISSUE THREAD

**Issue by sylvainjack** [bluefireteam/audioplayers#1418]
I tried playing sound file from a SourceBytes on IOS and it didn't work. Will this be developed ?

**Comment by Gustl22** [comment]
Unfortunately, we are at our capacity limit, especially for MacOS / iOS, we don't have any real devices to test. We do this in our spare time and are relied on our community. We are happy to review any Merge Requests, if you are interested in developing such a feature for these platforms. If you feel confident, we can help you in contributing! thx :)

**Comment by Gustl22** [comment]
See also #1269

**Comment by spydon** [comment]
I think this can be closed as a duplicate?
