### ISSUE TITLE
OS Error: The process cannot access the file because it is being used by another process. , errno = 32

### ISSUE THREAD

**Issue by humam-alBasha** [bluefireteam/audioplayers#1424]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

```
  static Future<void> play() async {
    try {
    final Source source = AssetSource("music/scale-f6.mp3");
      await player.stop();
      await player.play(source);
    } catch (e) {
      debugPrint("AudioPlayerModel.play : $e");
    }
  }
```

if hot restart code .

Exception has occurred.
FileSystemException (FileSystemException: Cannot open file, path = 'C:\Users\HUMAMA~1\AppData\Local\Temp/laser.wav' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32))

### Proposal / Solution

file `audio_cache.dart`
function name : fetchToMemory 
```
    await file.delete(recursive: true); // add this line
    await file.create(recursive: true);
    await file.writeAsBytes(byteData.buffer.asUint8List());
```

### Affected platforms

Windows

### Working on PR

no way

**Comment by Gustl22** [comment]
I think we can favor #1120 then.

**Comment by humam-alBasha** [comment]
> You can't delete a file that is being used by another process in windows either, so that workaround wouldn't work. There is a bit more explanation [here](https://stackoverflow.com/a/70720610/789545) and [here](https://github.com/flutter/flutter/issues/10437).

I tried before writing a comment, it can be deleted without any problem. Tested on Windows

**Comment by spydon** [comment]
> I tried before writing a comment, it can be deleted without any problem. Tested on Windows

That's odd, I wonder how that is possible. What filesystem are you running?

**Comment by humam-alBasha** [comment]
> > I tried before writing a comment, it can be deleted without any problem. Tested on Windows
> 
> That's odd, I wonder how that is possible. What filesystem are you running?

The file system is NTFS.

**Comment by spydon** [comment]
> The file system is NTFS.
> The audio clip must end or stop. 
> before hot resort

Do you mean that you have already stopped it when deleting the file, or that it should stop after deleting it?
I wonder if when flutter deletes the file it disposes any other open sockets that flutter has to the file, if that is the case this could work.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA

**Comment by Gustl22** [comment]
We have to handle this reliably for all platforms. Closing this in favor of #1120 . Please comment there or make a PR if you come up with a solution :) Thx
