### ISSUE TITLE
Some problem about oncompleted  callback

### ISSUE THREAD

**Issue by zyk-miao** [bluefireteam/audioplayers#1429]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

The oncompleted  callback will be call twice after flutter hot restart.
And when I play mp4 the oncompleted  callback won't be call.

### Steps to reproduce

onPlayerStateChanged.listen((PlayerState s) {
        LogE(s);
        }
      });

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Windows, Linux

### AudioPlayers Version

3.0.1

### Screenshots

![图片](https://user-images.githubusercontent.com/45023244/222321231-4e24d74b-8aa2-4248-99b2-c3caf97d426b.png)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by zyk-miao** [comment]
linux onDurationChanged call 0 and log 'AudioPlayers: Could not query current duration'.

**Comment by Gustl22** [comment]
Hot restart / reload is not an issue with audioPlayers. We currently cannot do anything about it. If you want to test properly close the application entirely, see #1120.
