### ISSUE TITLE
flutter: Unexpected platform error: AVPlayerItem.Status.failed

### ISSUE THREAD

**Issue by hatemragab** [bluefireteam/audioplayers#1430]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

when run set from url and play 
```
await _player.play(UrlSource(audioSrc.url!), position: _currentDuration);
```
it works in android but ios not working
this is the url the wav not working on ios
```
https://superupdev.online/apps/x.wav
```

### Expected behaviour

play normal on ios

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### Platform details

Ios 16.0

### AudioPlayers Version

3.0.1

### Build mode

debug

### Audio Files/URLs/Sources

https://superupdev.online/apps/x.wav

### Logs

[[
```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
[  my full logs or a link to a gist](flutter: Unexpected platform error: AVPlayerItem.Status.failed)
  ```

  Flutter doctor:
  ```
• No issues found!
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-EG)
    • Flutter version 3.7.3 on channel stable at /Users/hatemragap/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hatemragap/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4533

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64  • Android 10
      (API 29) (emulator)
    • iPhone 14 Pro (mobile)               • 19B3A8FA-7DE7-4B6F-A0C0-E6F28A264F80 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 13.2.1
      22D68 darwin-arm64 (Rosetta)
    • Chrome (web)                         • chrome                               • web-javascript • Google
      Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
➜  ~ 

  ```
</details>
](flutter: Unexpected platform error: AVPlayerItem.Status.failed)](flutter: Unexpected platform error: AVPlayerItem.Status.failed)

### Working on PR

no way

**Comment by SyedSaadHussain** [comment]
any update?

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA

**Comment by jeet2609** [comment]
Can you please share your code and the URL you are trying to play the audio from?

**Comment by SyedSaadHussain** [comment]
> Can you please share your code and the URL you are trying to play the audio from?
i have tried many audio file none of them was working.

void playAudio() async{
    advancedPlayer.dispose();
    advancedPlayer= AudioPlayer();
    advancedPlayer.setPlaybackRate( speed);
    Future.delayed(Duration.zero, () async {
      this.advancedPlayer.onDurationChanged.listen((d) {
        setState(() {
          _duration = d;
        });
      });
      this.advancedPlayer.onPositionChanged.listen((p) {
        setState(() {
          _position = p;
        });
      });
      this.advancedPlayer.onPlayerComplete.listen((event) {
        setState(() {
          _position = Duration(seconds: 0);
          isPlaying = false;
        });

      });
    });

    this.advancedPlayer.play(DeviceFileSource(currentBookAudio.AudioURL)).then((value){
            setState((){
              isPlaying=true;
            });
    });
  }

**Comment by Gustl22** [comment]
@hatemragab the file link is broken. Please wrap it in a zip and upload it here.

**Comment by wangx9604** [comment]
I met the same problem, my audio url is “https://studyfile.cdn.bcebos.com/EP/333CEB93AB061D88B42D322883F5AACA/WORK/3/1680572598496/8f2f38db-6ef3-4348-a79b-20ad965aaffc.amr”，it plays fine on android，but it doesn't work on ios

**Comment by Gustl22** [comment]
@wangx9604 Amr is not supported for iOS since iOS 4.3, see https://stackoverflow.com/a/1761586/5164462

**Comment by hatemragab** [comment]
> @hatemragab the file link is broken. Please wrap it in a zip and upload it here.
> 
> 
> 
> Possibly iOS doesn't support the format. Despite it's a wav file extension it could contain another format, which is not matching the extension.

yes is was webM and i fixed it by play the voice by VLC

**Comment by Gustl22** [comment]
Closing in favor of #1494
