### ISSUE TITLE
How do I play *.ulaw file ?

### ISSUE THREAD

**Issue by Angkhan1992** [bluefireteam/audioplayers#1435]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

I tried to play *.ulaw file on audioplayers. 
But the app crashed (for ios version, didn't check on android and other versions)
Example Link
https://stcadevicedata.blob.core.windows.net/audio/sam’shome_459/1668140740.16229.ulaw

Please update me. Thanks.

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS

### Working on PR

yeah

**Comment by Angkhan1992** [comment]
And if possible, could you let me know the supported file type list?

**Comment by Gustl22** [comment]
I think ulaw isn't supported for iOS: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#supported-formats--encodings
There isn't much you can do about it, as it has to be supported by the platform player.

**Comment by Angkhan1992** [comment]
I can see some ios apps on native platform. 
But I want to implement that on flutter/dart.
I showed a sample app via appstore link below.
https://apps.apple.com/us/app/carealert/id1403367252
So I think the ios platform is supported *.ulaw file type.

**Comment by Gustl22** [comment]
@Angkhan1992 So did you succeed playing your mentioned file on iOS with the native player? If so, it should also work with audioplayers. I cannot test, as I'm lacking of apple devices.

**Comment by Gustl22** [comment]
I can play it now, maybe it was fixed with #1625
