### ISSUE TITLE
Disposed PlayerState

### ISSUE THREAD

**Issue by felixriehm** [bluefireteam/audioplayers#1450]
### Use case / Problem

When you dispose an `AudioPlayer` object the `PlayerState` is set to `stopped`. How do you decide now if you want to replay this `AudioPlayer` object or not? if your condition is 

```dart
if (player.state != PlayerState.playing && player.state != PlayerState.completed) {
    player.resume();
}

player.onPlayerComplete.listen((event) {
    circle.player.dispose();
});
```

you are out of luck...

Workaround is to assign `null` to `player` and then check if the player is null....

```dart
player?.onPlayerComplete.listen((event) {
    player?.dispose();
    player = null;
});

if (player != null && player?.state != PlayerState.playing && player?.state != PlayerState.completed) {
    player?.dispose();
    player = null;
}
```

### Proposal / Solution

Add `PlayerSate.disposed`

### Example Code

```dart
if (player.state != PlayerState.disposed && player.state != PlayerState.playing && player.state != PlayerState.completed) {
    player.resume();
}
```

**Comment by Gustl22** [comment]
yeah i think it's a nice addition. Although i'm not sure, if we want this to be in the same row with the other player states, or just another variable in the `AudioPlayer`. But I think it is reasonable to add this to the `AudioPlayer().state` property.

**Comment by spydon** [comment]
Sounds like it could be in the same state field as the rest to me, because a disposed player should never be started again right?

**Comment by Gustl22** [comment]
@spydon yeah that's the final state :D
