### ISSUE TITLE
Error (Xcode): Framework not found audioplayers

### ISSUE THREAD

**Issue by karafrat921** [bluefireteam/audioplayers#1452]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I'm getting this error even when upgrading the package to the latest version and even deleting the package

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

audioplayers: ^3.0.1

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by vikramaggarwal13** [comment]
I have added audioplayers dependency in pubspec.yaml but its adding audioplayers_darwin in generatedpluginregistrant and when i try to play using xcode then I am getting "Module 'audioplayers_darwin' not found"

**Comment by Gustl22** [comment]
Did you try a `flutter clean` and `flutter pub cache clean` and `flutter pub get` before running the app?

**Comment by vikramaggarwal13** [comment]
Tried but again the same issue is there 

OUTPUT OF  flutter build ios 
Building .......... for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXX
Running pod install...                                             443ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        649ms
Xcode build done.                                           27.9s
Failed to build iOS app
Parse Issue (Xcode): Module 'audioplayers_darwin' not found
................................/ios/Runner/GeneratedPluginRegistrant.m:11:8


Encountered error while building for device.

**Comment by sgruhier** [comment]
same for me

**Comment by karafrat921** [comment]
> Did you try a `flutter clean` and `flutter pub cache clean` and `flutter pub get` before running the app?

yes, but it didn't work

**Comment by sgruhier** [comment]
FYI If you create a new flutter project, add audioplayers and try to build it in xcode, you see that error.
Latest flutter, latest xcode

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3385/229508800-f5910da2-9b05-4367-9637-7566d57282dc.png">

**Comment by sgruhier** [comment]
FYI, moving back to XCode 14.2, it works. The issue I guess comes from XCode 14.3

**Comment by Gustl22** [comment]
Did you try this https://github.com/flutter/flutter/issues/53573#issuecomment-680265617 ? 
Plz state what you have yet tried. Did you once run it from XCode and in the ios folder. Did you do a `pod update` ?

**Comment by sgruhier** [comment]
XCode 14.2 worked for me but now with latest flutter version, everything works on latest xcode

**Comment by loonix** [comment]
Same problem here:

```shell
Xcode build done.                                           18.0s
Failed to build iOS app
Error (Xcode): Framework not found audioplayers

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by loonix** [comment]
Found the solution for this.

![image](https://github.com/bluefireteam/audioplayers/assets/3384277/aacf70b0-cafe-4538-8e18-b35abf5d9129)


1. Open your Xcode project.
2. Navigate to the "Build Settings" tab.
3. Select the "Linking" category.
4. Look for the "Other Linker Flags" setting and expand it.
5. Find the flag that includes "audioplayers". and also remove the "-framework", before it
6. Remove the flag by clicking on it and pressing the delete key, or by right-clicking and selecting "Delete".
7. Save your changes and rebuild your project.

Should work after that, it might be because they have changed for ios.

**Comment by lukasnevosad** [comment]
I have the same issue. I can build and run on any physical device I have both from flutter and Xcode (14.3), but the build fails on any simulator device I tried.

Message from Xcode:
```
/Users/lukasnevosad/Projects/Yomio/scholis/scholis/ios/Runner/GeneratedPluginRegistrant.m:12:9: Module 'audioplayers_darwin' not found
```

Message when building from flutter:
```
Launching lib/main.dart on iPad Pro (12.9-inch) (6th generation) in debug mode...
main.dart:1
Xcode build done.                                            2.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2023-05-29 08:42:23.450 xcodebuild[43714:13960633] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
    		{ id:272FF786-7F03-4103-B72A-504974A814BD }
    	Available destinations for the "prod" scheme:
    		{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-000428101132001E }
    		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/bx/lkj2g27x5491t9zy48cwrslr0000gn/T/flutter_tools.7pqIkG/flutter_ios_build_temp_dirEubjAX/temporary_xcresult_bundle
Could not build the application for the simulator.
Error launching application on iPad Pro (12.9-inch) (6th generation).
Exited
```

Regarding the solutions mentioned above, there is no mention of "audioplayers" in my `project.pbxproj` and `flutter clean` did not work either.
