### ISSUE TITLE
Potential bug in 3.0.1

### ISSUE THREAD

**Issue by Chezlui** [bluefireteam/audioplayers#1463]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Since I am new to Flutter I spent like 2 hours trying to make it work the library without success.

After different tests I noticed that my 3.0.1 version of the library was missing the /lib folder.

![image](https://user-images.githubusercontent.com/4120243/230435784-72403235-2212-418a-9350-8530f51e4762.png)

I'm attaching an image for your convenience. I read some other issue in the repository posted by somebody else, and this could be potentially the reason.

Hope this helps. Excuse me if was just my error.

### Affected platforms

Android

### AudioPlayers Version

3.0.1

### Build mode

debug

### Screenshots

![image](https://user-images.githubusercontent.com/4120243/230436128-98b815dd-6a2a-4acd-9d50-8c28ac938a68.png)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
How did you download the library?

Can you try a `flutter pub clean`.
Also follow the [installing instructions](https://pub.dev/packages/audioplayers/install)

In the release lib fodlers seems to be included.
![image](https://user-images.githubusercontent.com/18537755/230796910-dd78a2fc-757a-4750-9fff-4c4c4a3d1a91.png)

**Comment by Chezlui** [comment]
Sorry @Gustl22 , maybe I was a newbie using Flutter and didn't know how to use it properly.
