### ISSUE TITLE
`Expression: cannot dereference end map/set iterator` on Windows

### ISSUE THREAD

**Issue by Skyost** [bluefireteam/audioplayers#1475]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Audio cannot be played on Windows due to a MVC++ error occuring.

### Expected behaviour

Audio should play without any problem.

### Steps to reproduce

1. Clone the repository and extract the `flame_audio` example project.
2. Run `flutter create .` in order to create the Windows project.
3. `flutter run`.

### Code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:flame/components.dart';
import 'package:flame/extensions.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flame/palette.dart';
import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/widgets.dart' hide Animation;

void main() {
  runApp(GameWidget(game: AudioGame()));
}

/// This example game showcases three possible use cases:
///
/// 1. Use the static FlameAudio class to easily fire a sfx using the default
/// configs for the button tap.
/// 2. Uses a custom AudioPool for extremely efficient audio loading and pooling
/// for tapping elsewhere.
/// 3. Uses the Bgm utility for background music.
class AudioGame extends FlameGame with TapDetector {
  static Paint black = BasicPalette.black.paint();
  static Paint gray = const PaletteEntry(Color(0xFFCCCCCC)).paint();
  static TextPaint text = TextPaint(
    style: TextStyle(color: BasicPalette.white.color),
  );

  late AudioPool pool;

  @override
  Future<void> onLoad() async {
    pool = await FlameAudio.createPool(
      'sfx/fire_2.mp3',
      minPlayers: 3,
      maxPlayers: 4,
    );
    startBgmMusic();
  }

  Rect get button => Rect.fromLTWH(20, size.y - 300, size.x - 40, 200);

  void startBgmMusic() {
    FlameAudio.bgm.initialize();
    FlameAudio.bgm.play('music/bg_music.ogg');
  }

  void fireOne() {
    FlameAudio.play('sfx/fire_1.mp3');
  }

  void fireTwo() {
    pool.start();
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    canvas.drawRect(size.toRect(), black);

    text.render(
      canvas,
      '(click anywhere for 1)',
      Vector2(size.x / 2, 200),
      anchor: Anchor.topCenter,
    );

    canvas.drawRect(button, gray);

    text.render(
      canvas,
      'click here for 2',
      Vector2(size.x / 2, size.y - 200),
      anchor: Anchor.bottomCenter,
    );
  }

  @override
  void onTapDown(TapDownInfo info) {
    if (button.containsPoint(info.eventPosition.game)) {
      fireTwo();
    } else {
      fireOne();
    }
  }
}
```

</details>

(as you can see, it's the sample project of `flame_audio`, which is available [here](https://github.com/flame-engine/flame/tree/main/packages/flame_audio/example)).

### Affected platforms

Windows

### Platform details

**Processor :** AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
**RAM :**	16,0 Go (15,3 Go usable)
**Edition :**	Windows 11 Famille
**Version :**	22H2
**Installed on :** ‎05/‎10/‎2022
**OS Build :**	22621.1555
**Experience :**	Windows Feature Experience Pack 1000.22640.1000.0

### AudioPlayers Version

4.0.1

### Build mode

debug

### Audio Files/URLs/Sources

[`bg_music.ogg`](https://github.com/flame-engine/flame/blob/main/packages/flame_audio/example/assets/audio/music/bg_music.ogg)

### Screenshots

![2023-04-17_12-36](https://user-images.githubusercontent.com/3882599/232467111-dad63a4b-df07-43a8-bef3-2497d9794e19.png)

### Logs

No log as it's a native error. See screenshot above.

### Working on PR

Why not, but I have no C++ experience.

**Comment by Gustl22** [comment]
Good catch @Skyost. The following happens: Dispose is called on [bgm in FlameAudio](https://github.com/flame-engine/flame/blob/a25b0a03a56975e1de2e15747bc3e527ac232545/packages/flame_audio/lib/bgm.dart#L56), which should not be the case as it makes the player obsolete, should be replaced with  `release()` (cc @spydon).

But it should also be tested and fixed in AP, as a player could be disposed, without ever playing any source.

#1450 
#1478 

Further .ogg is not supported by Windows, but that was not the problem for crashing here :)

**Comment by Skyost** [comment]
Good ! Can I close this one @Gustl22 ?

**Comment by Gustl22** [comment]
I'll close, when #1480 is merged ;)
