### ISSUE TITLE
AudioPool dispose() method

### ISSUE THREAD

**Issue by fuckgithubanyway** [bluefireteam/audioplayers#1478]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

The `AudioPool` class does not have a `dispose` method.

### Proposal / Solution

It seems that you need to call the `dispose` method on each thread, synchronizing with the `_lock` field.

### Affected platforms

Linux

### Platform details

In Linux, this leads to an uncontrolled multiplication of playback streams.

### Working on PR

yeah

**Comment by Gustl22** [comment]
Sounds like a very good addition! Feel free to open a Merge request!

**Comment by fuckgithubanyway** [comment]
Unfortunately, I do not have sufficient competencies to solve such a problem.
I really tried. ))
