### ISSUE TITLE
onPositionChanged not working correctly on Android device

### ISSUE THREAD

**Issue by Kang-Kim1** [bluefireteam/audioplayers#1484]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I am getting wrong seconds from onPositionChanged after changing the current position through `seek()` method.

For example, once I change the current position from 0.0 to 1.2, onPositionChanged is giving me the seconds in the following sequence : 
1. 1.2
2. 1.0
3. 1.2
4. 1.3 

The same code works fine on iOS devices. Should I handle either seek or onPositionChanged differently on Android device?

Please help.. 🙇🏻‍♂️

**Comment by Gustl22** [comment]
@Kang-Kim1 can you upload your audio sample here as `zip`? #1324
