### ISSUE TITLE
illegal audio focus gain type 0 

### ISSUE THREAD

**Issue by darajay90** [bluefireteam/audioplayers#1485]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

![WhatsApp Image 2023-04-27 at 19 59 02](https://user-images.githubusercontent.com/5908229/234964958-1035c94b-dd72-4d42-ae7f-369261d3bd90.jpeg)

illegal audio focus gain type 0 when going to play the file (from url)

### Expected behaviour

This works on iOS, but for some reason fails on Android. 

### Code sample

<details>
<summary>Code sample</summary>

```dart
  try {
      final value = await CommonApi.getPresignedUrl(widget.answer);

      print("Presigned URL: $value");
      try {
        await player.play(UrlSource(value),
            mode: PlayerMode.lowLatency, ctx: audioContext);

        setState(() {
          loading = false;
          hasLoadedUrl = true;
          playing = true;
        });
      } catch (e) {
        print("Error: $e");
        setState(() {
          extremelyBadErrorHappened = true;
          Util.showAlertDialog(context, "Err1", e.toString(), () {});
        });
      }
    } catch (error) {
      Util.showAlertDialog(context, "Err2", e.toString(), () {});
      print("Error: $error");
      setState(() {
        extremelyBadErrorHappened = true;
      });
    } finally {
      setState(() {
        loading = false;
      });
    }
```

</details>

### Affected platforms

Android

### AudioPlayers Version

4.01 and 3.01

### Build mode

release

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Should be fixed in #1534
