### ISSUE TITLE
Sound does not play through headphones on Android and iOS devices

### ISSUE THREAD

**Issue by MichaelNZ85** [bluefireteam/audioplayers#1486]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I created an app that uses the AudioPlayers class to play a beep every 8 seconds. However, when running on an actual physical device, the sound does not come through the headphones, even if they are connected and the main audio output. I tried both Bluetooth and physical headphones on Android, and Bluetooth headphones on iOS - couldn't get the sound to come through them.

### Expected behaviour

The sound would be played through the headphones, which are the current audio output device.

### Steps to reproduce

1. Create an app that plays a sound. 
2. Run the app on an physical device (either Android or iOS). Make sure headphones are connected and are the current audio output device.
3. Play the sound in the app. You should hear nothing through the headphones (or maybe one initial sound, and then none after)

### Code sample

<details>
<summary>Code sample</summary>

```dart
bool isPlaying = false;
  final player = AudioPlayer();
  AssetSource sound = AssetSource("sounds/beep.wav");

  void _setIsPlaying() {
    setState(() {
      isPlaying = !isPlaying;
    });
  }

  @override
  void initState() {
    Timer timer = Timer.periodic(Duration(seconds: 8), (timer) async {
      if (isPlaying) {
        await player.play(sound);
        print("${DateTime.now()}: Played sound!");
      }
    });
    super.initState();
  }
```

</details>

### Affected platforms

Android, iOS

### Platform details

* iPhone XR, iOS 16.0 (20A362)
* Huawei Y9 Prime 2019 STK-L22, Android 12.0.0.225(C636E2R2P1)

### AudioPlayers Version

4.0.1

### Logs

Not applicable as the program runs fine on emulators and also on physical devices, just not playing through headphones

### Working on PR

Would be happy to help but am not experienced enough with Dart/Flutter to be able to do this.

**Comment by xxddff** [comment]
I had this problem too, the temporary fix was to set AudioContextIOS(Android devices not yet tested)
```dart
iOS: AudioContextIOS(
         category: AVAudioSessionCategory.playback,
         options: [
           AVAudioSessionOptions.mixWithOthers,
          //AVAudioSessionOptions.defaultToSpeaker,  Unable to set this, will result in forced use of the speaker, the headset is invalid
         ],
       ),
```
Might be related to this question #1194
The outcome of this discussion seems to be that defaultToSpeaker must be set in order for sound to be played on the speaker. But the current test results on iOS show that even if defaultToSpeaker is not set, the sound can be played from the speaker normally, and it can be connected to the headset to play

**Comment by LeoSandbox** [comment]
Hi all - is there any update on this issue?
