### ISSUE TITLE
UrlSource with Headers Problem

### ISSUE THREAD

**Issue by cnkygmr** [bluefireteam/audioplayers#1488]
### Checklist

- [ ] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

I want to be able to send headers while adding UrlSource because the url I want to reach does not allow access without header?

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS

### Working on PR

no way

**Comment by Gustl22** [comment]
See pinned issue: #129
