### ISSUE TITLE
Documentation for AudioContextConfig.respectSilence is backwards?

### ISSUE THREAD

**Issue by wujek-srujek** [bluefireteam/audioplayers#1490]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

The docs for `respectSilence` at https://github.com/bluefireteam/audioplayers/blob/6cd5656c0c5deaab1fb4af78a5b7632402c3a1d3/packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart#L47-L48 sound backwards: the property named `respectSilence`, whose default value is `false` (i.e. it DOES NOT respect silence) should result in the audio being played even in silent mode of the device; the docs state the contrary.
Or maybe the property name is incorrect?

### Working on PR

yeah (if it means updating the docs)

**Comment by Gustl22** [comment]
Yes I think the explanation is a bit confusing, see also the test description: https://github.com/bluefireteam/audioplayers/blob/6cd5656c0c5deaab1fb4af78a5b7632402c3a1d3/packages/audioplayers/example/integration_test/lib_test.dart#L117

Maybe sth like this (?)
```
By default (false), means the audio will be played, even if is on silent mode.

If enabled and the device is on silent mode, the audio will not be played:
```

**Comment by wujek-srujek** [comment]
Yes, this makes perfect sense to me now. Should I create a PR or are you on it already? (I suppose that you fixing the docs will be much less work than you reviewing the PR by my?)

**Comment by Gustl22** [comment]
Just go on, we love Merge requests from the community :)
