### ISSUE TITLE
feat: better error description for unsupported file formats

### ISSUE THREAD

**Issue by Gustl22** [bluefireteam/audioplayers#1494]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Many bug reports describing an error, and the code is not working. But it's not the fault of the library per se.
The file format / codec is just not supported on that platform.

### Proposal / Solution

- Unify the error message for all platforms
- Link to trouble shooting guide: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md
- Ask questions in the message:
  - Does the platform support this file format?
  - Is the file corrupt or empty?
  - Do you use the correct path, e.g. remove `asset/` for `AssetSource`?
  - Web only: How to handle CORS errors correctly
  - Darwin: test white space in url
- network issue
- a malformed URL
- a missing permission in the app manifest

### Example Code

<details>
<summary>Example Code</summary>

Catch and throw the relevant errors on their native platform.

</details>

### Affected platforms

other

### Related issues / more information

Web:
#1427
#1437
#1327

Darwin:
#1210
#1430
#1473

#748
#972
#1621
#1546

#803 is related, but not yet solved, as it needs a parameter on the native side for the meme type.

### Working on PR

not yet

**Comment by Mamong** [comment]
Though iOS AVPlayer supports .wav file, but it still will fail to play remote wav when "content-type" is set to 'audio/mpeg', while 'audio/x-wav' is the correct one. So downloading and caching tiny audio files will solve many problems like these.

**Comment by Gustl22** [comment]
@Mamong it may depends on the file extension inside the url. If it has non, the mime type has to be handed over, which is not supported yet.
https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#ios-macos-urls-or-paths-without-a-file-extension
https://github.com/bluefireteam/audioplayers/issues/803#issuecomment-1738066829
