### ISSUE TITLE
Make it possible to set AudioContext on only 1 platform

### ISSUE THREAD

**Issue by wujek-srujek** [bluefireteam/audioplayers#1497]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Context: my application will be used mostly when the phone is playing music in the background (with Spotify etc.) and then it will play short sounds on top of it every now and then. Due to various inconsistencies and bugs (I think?) I had to settle on the following: my app playing sounds will not interrupt/pause the background music (this is a hard requirement) and it will also not duck the background music either (because I couldn't get it to work correctly on iOS, see https://github.com/bluefireteam/audioplayers/issues/1496). However, for this to work, I must not set any `AudioContext` on Android (see https://github.com/bluefireteam/audioplayers/issues/1495).

As a result, my current code looks like this:
```dart
if (Platform.isIOS) {
  await AudioPlayer.global.setAudioContext(
    const AudioContext(
      iOS: AudioContextIOS(
        // ignore: avoid_redundant_argument_values
        category: AVAudioSessionCategory.playback,
        options: [
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
    ),
  );
}
```
Which means that even though Android and iOS have separate settings, it is impossible to set the context on only one platform (in my case, I don't want to set any context on Android, so I need to check the platform and do it only if running on iOS).

BTW, not setting any `AudioContext` ever is not an option either, because then iOS has strange artifacts when my audio starts playing the first time, and when my app is killed / moved to background.

### Proposal / Solution

One option would be to make the `AudioContext` properties `android` and `iOS` to be nullable, so that the code can be written like this:
```dart
await AudioPlayer.global.setAudioContext(
  const AudioContext(
    android: null,
    iOS: AudioContextIOS(
      // ignore: avoid_redundant_argument_values
      category: AVAudioSessionCategory.playback,
      options: [
        AVAudioSessionOptions.mixWithOthers,
      ],
    ),
  ),
);
```
Of course, code receiving this must be then null-safe and just do nothing if running on a platform that has `null` context.

Another option, or if you don't want/like nullability, would be to make sure that the default contexts per platform (as created using their respective default constructors `AudioContextIOS()` and `AudioContextAndroid()`) behave exactly as if no context were set at all. This is currently not the case, as can be seen e.g. in https://github.com/bluefireteam/audioplayers/issues/1495 for Android, or the fact that it sets `forceSpeaker` to `true`, which even makes the default `AudioContextIOS()` instance unusable as can be seen in https://github.com/bluefireteam/audioplayers/issues/1491.

Again, the API limitation only occurred to me because of other issues, which may make it irrelevant if they are fixed. At the same time, I still think it would be nice to have the option.

### Affected platforms

Android, iOS

### Working on PR

no way

**Comment by Gustl22** [comment]
I would not recommend to be able to set only one platform, as it just hides the other issues. Instead all default values should act like the initial native values, their differences should be fixed.

**Comment by wujek-srujek** [comment]
That would be fine. But I noticed you closed this ticket, is there another one, which tackles making the defaults behave correctly?

**Comment by Gustl22** [comment]
I think #1495 should tackle the wrong default value (?)

**Comment by wujek-srujek** [comment]
Sure, if it is possible to have the default AudioContext to behave just like if none is ever set, sure, that would work as well.

**Comment by Gustl22** [comment]
That would be the expected behavior I guess :)
