### ISSUE TITLE
bytes of mp3 file is not played. 

### ISSUE THREAD

**Issue by kotran88** [bluefireteam/audioplayers#1502]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I have list of byte of mp3 that saying hello 

List<int> mp3Bytes = [
        255,
        251,
        48,
        13,
        0,
        0,
        0,
        0,
        0,
        35,
        84,
        83,
        83,
        69,
        0,
        0,
        0,
        15,
        0,
        0,
        3,
        76,
        97,
        118,
        102,
        53,
        56,
        46,
        50,
        57,
        46,
        49,
        48,
        48,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        255,
        243,
        112,
        192,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        73,
        110,
        102,
        111,
        0,
        0,
        0,
        15,
        0,
        0,
        0,
        38,
        0,
        0,
        16,
        57,
        0,
        17,
        17,
        24,
        24,
        24,
        30,
        30,
        36,
        36,
        36,
        43,
        43,
        43,
        49,
        49,
        56,
        56,
        56,
        62,
        62,
        62,
        69,
        69,
        75,
        75,
        75,
        82,
        82,
        88,
        88,
        88,
        94,
        94,
        94,
        101,
        101,
        107,
        107,
        107,
        114,
        114,
        114,
        120,
        120,
        127,
        127,
        127,
        133,
        133,
        140,
        140,
        140,
        146,
        146,
        146,
        152,
        152,
        159,
        159,
        159,
        165,
        165,
        165,
        172,
        172,
        178,
        178,
        178,
        185,
        185,
        185,
        191,
        191,
        197,
        197,
        197,
        204,
        204,
        210,
        210,
        210,
        217,
        217,
        217,
        223,
        223,
        230,
        230,
        230,
        236,
        236,
        236,
        243,
        243,
        249,
        249,
        249,
        255,
        255,
        0,
        0,
        0,
        0,
        76,
        97,
        118,
        99,
        53,
        56,
        46,
        53,
        52,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        36,
        4,
        72,
        0,
        0,
        0,
        0,
        0,
        0,
        16,
        57,
        133,
        94,
        77,
        249,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        255,
        243,
        64,
        196,
        0,
        17,
        104,
        50,
        0,
        8,
        121,
        134,
        0,
        136,
        176,
        54,
        171,
        192,
        100,
        237,
        221,
        192
      ];

Uint8List mp3Bytes2 =
          Uint8List.fromList(mp3Bytes); // your byte array here

      await audioPlayer.playBytes(mp3Bytes2);

I tried to play it but it won't happend anything. 
seems like they cause error of below. 

How can I play it...? 
pubspec.yaml 

  audioplayers: ^0.20.1
```


V/MediaPlayerNative(21779): message received msg=100, ext1=1, ext2=-2147483648
E/MediaPlayerNative(21779): error (1, -2147483648)
E/MediaPlayer(21779): Error (1,-2147483648)
```

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

0.20.1

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
We don't support older Audio Player versions. Update to > v1.x.x

**Comment by kotran88** [comment]
so you mean I should have audioplayer more new version ? 
I upgraded to 
  audioplayers: ^4.0.1
 but in this version there is no playBytes defined T_T
 The method 'playBytes' isn't defined for the type 'AudioPlayer'.

**Comment by Gustl22** [comment]
Please read the [getting started guide](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#sources).
