### ISSUE TITLE
Potential creating an instance bug in 4.0.1

### ISSUE THREAD

**Issue by Mike-3** [bluefireteam/audioplayers#1508]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When running tests for the audio player, I get an exception when creating an instance.
`var advancedPlayer = Audio.AudioPlayer();`

### Expected behaviour

This was not the case in version 3.0.
With
TestWidgetsFlutterBinding.ensureInitialized();
I was able to handle it first.
But we try not to implement flutter stuff in the logic part.
Maybe that can be changed.

### Steps to reproduce

Creating an instance in a test

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### Platform details

Platform: Android 10, (API 29) Android Emulator

### AudioPlayers Version

main 4.0.1

### Build mode

debug

### Logs

```
===== asynchronous gap ===========================
dart:async                                                                          _CustomZone.registerBinaryCallback
package:audioplayers/src/audioplayer.dart 144:7                                     AudioPlayer._create
package:audioplayers/src/audioplayer.dart 139:5                                     new AudioPlayer
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2913], locale de-DE)
    • Flutter version 3.10.0 on channel stable at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0        
    • DevTools version 2.23.1   

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at C:\Users\bim\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0-rc1
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[!] Android Studio
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X android-studio-dir = /usr/local/android-studio
    X Android Studio not found at /usr/local/android-studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2913]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.68

[!] Network resources
    X A cryptographic error occurred while checking "https://github.com/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.

! Doctor found issues in 2 categories.
PS D:\tmp\GitHub\GCWizard> 

  ```
</details>

### Working on PR

yeah

**Comment by Gustl22** [comment]
Can you provide the full logs on executing and the exact test command. Also the the exact code of your test? Thank you ;D

**Comment by Mike-3** [comment]
test code

```
import 'package:flutter_test/flutter_test.dart';
import 'package:audioplayers/audioplayers.dart' as Audio;

void main() {
  //TestWidgetsFlutterBinding.ensureInitialized();

  group("audioplayers.test:", () {
    List<Map<String, Object?>> _inputsToExpected = [

      {'input' : ''},
    ];

    for (var elem in _inputsToExpected) {
      test('input: ${elem['input']}', () async {
        var advancedPlayer = Audio.AudioPlayer();
      });
    }
  });
}
```

exception log:

package:flutter/src/foundation/binding.dart 302:9                               BindingBase.checkInstance.<fn>
package:flutter/src/foundation/binding.dart 383:6                               BindingBase.checkInstance
package:flutter/src/services/binding.dart 55:54                                 ServicesBinding.instance
package:flutter/src/services/platform_channel.dart 136:25                       _findBinaryMessenger
package:flutter/src/services/platform_channel.dart 269:56                       MethodChannel.binaryMessenger
package:flutter/src/services/platform_channel.dart 303:15                       MethodChannel._invokeMethod
package:flutter/src/services/platform_channel.dart 483:12                       MethodChannel.invokeMethod
package:audioplayers_platform_interface/src/method_channel_extension.dart 5:12  StandardMethodChannel.call
package:audioplayers_platform_interface/src/audioplayers_platform.dart 200:27   MethodChannelAudioplayersPlatform._call
package:audioplayers_platform_interface/src/audioplayers_platform.dart 27:12    MethodChannelAudioplayersPlatform.create
package:audioplayers/src/audioplayer.dart 144:23                                AudioPlayer._create
package:audioplayers/src/audioplayer.dart 139:5                                 new AudioPlayer
test\tools\audioPlayer_test.dart 15:36       main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                                      _CustomZone.registerBinaryCallback
package:audioplayers/src/audioplayer.dart 144:7                                 AudioPlayer._create
package:audioplayers/src/audioplayer.dart 139:5                                 new AudioPlayer
test\tools\images_and_files\hidden_data\logic\audioPlayer_test.dart 15:36       main.<fn>.<fn>

Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.

**Comment by Gustl22** [comment]
You have to use `IntegrationTestWidgetsFlutterBinding.ensureInitialized();'` on the native tests.

**Comment by Mike-3** [comment]
With this adjustment it works as already written above.
But normally, I don't want to have to make extra adjustments for tests.
But if there is no other way, I can live with it.
