### ISSUE TITLE
how to use default device speaker in audio player

### ISSUE THREAD

**Issue by sifatullahshah1** [bluefireteam/audioplayers#1509]
i am using audioplayers library the main issue i have faced is when i play audio it use microphone for sound by default but if one the same screen with video audioplayer user speaker of the device 

i am new try a lot but dont find solution for default speaker using plz help

**Comment by sifatullahshah1** [comment]
i have use this all and every things is ok the main issues on ios operating system audio by default play in mircrophone not by device speaker i have try a lot dont find any solution 
plz brother if you explain in simple way i will be very thank full to you

**Comment by Gustl22** [comment]
Set the AudioContext, see #1194 but this should already be fixed with AudioPlayers `v4.0.1`. Plz provide a proper issue, we cannot help otherwise.

**Comment by sifatullahshah1** [comment]
Thanks so much brother issue solved by putting this code
 final position = Duration(seconds: value.toInt());
      final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
          category: AVAudioSessionCategory.ambient,
          options: [
            AVAudioSessionOptions.defaultToSpeaker,
            AVAudioSessionOptions.mixWithOthers,
          ],
        ),
        android: AudioContextAndroid(
          isSpeakerphoneOn: true,
          stayAwake: true,
          contentType: AndroidContentType.sonification,
          usageType: AndroidUsageType.assistanceSonification,
          audioFocus: AndroidAudioFocus.none,
        ),
      );
      AudioPlayer.global.setGlobalAudioContext(audioContext);
