### ISSUE TITLE
option to disable logging

### ISSUE THREAD

**Issue by shawn736** [bluefireteam/audioplayers#151]
Please don't use NSLog in iOS to print information,  or a switch is needed.  For example :
`NSLog(@"iOS => call %@, playerId %@", call.method, playerId);`

**Comment by luanpotter** [comment]
I think we should remove all logs from both android and ios, there used to be an issue about that. We'd be glad if you could contribute with a PR, @shawn736 .

**Comment by luanpotter** [comment]
I think the `disableLogs` dart method should notify both backends via a channel to stop all logs. Then on ios introduce an if statement in the log function (just like that dart side does). For android, apart from that, we need to configure the MediaPlayer class to stop with the random logging.

It should be a relatively easy improvement if someone is interested in helping out :)

**Comment by erickzanardo** [comment]
@luanpotter did this got fixed when the refactor to swift was made?

**Comment by luanpotter** [comment]
Not yet, I made a refactor to allow it but didn't wire yet.
