### ISSUE TITLE
AssetSource has prefix 'assets', can I remove it?

### ISSUE THREAD

**Issue by CalsRanna** [bluefireteam/audioplayers#1513]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

I don't want the default prefix of assets, how can I remove or replace it?

### Affected platforms

Linux

### Working on PR

no way

**Comment by Gustl22** [comment]
You can set the default path by overriding the [AudioCache](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#audiocache).
