### ISSUE TITLE
java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by dleurs** [bluefireteam/audioplayers#1519]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

```
gradle wrapper --warning-mode all

> Configure project :audioplayers_android
The Report.destination property has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the outputLocation property instead. See https://docs.gradle.org/8.1.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:destination for more details.
```

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1
Erreur : impossible de trouver ou de charger la classe principale org.gradle.wrapper.GradleWrapperMain
Causé par : java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
Exception: Gradle task assembleProdDebug failed with exit code 1
Exited
```

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

4.0.1

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

yeah

**Comment by Gustl22** [comment]
Maybe was fixed in the mean time. Feel free to reopen, if you encounter this again.

**Comment by Mohamed207470** [comment]
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Erreur : impossible de trouver ou de charger la classe principale org.gradle.wrapper.GradleWrapperMain
 help me please

**Comment by mathis6787** [comment]
> e pleas

I have the same issue did you find a solution ?
