### ISSUE TITLE
(Will PR) Android `WrappedPlayer` has concurrency bugs, since it is called in multiple threads, has shared fields, but without synchronizations

### ISSUE THREAD

**Issue by fzyzcjy** [bluefireteam/audioplayers#1525]
PS. This is similar to https://github.com/bluefireteam/audioplayers/issues/1524, but not the same thing.

By logging, it seems that the various methods of `WrappedPlayer` are called in multiple threads. However, WrappedPlayer has several fields like `playing`, `prepared`, etc, without any protection such as `volatile`, `synchronized` or anything like that. Therefore, the code seems to have bugs related to concurrency.

**Comment by Gustl22** [comment]
Isn't the root cause the same as in #1524 ? What is the difference? You mean like the approach to solve the issue?

**Comment by fzyzcjy** [comment]
Yes and no. 

1. If we enforce WrappedPlayer to be called always using the same thread (say ui thread), then 1524 is also fixed.
2. If we only fix 1524, but still let WrappedPlayer functions be run on multi threads, then even if MediaPlayer is happy, *this* class (WrappedPlayer) will still be buggy

**Comment by Gustl22** [comment]
So we should solve this issue then instead of #1524. No need to fix a bug the "wrong" or not good enough way.

**Comment by Gustl22** [comment]
Maybe it's worth waiting for #1526
