### ISSUE TITLE
No signature of method: build_94oy9ugmmdre65zz0r3epqa6x.android()

### ISSUE THREAD

**Issue by HAFIZkhan-source** [bluefireteam/audioplayers#1531]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\AppData\Local\Pub\Cache\hosted\pub.dev\audioplayers_android-3.0.2\android\build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':audioplayers_android'.
> No signature of method: build_94oy9ugmmdre65zz0r3epqa6x.android() is applicable for argument types: (build_94oy9ugmmdre65zz0r3epqa6x$_run_closure2) values: [build_94oy9ugmmdre65zz0r3epqa6x$_run_closure2@2098c40]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

### Steps to reproduce

1. use the flutter version 3.7.12
2. add the latest audio players package in pubspec.yaml
3. run the project in android with debug mode

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### Platform details

Android os 13 (API 33)

### AudioPlayers Version

4.1.0

### Build mode

debug

### Screenshots

![image](https://github.com/bluefireteam/audioplayers/assets/53444341/f6acdbea-4176-48bc-beee-373a041549d5)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by jithware** [comment]
Seeing the same error:

```
Launching lib/main.dart on ***** in debug mode...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/*****/.pub-cache/hosted/pub.dev/audioplayers_android-3.0.2/android/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':audioplayers_android'.
> No signature of method: build_crppnf396tf2qe99jttdjhl8w.android() is applicable for argument types: (build_crppnf396tf2qe99jttdjhl8w$_run_closure2) values: [build_crppnf396tf2qe99jttdjhl8w$_run_closure2@47f1b015]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

```
flutter --version
Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (4 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
```

**Comment by jithware** [comment]
@HAFIZkhan-source it appears to have been fixed for me by updating my ```android/build.gradle``` with:

```
...
ext.kotlin_version = '1.8.21'
...
classpath 'com.android.tools.build:gradle:7.3.0'
...
```

And ```android/gradle/wrapper/gradle-wrapper.properties``` with:

```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
...
```

**Comment by Gustl22** [comment]
@HAFIZkhan-source have you tried the solution of @jithware ?
