### ISSUE TITLE
[Windows] File is never closed

### ISSUE THREAD

**Issue by llfbandit** [bluefireteam/audioplayers#1537]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When player has been disposed after playing a file, the input is still open.

### Expected behaviour

File closed to not leak resources and be able to manipulate it.

### Steps to reproduce

1. play an input file.
2. dispose the player.

### Affected platforms

Windows

### Platform details

Windows 11

### AudioPlayers Version

4.1.0

### Build mode

debug, release

### Logs

```
HRESULT_FROM_WIN32(ERROR_SHARING_VIOLATION) : Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. 
```

### Related issues / more information

As far as I can tell regarding the code, the source is not released.
As `IMFMediaSource` is COM object, `Release()` should be called before setting the pointer to a null reference.

Maybe I'm wrong on the issue location:
https://github.com/bluefireteam/audioplayers/blob/92995357c4e29d63537d66f478dca8f655e99a08/packages/audioplayers_windows/windows/MediaEngineExtension.cpp#LL104C9-L104C25

For what it's worth I use those wrappers to release COM objects:
```cpp
//////////////////////////////////////////////////////////////////////////
//  COM Safe release
//////////////////////////////////////////////////////////////////////////

template <class T> void SafeRelease(T** ppT)
{
	if (*ppT)
	{
		(*ppT)->Release();
		*ppT = NULL;
	}
}

template <class T> inline void SafeRelease(T*& pT)
{
	if (pT != NULL)
	{
		pT->Release();
		pT = NULL;
	}
}
```

### Working on PR

no way

**Comment by Gustl22** [comment]
May needs to be fixed in #1517
