### ISSUE TITLE
Support http ^1.0.0 and file ^7.0.0

### ISSUE THREAD

**Issue by yangfanyu** [bluefireteam/audioplayers#1541]
### Checklist

- [x] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

First of all, thanks for this library,

 but the library currently does not support http^1.0.0 and file^7.0.0,

 can you upgrade it.

### Affected platforms

Android, iOS, web, Windows, Linux, macOS, other

### Working on PR

no way

**Comment by behzadbehnami** [comment]
Because audioplayers >=3.0.1 depends on http ^0.13.5 and .... depends on http ^1.0.0, audioplayers >=3.0.1 is forbidden.
So, because ....... depends on audioplayers ^4.1.0, version solving failed.
