### ISSUE TITLE
Issue with Playing .WAV URL Files, Only MP3 Extension Files Work

### ISSUE THREAD

**Issue by rajaarav0** [bluefireteam/audioplayers#1542]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I have noticed that when I use a URL for an MP3 file, it works properly. However, when I try to use a URL for a WAV file, it doesn't work as expected.
```
  void previewAudio({required String audioUrl}) async {
    _previewAudioPlayer.play(UrlSource(audioUrl));
  }
```

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS

### AudioPlayers Version

  audioplayers: ^4.1.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
You have to be more precise. What exactly doesn't work? Does it even play wav, or is it stuttering. What is the url?
Wav works on all platforms in our tests ;D

**Comment by rajaarav0** [comment]
I have two files in my database, one with an mp3 extension and one with a wav extension. When I play the mp3 file, it plays the URL audio, but it doesn't play wav files.

Example of the url:
Mp3: 
https://firebasestorage.googleapis.com/v0/b/chanter-761bc.appspot.com/o/mindfulness-relaxation-amp-meditation-music-22174.mp3?alt=media&token=0cfb178d-7510-45a1-8647-bb6e7d673c77&_gl=1*1fy64rg*_ga*MzYzMDgzODU3LjE2NjM2ODIwMDE.*_ga_CW55HF8NVT*MTY4NjU0ODg2Mi44MS4xLjE2ODY1NDkzNzkuMC4wLjA.

Wav:
https://firebasestorage.googleapis.com/v0/b/chanter-761bc.appspot.com/o/Audios%2FMeditation%20and%20Peace%2FCalm%2FBryan%2FCalmness%20flows%20through.wav?alt=media&token=10782fd9-e0c1-4680-b385-60aa5adc443d&_gl=1*e3c4es*_ga*MzYzMDgzODU3LjE2NjM2ODIwMDE.*_ga_CW55HF8NVT*MTY4NjU0ODg2Mi44MS4xLjE2ODY1NDkyMzYuMC4wLjA.

**Comment by Gustl22** [comment]
In your issue description you also mentioned Android. I can play both files on Android and Linux. Can't test for iOS though, as I don't have a device. Plz reevaluate your observation.

**Comment by rajaarav0** [comment]
> In your issue description you also mentioned Android. I can play both files on Android and Linux. Can't test for iOS though, as I don't have a device. Plz reevaluate your observation.

Apologies for the confusion in my previous message. Upon further investigation, I realized that the issue I mentioned is specific to iOS, not Android. I have verified that the functionality is working fine on Android devices. However, I have observed that the WAV format URL file links do not work as expected on iOS devices.

Please consider this update regarding the issue and its platform-specific nature. If there are any further steps or instructions you would like me to follow or provide, please let me know. Thank you for your understanding.

**Comment by Gustl22** [comment]
@rajaarav0 Sorry, this may take a while. We don't have native ios devices to test this, nor I have a mac. So right now I can't figure out, what may causing the issue. But feel free to give us any more hints or try debugging the issue by yourself, if you feel comfortable :)

**Comment by rajaarav0** [comment]
> Sorry, this may take a while. We don't have native ios devices to test this, nor I have a mac. So right now I can't figure out, what may causing the issue. But feel free to give us any more hints or try debugging the issue by yourself, if you feel comfortable :)

Thank you for your response. I understand the limitations. I will try to debug the issue on my own and provide any helpful information. If there are any updates or hints, please let me know. Btw your package is very good.

**Comment by rajaarav0** [comment]
Hello, The WAV files do play, but it takes longer time and at least two taps to play the audio.
