### ISSUE TITLE
iOS Play out of earpiece only

### ISSUE THREAD

**Issue by RedHappyLlama** [bluefireteam/audioplayers#1545]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Using AudioContextIOS, I can't seem to find a combinations of a category and options to play audio out of the earpiece speaker only, i.e. On a call. I can't currently test on Android but it seems this is possible baed on https://github.com/bluefireteam/audioplayers/issues/1401 from @dariocavada.

Is this at all possible on   audioplayers: ^4.1.0? It was possible on  audioplayers: ^0.20.1

Thanks!

### Proposal / Solution

AudioContextIOS that allows audio to played from just the earpiece speaker. 

### Affected platforms

iOS

### Working on PR

no way

**Comment by Gustl22** [comment]
I cannot test, as I don't have a real device but this should do the trick:

```
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      iOS: AudioContextIOS(
        category: AVAudioSessionCategory.playAndRecord,
        options: const [
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
    ),
  );
```

Maybe you can also tell me, if there's a difference to:
```
```
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      iOS: AudioContextIOS(
        category: AVAudioSessionCategory.playback,
        options: const [
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
    ),
  );
```
```

**Comment by Gustl22** [comment]
@RedHappyLlama did you succeed?

**Comment by RedHappyLlama** [comment]
@Gustl22, yes, thanks very much for your help! Sorry for the late reply! 

The first bit of code worked, the second did not work.

**Comment by Gustl22** [comment]
@RedHappyLlama Thank you, that helped a lot ;D

**Comment by sagar-esmagico** [comment]
> I cannot test, as I don't have a real device but this should do the trick:
> 
> ```
>   AudioPlayer.global.setGlobalAudioContext(
>     AudioContext(
>       iOS: AudioContextIOS(
>         category: AVAudioSessionCategory.playAndRecord,
>         options: const [
>           AVAudioSessionOptions.mixWithOthers,
>         ],
>       ),
>     ),
>   );
> ```
> 
> Maybe you can also tell me, if there's a difference to:
> 
> ```
>   AudioPlayer.global.setGlobalAudioContext(
>     AudioContext(
>       iOS: AudioContextIOS(
>         category: AVAudioSessionCategory.playback,
>         options: const [
>           AVAudioSessionOptions.mixWithOthers,
>         ],
>       ),
>     ),
>   );
> ```
> 
> There could also be a different behavior, if headphones are connected...

This solution works for me thanks.!
