### ISSUE TITLE
The audioplayers plugin for Windows has an issue related to audio seeking precision

### ISSUE THREAD

**Issue by SNNafi** [bluefireteam/audioplayers#1547]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

The audioplayers plugin for Windows has an issue related to audio seeking precision, where it is limited to seconds instead of milliseconds. This limitation prevents users from accurately seeking to specific points within an audio file, leading to imprecise playback control and usability issues.
Steps to Reproduce:
Install the Audioplayers plugin in a Windows environment.
Load an audio file using the plugin.
Attempt to seek to a specific point within the audio file using milliseconds (e.g., 1570 milliseconds).

### Expected behaviour

The audio playback should accurately seek to the specified millisecond point within the audio file, allowing precise control over playback position.

### Steps to reproduce

`audioPlayer = AudioPlayer(); audioPlayer.seek(Duration(milliseconds: 1560));`

It works perfectly on other platforms. Tested in Android, iOS, and macOS. But in Windows, it doesn't seek to exact 1560

### Code sample

audioPlayer = AudioPlayer(); audioPlayer.seek(Duration(milliseconds: 1560));

### Affected platforms

Windows

### Platform details

N/A

### AudioPlayers Version

main

### Build mode

debug, profile, release

### Audio Files/URLs/Sources

N/A

### Screenshots

N/A

### Logs

N/A

### Related issues / more information

N/A

### Working on PR

yeah

**Comment by Gustl22** [comment]
Hi @SNNafi I added this test, and I could not reproduce the precision issue:

```dart
    testWidgets('#seek with millisecond precision', (tester) async {
      final platform = AudioplayersPlatformInterface.instance;

      final playerId = 'somePlayerId';
      await platform.create(playerId);

      final preparedCompleter = Completer<void>();
      final eventStream = platform.getEventStream(playerId);
      final onPreparedSub = eventStream
          .where((event) => event.eventType == AudioEventType.prepared)
          .map((event) => event.isPrepared!)
          .listen(
            (isPrepared) {
          if (isPrepared) {
            preparedCompleter.complete();
          }
        },
        onError: preparedCompleter.completeError,
      );
      await platform.setSourceUrl(
        playerId,
        'https://luan.xyz/files/audio/ambient_c_motion.mp3',
      );
      await preparedCompleter.future.timeout(const Duration(seconds: 30));

      final seekCompleter = Completer<void>();
      final onSeekSub = eventStream
          .where((event) => event.eventType == AudioEventType.seekComplete)
          .listen(
            (_) {
              seekCompleter.complete();
        },
        onError: seekCompleter.completeError,
      );
      await platform.seek(playerId, const Duration(milliseconds: 1560));
      await seekCompleter.future.timeout(const Duration(seconds: 30));
      await onSeekSub.cancel();
      expect(await platform.getCurrentPosition(playerId), 1560);
      
      await onPreparedSub.cancel();
      await platform.dispose(playerId);
    });
```
