### ISSUE TITLE
When getting build for Flutter web " Uncaught MissingPluginException(No implementation found for method create on channel xyz.luan/audioplayers)" this error occurs

### ISSUE THREAD

**Issue by frkn-erkl** [bluefireteam/audioplayers#1550]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When getting build for Flutter web " Uncaught MissingPluginException(No implementation found for method create on channel xyz.luan/audioplayers)" this error occurs. Normally running 'flutter run' in Chrome does not raise an error. Audio files are not played if served after 'flutter build web' is done. 'AudioEncoder.opus' is used to encode the audio file used.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### AudioPlayers Version

4.1.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by kashiflab** [comment]
@frkn-erkl did you find any solution? I am stuck

**Comment by Gustl22** [comment]
Did you try a `flutter clean` before `flutter pub get` and then `flutter build web`?

**Comment by Shubham-VE** [comment]
I was facing this issue only in hosting and in debug it was working fine. Using flutter clean, flutter pub get, flutter build and then hosting fixed the issue for me

**Comment by Gustl22** [comment]
I think it's a temporary build problem. Nothing wrong with the lib. So closing it now.

**Comment by berryart** [comment]
Problem still persists after cleaning cache and pulling packages anew on Firebase hosting
```
main.dart.js:5593 Uncaught Error: MissingPluginException(No implementation found for method init on channel xyz.luan/audioplayers.global)
    at Object.e (main.dart.js:3212:19)
    at main.dart.js:62318:15
    at at5.a (main.dart.js:4554:63)
    at at5.$2 (main.dart.js:35112:14)
    at arE.$1 (main.dart.js:35106:21)
    at ape.an_ (main.dart.js:36000:34)
    at ape.Hj (main.dart.js:36003:13)
    at amb.$0 (main.dart.js:35535:11)
    at Object.vx (main.dart.js:4691:40)
    at ah.mD (main.dart.js:35461:3)
```
Any ideas of what else can be done (perhaps some initialization?)
