### ISSUE TITLE
Version 4.1.0 not compatible with http: ^1.1.0

### ISSUE THREAD

**Issue by DanielJaramillo94** [bluefireteam/audioplayers#1554]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

audioplayers version 4.1.0 not compatible with version 1.1.0 of http package.
Error message: 
Because audioplayers >=3.0.1 depends on http ^0.13.5 and example_project depends on http ^1.1.0, audioplayers >=3.0.1 is forbidden. So, because example_project depends on audioplayers ^4.1.0, version solving failed.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS, web, Windows, Linux, macOS

### AudioPlayers Version

4.1.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Plz see #1541, it's not released yet
