### ISSUE TITLE
Upgrading to Dart 3.0.5

### ISSUE THREAD

**Issue by SunnyG12** [bluefireteam/audioplayers#1562]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Upgraded the version of Dart and getting below error
Because audioplayers 4.1.0 depends on http ^0.13.5 and no versions of audioplayers match >4.1.0 <5.0.0, audioplayers ^4.1.0 requires http ^0.13.5.
So, because areno depends on both audioplayers ^4.1.0 and http ^1.1.0, version solving failed.
I am already using http 1.1.0 due to dependency with other plugins.
Seeking resolution or suggestion.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS

### Platform details

Flutter
Android & iOS

### AudioPlayers Version

4.1.0

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by therif** [comment]
please, is there any fix ? or Solution for still use http 1.1.0 (because too many package already required this)

**Comment by Gustl22** [comment]
It's already fixed, but not released. Use this https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#current-development

See #1554

**Comment by securexperts** [comment]
When is it released? I also Really must have compatibility to HTTP 1.x

**Comment by Gustl22** [comment]
As mentioned, you can override dependecies as a workaround. We don't know yet the exact release date, as we have breaking changes and need to validate them. Probably within the next two weeks.

**Comment by Gustl22** [comment]
See #1554
