### ISSUE TITLE
Dependency problem with http version 

### ISSUE THREAD

**Issue by mah454** [bluefireteam/audioplayers#1565]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Please fix this problem . 
this is my current project dependencies : 
dependencies:
```
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.9.31
  http: ^1.1.0
  shared_preferences: ^2.1.1
  wakelock: ^0.6.2
  permission_handler: ^10.2.0
  lottie: ^2.3.2
  audioplayers: ^4.1.0
  protobuf: ^3.0.0
  pointycastle: ^3.7.3
  basic_utils: ^5.6.0
  fixnum: ^1.1.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
```
I try to build android apk : 
```
# flutter clean 
# flutter build apk 
Resolving dependencies... 
Because audioplayers >=3.0.1 depends on http ^0.13.5 and dandelion_client depends on http ^1.1.0, audioplayers >=3.0.1 is forbidden.
So, because dandelion_client depends on audioplayers ^4.1.0, version solving failed.
```
Flutter information : 
```
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (7 weeks ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Affected platforms

Android

### AudioPlayers Version

4.1.0

### Build mode

debug, release

### Working on PR

no way

**Comment by maxstubbersfield** [comment]
I think this issue has already been raised, please see #1554 and #1541.

**Comment by mhamTech** [comment]
They really need to upgrade their dependencies, especially the "**http**" package. Flutter is not allowing me to upgrade any other dependencies because they are using an old version of "**http**" package. Please upgrade it **ASAP**!

**Comment by Bloddwyn** [comment]
I have a similar problem:
```
Because no versions of audioplayers match >4.1.0 <5.0.0 and audioplayers 4.1.0 depends on http ^0.13.5, audioplayers ^4.1.0 requires http ^0.13.5.
And because google_fonts >=4.0.5 depends on http ^1.0.0, audioplayers ^4.1.0 is incompatible with google_fonts >=4.0.5.
So, because basesolutions_flutter depends on both google_fonts ^5.1.0 and audioplayers ^4.1.0, version solving failed.
```

**Comment by tanguy-penfen** [comment]
It should be top priority. It is annoying to not be able to upgrade other packages due to this issue.

**Comment by Gustl22** [comment]
You can always use the top of the edge development of this library, see https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#current-development

But even [Flutter](https://github.com/flutter/flutter/issues/129543) and [Google](https://github.com/google/process.dart/pull/75) have their problems keeping up with dependencies on a different, but similar issue, so our hands were tied.

The release of AP `5.0.0` will be available shortly.
