### ISSUE TITLE
iOS Bug - AVAudioSession

### ISSUE THREAD

**Issue by RedHappyLlama** [bluefireteam/audioplayers#1566]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Hi,

Getting the following issue on iOS. Not sure how to resolve. Audio seems to play correctly and can't see any actual issues. 

[as_client]     AVAudioSession_iOS.mm:2374  Failed to set category, error: -50
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>

### Expected behaviour

No error displayed in logs. 

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

4.1.0

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Mowinski** [comment]
I had similar issues. When I've created AudioPlayer future wont be resolved. It just stuck and nothing happend. 

```
log.info({"message": "Initializing audio service"});
player = AudioPlayer();
log.info({"message": "Done"});
```

There is no additional logs and it happens only on iphone (android works well).

**Comment by pushpendraKh** [comment]
Yeah, we are also having a lot of events generated due to this.

**Comment by Gustl22** [comment]
Closing in favor of #1584
