### ISSUE TITLE
Source Bytes for Windows

### ISSUE THREAD

**Issue by dogukangulyasar** [bluefireteam/audioplayers#1600]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

As discussed in #1269, there is no implementation byte source for Windows. This feature will implement bytes source for Windows for .mp3 formatted files.

### Proposal / Solution

Using byte source in Windows operating system.

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
    final player = AudioPlayer();
    player.play(BytesSource(data)); // which is data is UInt8List type stream.
}
```

</details>

### Affected platforms

Windows

### Platform details

- It should be implemented on Linux/MacOS/Web as well. I will try it when I become available again.
- Should be used platform-specific media player APIs.
- There is no required package or anything else for this implementation.

### Audio Files/URLs/Sources

[example.zip](https://github.com/bluefireteam/audioplayers/files/12327180/example.zip)

### Related issues / more information

#1269 

### Working on PR

yeah

**Comment by dogukangulyasar** [comment]
The code is ready, @Gustl22. If everything looks good for you, please approve this issue to start developing.

**Comment by spydon** [comment]
I assigned you to the issue @dogukangulyasar
