### ISSUE TITLE
Failed to play audio

### ISSUE THREAD

**Issue by lurongshuang** [bluefireteam/audioplayers#1621]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

https://dict.youdao.com/dictvoice?type=0&audio=catastrophe
Failed to play audio

### Expected behaviour

Normal playback

### Steps to reproduce

 
     _audioPlayer = audio_player.AudioPlayer();
  _audioPlayer?.play(audio_player.UrlSource(“https://dict.youdao.com/dictvoice?type=0&audio=catastrophe”));

### Code sample

 
     _audioPlayer = audio_player.AudioPlayer();
  _audioPlayer?.play(audio_player.UrlSource(“https://dict.youdao.com/dictvoice?type=0&audio=catastrophe”));

### Affected platforms

iOS

### Platform details

ios16.11
iphone XR

Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.0.5 • DevTools 2.23.1

### AudioPlayers Version

audioplayers: ^5.1.0

### Build mode

debug

### Audio Files/URLs/Sources

https://dict.youdao.com/dictvoice?type=0&audio=catastrophe

### Logs

flutter: playUrl------https://dict.youdao.com/dictvoice?type=0&audio=catastrophe
flutter: \^[[31mAudioPlayers Exception: AudioPlayerException(
	UrlSource(url: https://dict.youdao.com/dictvoice?type=0&audio=catastrophe), 
	PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)<…>
flutter: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
flutter: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)

### Working on PR

no way

**Comment by SimmaAulakh** [comment]
I am also getting issue while playing Audio from a local path. This is happening only on iOS and I noticed that this has started happening very recently as previously it was working really good.

**Comment by Gustl22** [comment]
@lurongshuang are you sure, it is not #1494 ?

**Comment by Gustl22** [comment]
I think it's actually #803 as no file extension is provided.
