### ISSUE TITLE
Play music in games not responding after playing multiple times

### ISSUE THREAD

**Issue by lenhatquang97** [bluefireteam/audioplayers#1638]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I am making a game and I use game sound (0.3s) to play for the effect. Everytime I swipe this sound plays. However, when I play a bit, my application is not responding. How can I prevent this problem? I try switching to mode lowLatency, however, I cannot play the sound anymore.

### Expected behaviour

I want sound playing smoothly without making the application not responding.

### Code sample

<details>
<summary>Code sample</summary>

```dart
final player = AudioPlayer();

late final AnimationController _moveController = AnimationController(
    duration: const Duration(milliseconds: 100),
    vsync: this,
  )..addStatusListener((status) async {
      await player.play(AssetSource("audio/move_sound.wav"));
      if (status == AnimationStatus.completed) {
        ref.read(boardManager.notifier).merge();
        _scaleController.forward(from: 0.0);
      }
    });

  @override
  void dispose() {
      player.dispose();
      super.dispose();
   } 
```

</details>

### Affected platforms

Android, iOS

### Platform details

* Platform 1: Google Pixel 6a
* Platform 2: iPhone 14 (VM)

### AudioPlayers Version

5.1.0

### Build mode

debug

### Audio Files/URLs/Sources

https://drive.google.com/file/d/1YSMoWGIjmhXxVktR3JzsMtXlKOihapKl/view?usp=sharing

### Logs

```
D/AudioManager(29536): dispatching onAudioFocusChange(-1) to android.media.AudioManager@b3231eexyz.luan.audioplayers.player.FocusManager$$ExternalSyntheticLambda0@e01cb4
D/AudioManager(29536): dispatching onAudioFocusChange(-1) to android.media.AudioManager@b3231eexyz.luan.audioplayers.player.FocusManager$$ExternalSyntheticLambda0@5503587
```

**Comment by Gustl22** [comment]
See https://github.com/bluefireteam/audioplayers/issues/1489#issuecomment-1649668497. I'm closing. If you think this is not the case, feel free to reopen.
