### ISSUE TITLE
Audio doesn't work in windows app after doing build

### ISSUE THREAD

**Issue by Handikadj** [bluefireteam/audioplayers#1639]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I have a problem with the audio section after building an application for Windows, there is no sound after the application is built. but there is no problem when running in the emulator. I use the assets directory for the audio.  I use the 'assets/audio' directory and use Urlsourcecode. if I use Assesource(path) it doesn't work and there is no audio, so I use Urlsource

### Expected behaviour

I need help with the solution so that this audio can appear in the Windows application after building

### Code sample
```
 button(
    onPessed: () async {
      try {
        if (homeC.spinning.value == true) {
          homeC.getdata();
          homeC.spinning.value = false;
          homeC.player.stop(); // STOP THE AUDIO
          await Future.delayed(Duration(milliseconds: 500));
          Get.toNamed(Routes.LIST_WINNERS);
          Get.showSnackbar(const GetSnackBar(
            message: 'Selamat Kepada Para Pemenang',
            duration: Duration(seconds: 3),
          ));
          homeC.player.play(UrlSource('assets/audio/winner.mp3')); // PLAY AUDIO WINNER
          print('audio berhenti');
        } else {
          homeC.drawRandomParticipants();
          homeC.spinning.value = true;
          homeC.player.play(UrlSource('assets/audio/wheel_spin_sound.mp3')); // PLAY AUDIO SPIN
          print('audio berjalan');
        }
      } catch (error, stackTrace) {
        await Sentry.captureException(error, stackTrace: stackTrace);
      }
    },
    title: homeC.spinning.value ? 'Stop' : 'Draw',
    height: 68,
    width: 361,
    color: Colors.white,
  ),
```

### Affected platforms

Windows

### Platform details

windows 11 home 64 bit

### AudioPlayers Version

audioplayers: ^5.1.0

### Build mode

release

### Audio Files/URLs/Sources

homeC.player.play(UrlSource('assets/audio/wheel_spin_sound.mp3')); // PLAY AUDIO SPIN
homeC.player.play(UrlSource('assets/audio/winner.mp3')); // PLAY AUDIO WINNER

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Just call: `player.play(AssetSource('audio/winner.mp3'));`

Or remove the prefix in AudioCache: 
`AudioCache.instance = AudioCache(prefix: '')`

Or better use
`AudioCache.instance = AudioCache(prefix: 'assets/audio/')` and remove the prefix completely when playing the sound.
`player.play(AssetSource('winner.mp3'));`

**Comment by Gustl22** [comment]
Closing due to #1650
