### ISSUE TITLE
AudioPlayer does not complete on Android

### ISSUE THREAD

**Issue by angrycodez** [bluefireteam/audioplayers#1652]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

It seems, that on android, the AudioPlayer is stuck in playing-state.
OnComplete is never triggered.

On Linux, I have no problem with the same code and everything works fine.

### Expected behaviour

I would expect the AudioPlayer to raise onComplete, once the audio playback has finished.

### Steps to reproduce

I don't have time to provide lots of information, but I used a minimal example like in the tutorial/getting started.
If you don't have this problem on Android, it's maybe just me...

### Affected platforms

Android

### Platform details

Android 13

### AudioPlayers Version

5.1

### Build mode

debug, release

### Working on PR

no way

**Comment by Gustl22** [comment]
Do you use lowLatency mode? See: https://github.com/bluefireteam/audioplayers/issues/1489#issuecomment-1649668497

**Comment by angrycodez** [comment]
I did indeed! I think I had the problem as well when switching to the normal mode, but maybe I am wrong, not sure right now.
Weird though, that it works in linux.
But thanks for the reply!!

-------- Original Message --------

**Comment by Gustl22** [comment]
Low Latency mode does not exist on Linux. It falls nack to normal mode. Can have a look at the parity table :)

**Comment by angrycodez** [comment]
ahaaa, that clarifies it a lot! ;) i did take a look at it, but it was a while ago and i didn't check it when i had this problem! well thanks a lot! :)

-------- Original Message --------

**Comment by Gustl22** [comment]
I'll close it then. Feel free to reopen if you still have issues regarding the playback completion.
