### ISSUE TITLE
Module 'audioplayers_darwin' not found

### ISSUE THREAD

**Issue by kevin915** [bluefireteam/audioplayers#1653]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

ios17 
Xcode15
Product-Archive  提示 ..ios/Runner/GeneratedPluginRegistrant.m:12:9: Module 'audioplayers_darwin' not found

尝试了 
flutter clean
pod install等都无用

### Expected behaviour

期待解决

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

audioplayers: 5.1.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
@kevin915 Try to write everything in english, as the community can better help then.

Can you also try  `flutter pub cache clean`?  I don't really know what it is. It works fine on my system and the tests.

**Comment by zzf0805** [comment]
cd the project root directory then run 'pod install'

**Comment by fadihere** [comment]
Please reopen this isssue

**Comment by Gustl22** [comment]
> Please reopen this issue

This is most likely a setup issue. Without additional information, what circumstances led to this error and what already was tried (like `flutter clean` and `cd ios && pod install`) it doesn't make sense to reopen.

**Comment by fadihere** [comment]
> > Please reopen this issue
> 
> This is most likely a setup issue. Without additional information, what circumstances led to this error and providing steps what already was tried (like `flutter clean` and `cd ios && pod install`) it doesn't make sense to reopen.

It did not work for me

**Comment by Gustl22** [comment]
Let's discuss in #1723
