### ISSUE TITLE
an update to readme 

### ISSUE THREAD

**Issue by RensFall** [bluefireteam/audioplayers#1655]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

when i first used your library i countered a problem in playing an audio from my assets , ive looked in ur toturial but it wasnt working , hopefully i understood it right ...
any way i have looked in other places and found the right way to use it , if i misunderstood it sorry but if not i hope that you update you readme  

### Proposal / Solution

in the picture i tried your code but it wasnt working , the other code below it was the working like a charm . 

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### Audio Files/URLs/Sources

![image](https://github.com/bluefireteam/audioplayers/assets/113024893/203375c9-eac4-4ef1-b891-61863958c26b)

### Working on PR

no way

**Comment by Gustl22** [comment]
It depends on what you want. You can either set the source, and then `resume` it.
Or `play` combines these two steps. Not everyone wants to play the source immediately...
See: https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#sources
