### ISSUE TITLE
Audio not working with IOS17 for AssetSource 

### ISSUE THREAD

**Issue by Anasslm** [bluefireteam/audioplayers#1666]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Issue Description:
I have implemented a button in my Flutter app that is intended to trigger a sound play when pressed. However, when I press the button, I do not hear any sound, and an exception is thrown, as shown below:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
<asynchronous suspension>
#2      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:78:27)
<asynchronous suspension>
#3      AudioCache.load (package:audioplayers/src/audio_cache.dart:101:31)
<asynchronous suspension>
#4      AudioPlayer.setSourceAsset (package:audioplayers/src/audioplayer.dart:249:17)
<asynchronous suspension>
#5      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:131:5)
<asynchronous suspension>

### Expected behaviour

I expect to hear the sound when I press the play button.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2.Navigate to the screen with the play button.
3.Press the play button.

### Code sample

`import 'package:english_words/english_words.dart';
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';

void main() => runApp(XylophoneApp());

class XylophoneApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: TextButton(
              onPressed: () {
                final player = AudioPlayer();
                player.play(AssetSource('note1.wav'));
              },
              child: Text("Click Meee"),
            ),
          ),
        ),
      ),
    );
  }
}
`

### Affected platforms

iOS

### Platform details

IOS17

### AudioPlayers Version

5.0.0

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Please read the other issues first. Also please use [code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) to wrap your code:
