### ISSUE TITLE
`setSourceUrl` broken since 5.2.0

### ISSUE THREAD

**Issue by putnokiabel** [bluefireteam/audioplayers#1669]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When calling `audioPlayer.setSourceUrl(url)`, it throws an exception `PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)` on iOS (it throws a different error with the same description on Android as well).

### Expected behaviour

`audioPlayer.setSourceUrl(url)` completes without throwing an error.

### Code sample

<details>
<summary>Code sample</summary>

```dart
Future<void> main() async {
  final audioPlayer = AudioPlayer();
  await audioPlayer.setSourceUrl('https://firebasestorage.googleapis.com/v0/b/obedience-app.appspot.com/o/audio%2F5e31ff82-e6fc-4837-87e3-aadd4b238c08.mp4?alt=media&token=8b849da9-9a92-4378-88b8-19fea933ed44');
}
```

</details>

### Affected platforms

Android, iOS

### AudioPlayers Version

5.2.0

### Build mode

debug, release

### Audio Files/URLs/Sources

https://firebasestorage.googleapis.com/v0/b/obedience-app.appspot.com/o/audio%2F5e31ff82-e6fc-4837-87e3-aadd4b238c08.mp4?alt=media&token=8b849da9-9a92-4378-88b8-19fea933ed44

### Related issues / more information

The exact same code and the same URL are working when I'm using version 5.1.0, the bug only occurs on 5.2.0.

**Comment by putnokiabel** [comment]
Upon looking into the changes between 5.1.0 and 5.2.0 I now see that the plugin URL-encodes the URL provided to `audioPlayer.setSourceUrl(url)` (which is already URL encoded).

This does not seem like the responsibility of the `audioplayers` package to me, IMO it would be better to either:
- just take a string URL and leave it up to the user of the package to encode it as needed (just like in 5.1.0 and before),
- require a `Uri` instead of a `String` so the format of the input URL string is always the same, or
- if for some reason you really want to take a string as an input and encode it, add a check to make sure the URL isn't URL-encoded already.

What do you think?

**Comment by Gustl22** [comment]
@putnokiabel there are many "false" user reports, which have the problem of unencoded url. So it is now encoded by default. To circumvent the problem of encode an already encoded url, it is decoded before. But maybe I missed a case. I'll check next week. Thanks for the report!

**Comment by putnokiabel** [comment]
@Gustl22 I see how the user reports with unencoded urls would be annoying. 
Another alternative (aside from requiring a `Uri` which would circumvent the problem altogether, though it is a breaking change) might be to check whether the URL is encoded, and if not, throw an error describing that the url needs to be encoded (since one might argue that the method throwing an error is the "correct" behavior when the user supplies an incorrect url).
Just a thought!
Thank you for looking into the issue either way! 😄

**Comment by ivanfemia** [comment]
I just started experiencing the same issue today

**Comment by Gustl22** [comment]
I merged a fix for that, but I don't know, when and with what other changes we will release this. Until that you can use the current main branch as follows:
https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#current-development

**Comment by fbarsotti** [comment]
i am facing the same issue: i reopened my project after a few months, i pulled the packages (after already having installed iOS 17), and now the older versions of the package nor the newer one are working properly. i checked the solution used here [https://github.com/bluefireteam/audioplayers/issues/1669](url) and it's not working to me:
<pre>
  AudioPlayer _audioPlayer = AudioPlayer()
    ..setReleaseMode(ReleaseMode.stop)
    ..setAudioContext(
      AudioContext(
        iOS: AudioContextIOS(
          options: [AVAudioSessionOptions.defaultToSpeaker],
        ),
      ),
    );

  // ...

  Future<void> loadRecording() async {
    try {
      return _audioPlayer.setSourceUrl(widget.url!);
    } catch (e) {
      print('Catched $e');
    }
  }
</pre>

i have an app depending on this package, and right now the old build i put in the AppStore is working fine.
other infos i can give is that i can't seem to make it work with simulator nor real device, and i also tried to use the latest commit (that fixes the problem i previously linked) to fix it, without any success.
the exception i get is this:
`PlatformException (PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null))`
Hope I'm doing something wrong

**Comment by putnokiabel** [comment]
Great, thanks @Gustl22 ! 😄
