### ISSUE TITLE
implement setSourceBytes for web

### ISSUE THREAD

**Issue by lucasdidur** [bluefireteam/audioplayers#1670]
### Checklist

- [ ] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Play audio offline from bytes in cache.

### Proposal / Solution

Implement setSourceBytes

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### Working on PR

no way

**Comment by Gustl22** [comment]
See #1269
