### ISSUE TITLE
Add web support for setSourceBytes

### ISSUE THREAD

**Issue by xinlake** [bluefireteam/audioplayers#1681]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Flutter web app uses AudioPlayers to play audio data byte responses from a cloud service

### Proposal / Solution

A very simple implements of `setSourceBytes` on Web, it works well.
```dart
Future<void> setSourceBytes(List<dynamic> bytes) async {
  final audioBlobUrl = Url.createObjectUrlFromBlob(
    Blob([bytes], "audio/mpeg"),
  );
  await audioPlayer.setSourceUrl(audioBlobUrl);
}

```
Need to delete the url when no longger use
```dart
Url.revokeObjectUrl(audioBlobUrl);
```

### Affected platforms

web

### Working on PR

no way

**Comment by Gustl22** [comment]
Closing in favor of #1670 and #1269. Please bring up your ideas and benefits there. Thank you ;D
