### ISSUE TITLE
 audioRecorderService?.playUrl(words.audio!);

### ISSUE THREAD

**Issue by lurongshuang** [bluefireteam/audioplayers#1682]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

flutter: \^[[31mAudioPlayers Exception: AudioPlayerException(
	UrlSource(url: https://dict.youdao.com/dictvoice?type=0&audio=sheet), 
	PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)

### Expected behaviour

play

### Steps to reproduce

play url : https://dict.youdao.com/dictvoice?type=0&audio=sheet

### Affected platforms

iOS

### Platform details

ios 16.1.1
iPhoneXR
xcode 14.3.1 (14E300c)
Flutter 3.10.5
Dart SDK version: 3.0.5

### AudioPlayers Version

audioplayers: ^5.2.0

### Build mode

debug

### Audio Files/URLs/Sources

https://dict.youdao.com/dictvoice?type=0&audio=sheet

### Logs

flutter: \^[[31mAudioPlayers Exception: AudioPlayerException(
	UrlSource(url: https://dict.youdao.com/dictvoice?type=0&audio=sheet), 
	PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)

### Working on PR

no way

**Comment by Gustl22** [comment]
Hi there :)
Please see the troubleshooting guide: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#ios-macos-urls-or-paths-without-a-file-extension 
Thanks ;D

**Comment by lurongshuang** [comment]
https://dict.youdao.com/dictvoice?type=0&audio=language    can  play

https://dict.youdao.com/dictvoice?type=0&audio=sheet  cannot play

**Comment by lurongshuang** [comment]
@Gu

**Comment by lurongshuang** [comment]
@Gustl22

**Comment by Gustl22** [comment]
That's because the first audio is an MP3:
> LAME encoded MP3 audio (ID3 v2.x tag)

and the second one is a RIFF/WAV:
> RIFF/WAVe standard Audio

See also: https://github.com/bluefireteam/audioplayers/issues/1668#issuecomment-1782511686

Checked with: https://www.aconvert.com/analyze.html

Reevaluate if the audio format is supported by apple, see the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#supported-formats--encodings)!
