### ISSUE TITLE
When I play an audio, the sound of my other apps will stop, such as music-App

### ISSUE THREAD

**Issue by afskalsfk** [bluefireteam/audioplayers#1685]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

我正在后台听歌， 当我执行我的app并播放背景音效时 我的后台音乐被中断了，这个应该如何处理

Edit (engl.): I am listening to music in the background. When I execute my app and play background sound effects, my background music is interrupted. How should I deal with this?

### Expected behaviour

不会中断我的后台音乐，两者同时存在

Edit (engl.): Doesn't interrupt my background music, both at the same time

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android, iOS

### AudioPlayers Version

5.1.0

### Build mode

release

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by exoad** [comment]
看看这个 https://pub.dev/packages/audio_service

**Comment by Gustl22** [comment]
You need to set the `AudioContext` to not interrupt your other apps:

```dart
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      android: AudioContextAndroid(
        audioFocus: AndroidAudioFocus.none,
      ),
    ),
  );
```
