### ISSUE TITLE
Audio still plays after hot restart 

### ISSUE THREAD

**Issue by sanihaq** [bluefireteam/audioplayers#1693]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

audio still plays after hot restart. the connection is lost to the previous instance player, so, theres no way to control the playing audio.

### Expected behaviour

it should stop playing or the connection reestablish so the audio could be controlled or previous instance should be destroyed.

### Steps to reproduce

just restart an app with audio playing.

### Affected platforms

macOS

### AudioPlayers Version

5.2.0

### Working on PR

no way

**Comment by Gustl22** [comment]
Plz vote the existing issues and especially the [original](https://github.com/flutter/flutter/issues/10437) one from flutter. See #1120
