### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by erperejildo** [bluefireteam/audioplayers#1698]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I have followed the steps to try the package locally but it doesn't work.

Folder included:
```
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
```

Version: 
`audioplayers: ^5.2.0`

Audio file:
![image](https://github.com/bluefireteam/audioplayers/assets/5629919/737aa4b3-b682-4c16-a584-76165e3285ab)

Play sound:
```
final player = AudioPlayer();
await player.setSource(AssetSource('audio/numbers/en/28.mp3'));
await player.resume();
```

Error:
```
FlutterError (Unable to load asset: "assets/audio/numbers/en/28.mp3".
The asset does not exist or has empty data.)
```

I also cloned the example repo to test directly from it but it doesn't compile due to some other errors:
- The setter 'positionUpdater' isn't defined for the type 'AudioPlayer'.
Try importing the library that defines 'positionUpdater', correcting the name to the name of an existing setter, or defining a setter or field named 'positionUpdater'.
- The function 'TimerPositionUpdater' isn't defined.
Try importing the library that defines 'TimerPositionUpdater', correcting the name to the name of an existing function, or defining a function named 'TimerPositionUpdater'.
- The argument type 'Set<AVAudioSessionOptions>' can't be assigned to the parameter type 'List<AVAudioSessionOptions>?'.

### Expected behaviour

It should play the sound

### Steps to reproduce

Import an audio and try to reproduce it

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### Platform details

Android (emulator and real device, not tested on other platforms)

### AudioPlayers Version

5.2.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
> Folder included

Don't you have to include the subdirectories in order to be able to access them?
https://docs.flutter.dev/ui/assets/assets-and-images#specifying-assets

```
flutter:
  assets:
    - assets/audio/numbers/en/
```

> I also cloned the example repo to test directly from it but it doesn't compile due to some other errors

You need to run melos before to load the current API: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#environment-setup

**Comment by erperejildo** [comment]
> > Folder included
> 
> Don't you have to include the subdirectories in order to be able to access them? https://docs.flutter.dev/ui/assets/assets-and-images#specifying-assets
> 
> ```
> flutter:
>   assets:
>     - assets/audio/numbers/en/
> ```
> 
> > I also cloned the example repo to test directly from it but it doesn't compile due to some other errors
> 
> You need to run melos before to load the current API: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#environment-setup

Sorry for the mistake, you're right. On previous projects I didn't have any subfolder and I thought including the main one would include the subfolders as well
