### ISSUE TITLE
Can you provide a seek method?

### ISSUE THREAD

**Issue by caoxingyu** [bluefireteam/audioplayers#1709]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

I want to fast forward while playing audio

### Proposal / Solution

Can you provide a seek method?

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### Working on PR

no way

**Comment by Gustl22** [comment]
https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#seek

**Comment by caoxingyu** [comment]
I made a mistake.
