### ISSUE TITLE
AudioPlayers uses a deprecated AVAudioSesssion.Category. audioProcessing

### ISSUE THREAD

**Issue by wujek-srujek** [bluefireteam/audioplayers#1722]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

The latest version uses is here: https://github.com/bluefireteam/audioplayers/blob/audioplayers-v5.2.1/packages/audioplayers_darwin/ios/Classes/AudioContext.swift#L72, it has been deprecated for a while now: https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616564-audioprocessing

### Affected platforms

iOS

### AudioPlayers Version

main, 5.2.1

**Comment by Gustl22** [comment]
Thank you for reporting :)
