### ISSUE TITLE
In IOS .ogg file is not working.

### ISSUE THREAD

**Issue by DenishUbhal** [bluefireteam/audioplayers#1733]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

.ogg file is not working in IOS.

### Expected behaviour

Why only in IOS .ogg file is not working. In android it is working fine.

### Steps to reproduce

1. Execute `flutter run` on the code sample 

2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
Connected devices:
ONEPLUS A5010 (mobile) • 192.168.1.142:5555                   • android-arm64 • Android 10 (API 29)
iPhone 7 Plus (mobile) • 1B900D71-15DB-4650-95AE-7B575A06E9F8 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
macOS (desktop)        • macos                                • darwin-arm64  • macOS 13.6 22G120 darwin-arm64

No wireless devices were found.

[1]: ONEPLUS A5010 (192.168.1.142:5555)
[2]: iPhone 7 Plus (1B900D71-15DB-4650-95AE-7B575A06E9F8)
[3]: macOS (macos)

```

</details>

### Affected platforms

iOS

### Platform details

IOS devices

### AudioPlayers Version

audioplayers: ^5.2.1

### Build mode

debug

### Audio Files/URLs/Sources

https://[engees.11za.com/internal-11za/Receive/AUD/AUD-6641217879675394.ogg](https://engees.11za.com/internal-11za/Receive/AUD/AUD-6641217879675394.ogg)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

 flutter: \^[[31mAudioPlayers Exception: AudioPlayerException(
	UrlSource(url: https://engees.11za.com/internal-11za/Receive/AUD/AUD-08060716225616038.ogg), 
	PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)<…>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)

  Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6 22G120 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (4 available)
[✓] Network resources

  Output of: flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6 22G120 darwin-arm64, locale
    en-IN)
    • Flutter version 3.16.0 on channel stable at /Users/engees/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/engees/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/engees/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/engees/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Users/engees/Downloads/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • ONEPLUS A5010 (mobile) • 192.168.1.142:5555                   • android-arm64  • Android 10 (API 29)
    • iPhone 7 Plus (mobile) • 1B900D71-15DB-4650-95AE-7B575A06E9F8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.
    
</details>

### Related issues / more information

no

### Working on PR

no way

**Comment by Gustl22** [comment]
Did you read the troubleshooting guide like stated in the error?

**Comment by DenishUbhal** [comment]
Yes, I read troubleshooting guide. What is the alternative solution for this?

**Comment by Gustl22** [comment]
Complain at Apple :)

There's a forum post with 1,7k views, but no answer:
https://developer.apple.com/forums/thread/668439

Or fill a feedback report there: https://developer.apple.com/bug-reporting/

I guess the simplest soltion is to convert your files to another format, before playing.
