### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException，The firebase crash was reported on Android 14 and Android 10，I have not repeated this problem myself，but this issue did not occur on 4.1.0

### ISSUE THREAD

**Issue by Tangxiaochuanle** [bluefireteam/audioplayers#1734]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

android.media.MediaPlayer.getPlaybackParams (MediaPlayer.java)
xyz.luan.audioplayers.player.MediaPlayerPlayer.setRate (MediaPlayerPlayer.java:2)
xyz.luan.audioplayers.player.MediaPlayerPlayer.start (MediaPlayerPlayer.java:6)
xyz.luan.audioplayers.player.WrappedPlayer.onPrepared (WrappedPlayer.java:17)
xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda$5$lambda$0 (MediaPlayerPlayer.java:5)
android.media.MediaPlayer$EventHandler.handleMessage (MediaPlayer.java:3410)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:226)
android.app.ActivityThread.main (ActivityThread.java:7592)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

project version：
targetSdkVersion 34
audioplayers: ^5.2.0
flutter sdk version：3.13.9

### Expected behaviour

The firebase crash was reported on Android 14 and Android 10

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

5.2.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
It's hard to reproduce without steps. Anyways we're planing to switch to [Exoplayer](https://github.com/bluefireteam/audioplayers/pull/1691). If you come up with a fix, feel free to open a PR. Thanks for your patience.
