### ISSUE TITLE
getting error while playing the audio in linux

### ISSUE THREAD

**Issue by SoftoNaveen** [bluefireteam/audioplayers#1735]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Launching lib/main.dart on Linux in debug mode...
CMake Error at /snap/flutter/141/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /snap/flutter/141/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:24 (pkg_check_modules)

Building Linux application...                                           
Exception: Unable to generate build files

### Expected behaviour

we are expecting to play audio file using flutter desktop application in Ubuntu 22

### Steps to reproduce

1. Execute `flutter run` on the code sample (example code provided by you)

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Linux

### AudioPlayers Version

5.2.1

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by japostoles** [comment]
The key here is the message "A required package was not found"

In your case, make sure gstreamer is installed.

Here's the relevant bit showing which packages are required: https://github.com/bluefireteam/audioplayers/blob/2333cb7f5a9fcd84bdd477120d1f53f346c3b10d/packages/audioplayers_linux/linux/CMakeLists.txt#L20C1-L26C64

**Comment by blackshadowsoftwareltd** [comment]
> The key here is the message "A required package was not found"
> 
> In your case, make sure gstreamer is installed.
> 
> Here's the relevant bit showing which packages are required: https://github.com/bluefireteam/audioplayers/blob/2333cb7f5a9fcd84bdd477120d1f53f346c3b10d/packages/audioplayers_linux/linux/CMakeLists.txt#L20C1-L26C64

It's worked for my issue.
I have installed 
`gstreamer-audio` ,`gstreamer-audio-sys` , & `gstreamer-app`

**Comment by Gustl22** [comment]
@SoftoNaveen did you follow these instructions for linux? https://github.com/bluefireteam/audioplayers/tree/2333cb7f5a9fcd84bdd477120d1f53f346c3b10d/packages/audioplayers_linux#setup-for-linux

**Comment by Gustl22** [comment]
I'm closing this for now, seems you using flutter via snap, which is not working well.
