### ISSUE TITLE
I don't want to have sound output while in silent mode.

### ISSUE THREAD

**Issue by buisiss12** [bluefireteam/audioplayers#1737]
(iOS) Before using this package, flutter_TTS would not play when the device was in silent mode. But after using this package, audio is now output even when the device is in silent mode. 

AppDelegate.swift is default now. 　I tried 'import AVFoundation' and try 'AVAudioSession.sharedInstance().setCategory(.ambient) '   but it did not cure the problem.

How do I mute all sound output from the app when in silent mode?

**Comment by Gustl22** [comment]
Can you please fill the complete issue template? I'm not sure, you're in the right package. These calls are not part of our exposed library.
