### ISSUE TITLE
Support Playlists

### ISSUE THREAD

**Issue by SuricateTrading** [bluefireteam/audioplayers#1741]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Currently it is only possible to play a single file. 

### Proposal / Solution

It would be great if we could add a playlist so that when one song ends, the next song automatically plays.

### Affected platforms

Android, iOS, web, Windows, Linux, macOS, other

### Working on PR

no way

**Comment by maknon** [comment]
I want to comment here:

```playlist: you can implement playlists as you wish by playing multiple audios or songs in sequence. Doesn't make sense for this package to have any builtin playlist mechanism.```

i believe the value is to have gapless playlist. Start loading next item just before reaching it.

**Comment by SuricateTrading** [comment]
I think a lof of people would like this feature.
"Doesn't make sense" is a harsh statement for an audio player package.

**Comment by abdusalamApps** [comment]
> Playlists are not scope of this library. You can implement your own though :) https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md#other-out-of-scope-features

I'm trying to play audio files in a list. I'm basically incrementing an index in `onPlayerComplete`, but it gets triggered multiple times and as result multiple files get skipped.

This is basically what I'm doing
```
 _playerCompleteSubscription =  _audioPlayer1.onPlayerComplete.listen((event) {
print('Player complete');
index++;
};
```

I'm seeing 'Player complete' multiple times in the logs. Any idea how to do it correctly?
