### ISSUE TITLE
.oga is not supporting in IOS

### ISSUE THREAD

**Issue by Ram-CGPL** [bluefireteam/audioplayers#1748]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

If i play .oga extention url in ios, throwing error (getting from whatsapp api)

### Expected behaviour

.oga audio file should be play

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

^5.1.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Yes as stated in the troubleshooting guide, which you checked that you read it, oga is not supported by ios. We can not do anything about it :/
