### ISSUE TITLE
How can I stop streaming and dispose player before start?

### ISSUE THREAD

**Issue by keyvanshajari** [bluefireteam/audioplayers#1752]
How can I stop streaming and dispose the player before starting the audio and completely loading the audio in Windows?
when I stop or dispose audio players object my app crashes.

Windows 10
audioplayers 5.2.1

**Comment by Gustl22** [comment]
It should be possible via `stop` or `release`. Once you have `disposed` your player, you have to create a new one via `AudioPlayer()`.
Does this problem still occur with version `6.0.0`?
