### ISSUE TITLE
Sound from assets folder takes time to play

### ISSUE THREAD

**Issue by Adrien300101** [bluefireteam/audioplayers#1755]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I am trying to add a sound effect when clicking on a button. The code works fine but I noticed that the sound does not play instantly as I click the button. There is always a delay. This is the code I wrote:

var player = AudioPlayer();

onTap: () async {
    await player.play(AssetSource('button_sounds/plus.mp3'));
}

### Expected behaviour

Once the user clicks on the button there should be negligible delay. I went through the documentation but not sure if I missed any implementation. Thanks in advance for the help.

### Affected platforms

Android, iOS

### AudioPlayers Version

5.2.1

### Build mode

debug

### Audio Files/URLs/Sources

[button_sounds.zip](https://github.com/bluefireteam/audioplayers/files/14204708/button_sounds.zip)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Did you try setting the source upfront via `setSource` and then only start playing via `resume`?
See: https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#sources
