### ISSUE TITLE
Make audioplayer package compatible with WASM

### ISSUE THREAD

**Issue by zoeyfan** [bluefireteam/audioplayers#1765]
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

We are hoping to use this package to create an exciting demo game (that uses Flutter and Flame) for an upcoming event. The game will support WASM, which is a critical product message Flutter team wants to land. Therefore, we would also appreciate it if this package could support WASM. 

### Proposal / Solution

Having a quick look, it looks like all the web code is here:
https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers_web/lib
There's one file importing package:js and one file importing dart:html.
Hopefully these are the only two files that need to be touched in order to make the package compatible with WASM. 

### Example Code

<details>
<summary>Example Code</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### Platform details

WASM specific support

### Working on PR

no way

**Comment by kevmoo** [comment]
See details at

https://dart.dev/interop/js-interop
https://dart.dev/interop/js-interop/package-web
