### ISSUE TITLE
UrlSource not working wit some urls

### ISSUE THREAD

**Issue by MarcoFiorentino** [bluefireteam/audioplayers#1768]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I'm trying to play an audio from url using the urlSource.

If I use the url taken from the live example of the package (https://luan.xyz/files/audio/nasa_on_a_mission.mp3) it works well but if I use that same file hosted on my public github repository (https://github.com/MarcoFiorentino/sounds/blob/main/nasa_on_a_mission.mp3) it doen't work and it return to me the error:
MEDIA_ERROR_UNKNOWN {what:1}, MEDIA_ERROR_SYSTEM
Failed to set source

### Expected behaviour

I'd like my app to play the audio even if hoster on my repository or at least that it returns an explicit error on why the source is wrong

### Code sample

// Working
AudioPlayer player = AudioPlayer();
String path = "https://luan.xyz/files/audio/nasa_on_a_mission.mp3";
Source source = UrlSource(path);
player.play(source);

// Not working
AudioPlayer player = AudioPlayer();
String path = "https://github.com/MarcoFiorentino/sounds/blob/main/nasa_on_a_mission.mp3";
Source source = UrlSource(path);
player.play(source);

### Affected platforms

Android

### Platform details

- Realme 9 with Android 13
- Emulator with Android 14 on macbook pro (with os Sonoma 14.4)

### AudioPlayers Version

5.2.1

### Screenshots

![Screenshot 2024-03-14 alle 17 39 24](https://github.com/bluefireteam/audioplayers/assets/4190432/a3b331be-ad5d-4d69-b731-2fb1fd51ec4b)

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
That's because, it's only the GitHub preview page, not the actual source. If you click right on your url and copy the link you get the actual valid url: https://github.com/MarcoFiorentino/sounds/raw/main/nasa_on_a_mission.mp3
