### ISSUE TITLE
Can't use positionUpdater setter on Windows

### ISSUE THREAD

**Issue by payailk** [bluefireteam/audioplayers#1772]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

The setter 'positionUpdater' isn't defined for the type 'AudioPlayer'.

### Expected behaviour

Change the position update interval

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Windows

### AudioPlayers Version

main 5.2.1

### Build mode

debug

### Logs

[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19044.3930], locale zh-Hans-HK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] VS Code (version 1.87.1)
[√] Connected device (3 available)
[√] Network resources

### Working on PR

no way

**Comment by Gustl22** [comment]
Hi there 👋🏻
You need to override all dependencies in order to work.
https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#current-development

But version 6.0.0 was now released anyways, so can just use that.
Kind regards
