### ISSUE TITLE
Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope

### ISSUE THREAD

**Issue by Fudal** [bluefireteam/audioplayers#1776]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Building app has error:
Xcode build done.                                           50.9s
```
Failed to build iOS app
Swift Compiler Error (Xcode): Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope
/Users/runner/.pub-cache/hosted/pub.dev/audioplayers_darwin-6.0.0/ios/Classes/WrappedMediaPlayer.swift:[18](https://github.com/SpectrumInsights/memeo-app/actions/runs/8355910679/job/22871926944#step:14:19)4:36
```

### Expected behaviour

Building app is end with success

### Steps to reproduce

1. Create app with using audioplayers
2. Create github workflow with build iOS app
3. See error

### Affected platforms

iOS

### AudioPlayers Version

6.0.0

### Build mode

release

### Logs

```
Running pod install...                                              6.3s
Running Xcode build...                                          
Xcode build done.                                           50.9s
Failed to build iOS app
Swift Compiler Error (Xcode): Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope
/Users/runner/.pub-cache/hosted/pub.dev/audioplayers_darwin-6.0.0/ios/Classes/WrappedMediaPlayer.swift:[18](https://github.com/SpectrumInsights/memeo-app/actions/runs/8355910679/job/22871926944#step:14:19)4:36

Encountered error while building for device.
Error: Process completed with exit code 1.
```

### Working on PR

yeah

**Comment by Gustl22** [comment]
You'll need to use XCode 15

**Comment by el2zay** [comment]
Is there no solution for people who can't get the latest version of Xcode?

**Comment by Gustl22** [comment]
Unfortunately, we have to stick with that, what's apple is forcing us to do.

**Comment by ettaegbe** [comment]
Sticking to that is not really a solution. there are a lot of devs using xcode version < 15

**Comment by Gustl22** [comment]
@ettaegbe If want allowing url sources and byte sources for darwin, we are forced to use `AVURLAssetOverrideMIMETypeKey`, which is only available in XCode 15. 
https://github.com/bluefireteam/audioplayers/commit/eaf7ce86ad271097365fcf9e3a03fc341629ae47#diff-241e808032ff411dc8937308a6d8c8f4ccfb04a2bbb593721c18d3b67befd5b7R183


Maybe we can add some code which can be differentiated before compiling: https://swiftversion.net/
```
#if swift(>=5.9)
print("Running Xcode 15 or later")
#else
print("Running Xcode 14")
#endif
```
