### ISSUE TITLE
Kotlin Gradle plugin version

### ISSUE THREAD

**Issue by yashappdev** [bluefireteam/audioplayers#1787]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':audioplayers' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21

This bug is occurring while launch my application even I have added higher version that 1.5.20. I have added 1.7.10 version of kotlin in gradle.  

### Expected behaviour

My expected behavior is, which version will work? 

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

### Affected platforms

Android

### AudioPlayers Version

0.18.3

### Build mode

debug

### Logs

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':audioplayers' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

### Working on PR

yeah

**Comment by Gustl22** [comment]
Version `0.18.3` is quite old. Did you try a newer version like `v6.0.0`?
