### ISSUE TITLE
Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope

### ISSUE THREAD

**Issue by KishanD24** [bluefireteam/audioplayers#1800]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Swift Compiler Error (Xcode): Cannot find 'AVURLAssetOverrideMIMETypeKey' in scope
audioplayers_darwin-6.0.0/ios/Classes/WrappedMediaPlayer.swift:184:36

I am getting ios app runtime issue.

### Expected behaviour

can you please fix this issue

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### Platform details

IOS 14

### AudioPlayers Version

6.0.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
> I made sure that the issue I am raising doesn't already exist

Are you sure you did search the existing issues, before raising a new one?

Thx

https://github.com/bluefireteam/audioplayers/issues?q=is%3Aissue+AVURLAssetOverrideMIMETypeKey+is%3Aclosed

**Comment by ettaegbe** [comment]
@KishanD24 did you solve it?

**Comment by softmastx** [comment]
I came across the need to install the audioplayers package.

flame_audio: ^2.0.0
audioplayers: ^5.0.0

**Comment by KishanD24** [comment]
> [@KishanD24](https://github.com/KishanD24) did you solve it?

no i dont get solution for that..
