### ISSUE TITLE
Get current volume / amplitude of the file being played

### ISSUE THREAD

**Issue by kataklysmo** [bluefireteam/audioplayers#203]
It would be good to add this functionality, in android would be something like this:

final int volume_level = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
int maxVolume = audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC);
float volume = (float) volume_level / maxVolume;

Thanks!

**Comment by erickzanardo** [comment]
Sounds a good addition @kataklysmo  Would you be willing to submit a PR? Also do you any idea on how to do on iOs?
