### ISSUE TITLE
DartMessenger(19023): Sending message with callback over channel 'xyz.luan/audioplayers'

### ISSUE THREAD

**Issue by willvlad** [bluefireteam/audioplayers#208]
I've got the above being printed every second in the console, non-stop. Not sure what it means and how to get rid of it. Any thoughts?

**Comment by luanpotter** [comment]
I'd like to reduce these annoying logs. I see then on android side, plus some mediaplayer messages I can't find how to disable. Anyone has any idea about it?

**Comment by Gustl22** [comment]
Related to #151, but maybe disable this ones permanentely(?)

**Comment by Gustl22** [comment]
Closing this in favor of #933
