### ISSUE TITLE
Add a possibility to change playing speed/rate

### ISSUE THREAD

**Issue by dvorapa** [bluefireteam/audioplayers#224]
Add a possibility to change audio player speed/rate

See for example https://pub.dev/packages/audioplayers_with_rate (I don't know where the code of audioplayers_with_rate is located), https://pub.dev/packages/youban_audio, https://pub.dev/packages/youban_audioplayer, https://github.com/Weststreet/audioplayers, or https://github.com/catoldcui/audioplayers

**Comment by luanpotter** [comment]
That'd be a good thing to have. If you are interested, you can help us out with a PR :)

**Comment by subhash279** [comment]
@luanpotter  Submitted a PR #270

**Comment by dvorapa** [comment]
For iOS this is already solved in master (and in the upcoming release), for Android the work has already begun! Thanks @subhash279!

**Comment by yringler** [comment]
https://github.com/Weststreet/audioplayers
1. has been kept up to date
1. has support for soundpool.
2. Checks android version to gracefully not support < SDK 23 for mediaplayer

Todo:
1. make it into a PR
2. If we aren't dropping mediaplayer yet:
 2.1  Add a canChangeSpeed method
 2.2 Document

I don't think it's a ton to do, but I don't know that I'll be able to get around to it so soon.
@subhash279 , do you still plan on working on android?

**Comment by dvorapa** [comment]
See also https://github.com/luanpotter/audioplayers/pull/304

**Comment by subhash279** [comment]
@yringler I do intend to do it in the future but I am really busy right now. So I don't think I can get back to it in the next one month. If any one else is willing to finish it, that would be great.

**Comment by dvorapa** [comment]
Isn't this solved?

**Comment by Gustl22** [comment]
According to [parity table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md) every platform is supported.
