### ISSUE TITLE
Playing different local files crashes iOS

### ISSUE THREAD

**Issue by tantzygames** [bluefireteam/audioplayers#23]
Playing multiple files works on Android, but playing a second file crashes iOS with no warning.

Playing the same file multiple times works on iOS. I've just tested with "audioplayer" and it works with different files on iOS, but I would like to use your volume feature.

**Comment by Kretin1** [comment]
Thanks. I didn't notice the update.

After updating to 0.7.0 and updating my code accordingly, no crashes, but no audio either. My local audio files are now not playing at all.

I tested your example, and:
 - Local File: after I download the file and press the play button the audio does not play. Pressing pause or stop and then play again plays the file.
- Local Assets: none of the buttons play any audio.

I only get:
ios -> updateDuration...3.813878
ios -> invokechannel

**Comment by erickzanardo** [comment]
@feroult just tested the above and is indeed not working, any thoughts?

**Comment by feroult** [comment]
I've a fix: https://github.com/luanpotter/audioplayer/commit/3c300beaaa4b29101ffc96607ef9ea7ba1317fbb

The strange thing is that it wasn't supposed to work before.

Tested all example tabs, it is working well. Would someone confirm it please?

**Comment by Kretin1** [comment]
Thanks ferault, you're a champion! 

I haven't tested the audioPlayers example, but that fix is working a treat in my project.

**Comment by feroult** [comment]
@Kretin1 

I've got it. The callback wasn't firing the second time because the asset was already loaded: https://github.com/luanpotter/audioplayer/commit/94430f1f21c4c06595bf1fe99a1b35bd668aa00b

Please let us know if it is not working again in some scenario that you have.

**Comment by Kretin1** [comment]
@feroult Thank you so much.

I tested my project and the example, and both appear to be working correctly.
