### ISSUE TITLE
Error: Attempt to call getDuration in wrong state

### ISSUE THREAD

**Issue by VictorUvarov** [bluefireteam/audioplayers#266]
I get the following error when trying to get duration for a remote URL. I am trying to get the duration to load before I show the widget because it is really confusing for the user to see a position of 0 and a duration of 0.
- Platform: Android
- Code
```dart
AudioPlayer _audioPlayer = AudioPlayer();
final url = 'https://www.sample-videos.com/audio/mp3/crowd-cheering.mp3'
int success = await _audioPlayer.setUrl(url);

if (success == 1) {
    int duration = await _audioPlayer.getDuration();
}
```
- Error
```
V/MediaHTTPService(13455): MediaHTTPService(android.media.MediaHTTPService@12f1aa7): Cookies: null
V/MediaHTTPService(13455): makeHTTPConnection: CookieHandler (java.net.CookieManager@c5f5f0f) exists.
V/MediaHTTPService(13455): makeHTTPConnection(android.media.MediaHTTPService@12f1aa7): cookieHandler: java.net.CookieManager@c5f5f0f Cookies: null
V/MediaHTTPService(13455): MediaHTTPService(android.media.MediaHTTPService@1e47afd): Cookies: null
V/MediaHTTPService(13455): makeHTTPConnection: CookieHandler (java.net.CookieManager@c5f5f0f) exists.
V/MediaHTTPService(13455): makeHTTPConnection(android.media.MediaHTTPService@1e47afd): cookieHandler: java.net.CookieManager@c5f5f0f Cookies: null
V/MediaHTTPService(13455): MediaHTTPService(android.media.MediaHTTPService@86fa3f2): Cookies: null
V/MediaHTTPService(13455): makeHTTPConnection: CookieHandler (java.net.CookieManager@c5f5f0f) exists.
V/MediaHTTPService(13455): makeHTTPConnection(android.media.MediaHTTPService@86fa3f2): cookieHandler: java.net.CookieManager@c5f5f0f Cookies: null
E/MediaPlayerNative(13455): Attempt to call getDuration in wrong state: mPlayer=0x79ec7b73c0, mCurrentState=4
E/MediaPlayerNative(13455): error (-38, 0)
E/MediaPlayer(13455): Error (-38,0)
V/MediaPlayer(13455): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(13455): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(13455): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(13455): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

**Comment by kaifiappsmaven** [comment]
While initializing audio player use below method - 
 _durationSubscription =
        Injector.getAUdio().onDurationChanged.listen((duration) {
          if (!mounted) return;
          setState(() {
            if (_playerState != PlayerState.paused ||
                _playerState != PlayerState.stopped) {
              _duration = duration;
            }
          });
        });
It will return duration of audio. 
In meantime this value is fetched, you can show streaming.. function. When this value is update show it in widget

**Comment by shikha1992** [comment]
As suggested by @erickzanardo , above example to fetch duration is working fine. I implemented same in demo. 
Future<int> _getDuration() async {
    int duration = await Future.delayed(Duration(seconds: 0), () => Injector.getAUdio().getDuration());
    debugPrint('duration$duration');
    _duration = Duration(milliseconds: duration);
    return duration;
  }
After initializing audioplayer, duration is fetched after passing url to audioplayer.

**Comment by volgin** [comment]
The solution proposed by @shikha1992 does not work, unless I set duration of a delay to 500ms (at 250ms it works sometimes). This is definitely a bug.

The same code for iOs works without a delay.

**Comment by Nailik** [comment]
I had the same Problem with getDuration and when i want to read mp3 Tags, i don't want a 250-500ms delay for every single song.
The best way to get the duration ist maybe https://pub.dev/packages/flutter_ffmpeg (Flutter FFMPEG).
It can also read title etc and audio-tls supports down to android 16

**Comment by chornbe** [comment]
I've had to implement the delay. I went through hoop after hoop after hoop. Ultimately, I just elected to NOT show or care about the duration until playback started :( 

Seems I have a lot of flutter code that basically says:

if( true == isAndroid ) { /* do all the workaround stuff here because android */ } 

:(

**Comment by 1912820899** [comment]
> The solution proposed by @shikha1992 does not work, unless I set duration of a delay to 500ms (at 250ms it works sometimes). This is definitely a bug.
> 
> The same code for iOs works without a delay.

Thanks，I fixed the problem with delay 300ms in Android
