### ISSUE TITLE
Add audioplayers to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [bluefireteam/audioplayers#269]
audioplayers can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by erickzanardo** [comment]
@luanpotter what do you think about this?

**Comment by Gustl22** [comment]
I think [flutterarsenal](https://github.com/flutterarsenal/FlutterArsenal/commits/master) is not actively maintained anymore.
