### ISSUE TITLE
Make the time that position updates are given configurable

### ISSUE THREAD

**Issue by wilkomanger** [bluefireteam/audioplayers#349]
Currently progress bars for playing audio are not that smooth because they're send out every 200ms, roughly. It would be nice to make this amount configurable to make progress bars smoother.

**Comment by volgin** [comment]
1. I believe that this is system-dependent, not something that can be configured. I'll let the plugin author to confirm.

2. If your progress bar is 1000 pixels, then for any recording longer than 200 seconds each notification equals less than 1 pixel. Making notifications more frequent will not make any difference.

**Comment by wilkomanger** [comment]
> 1. I believe that this is system-dependent, not something that can be configured. I'll let the plugin author to confirm.

In [`flutterr_sound`](https://github.com/dooboolab/flutter_sound) it's configurable, and defaults to 10 milliseconds.

> 2. If your progress bar is 1000 pixels, then for any recording longer than 200 seconds each notification equals less than 1 pixel. Making notifications more frequent will not make any difference.

Sure. But we're often dealing with short files so this is not a solution!

**Comment by luanpotter** [comment]
on ios its a hardcoded constant (I've stumbled upon it). on android not sure. could possibly be a PR.

**Comment by Gustl22** [comment]
We may could think about removing the `onDuration` and `onPosition` event on the native side, and request the according native values on a async runner on the dart side every x milliseconds. So the updates would be much more configurable. Or just hand over the update interval to the native side.
