### ISSUE TITLE
ios: about onDurationChanged fire time and remote control

### ISSUE THREAD

**Issue by Mamong** [bluefireteam/audioplayers#380]
I am writing a music player based on this plugin. In this program, I will hold a player globally and play a song when enter a song detail page. I will play it and exit, and enter again, and play the same song. I will get the song's duration first time when onDurationChanged fires. But I cannot get that notification later. I have checked the code, the notification is based on KVO, when I play the same song again, the AVPlayerItem's state is already AVPlayerItemStatusReadyToPlay and onDurationChanged will not fire. If I want to make it correct, I need store a url and duration map. But it is not a good idea. When we play a song using 'play' api, it should work like playing a new song, and fire duration notification.

I would like to add [self updateDuration:playerId]; before [onReady(playerId);](https://github.com/luanpotter/audioplayers/blob/560d9871e345b94aef7b11398dfca7b524405b6d/ios/Classes/AudioplayersPlugin.m#L478)

Another topic remote control, I think we can support nextTrackCommand and previousTrackCommand later. In my design, I prefer MPRemoteCommands than MPSkipIntervalCommands.

**Comment by Gradergage** [comment]
Agree with this, on IOS onDurationChanged doesn't work with replay. Meet that then reopened the widget

**Comment by Gustl22** [comment]
Fixed via #1206
