### ISSUE TITLE
Logic between setUrl()/resume() and play() when using multiple players

### ISSUE THREAD

**Issue by volgin** [bluefireteam/audioplayers#404]
1. It appears that play() is just a convenience method for setUrl/resume, because play() calls setUrl() under the hood. The problem is that play() has 'stayAwake' property, while setUrl/resume combo does not.

It means that the first play on a player must always be play(), which is fine for a single player implementation, but becomes a problem if an app tries to prepare multiple players by calling setUrl before the first play (for example, in order to reduce a gap between a user action and when the music starts playing).

Maybe 'stayAwake' can be added to setUrl. Or, even better, it can be a property of an audio player itself, set when a player is created.

2. The notification logic is implemented in setUrl, which again is fine for a single player implementation. However, if there are two players, then the following typical use case becomes impossible:

* setUrl() on player A
* resume() on player A
* while playerA plays, prepare player B by calling setUrl() on player B
* when player A finishes playing, call resume() on player B

The call on player B will override notification center changes, even though player B is not playing yet.

The code to update notification settings (and AVAudioSession settings) logically belongs to play() and resume(), not to setUrl(). Then apps will be able to call setUrl in advance in order to reduce a network latency impact on user experience.

**Comment by luanpotter** [comment]
I noticed this mess when converting the code to swift. I intend to make a change to these set of 3 boolean params so they are more clear and also separate global things/local per audioplayer instance things. Thanks for the detailed report, @volgin

**Comment by Gustl22** [comment]
@volgin Is this fixed with 1.x.x?
