### ISSUE TITLE
Panning Audio

### ISSUE THREAD

**Issue by chrisnorman7** [bluefireteam/audioplayers#571]
Hi,
Is it possible to pan audio with this package?

Looks great. Thank you.

Take care,

Chris

**Comment by luanpotter** [comment]
What do you mean by pan? You can seek and pause, that sounds like panning to me.

**Comment by chrisnorman7** [comment]
Pan, as in changing how far to the left or right a sound is.

Take care,

Chris Norman

**Comment by luanpotter** [comment]
You mean left or right ears for stereo? because you can seek to any moment in time...

**Comment by chrisnorman7** [comment]
Yes, I mean stereo panning.

Take care,

Chris Norman

**Comment by Gustl22** [comment]
Do you mean balancing like in #58, like changing the volume of left and right channel.

I think real stereo panning is not the goal, it's the task of audio DAWs:
https://www.pro-tools-expert.com/production-expert-1/the-difference-between-stereo-pan-and-stereo-balance

**Comment by chrisnorman7** [comment]
@Gustl22 
Yes, I mean like #58. Although that issue talks about using an integer, as in -1, 0, or 1. I've not tried the implemented feature, so I've no idea how it works, but I'd have thought a double from -1.0 to 1.0 would be more appropriate.

**Comment by Gustl22** [comment]
It's already partly implemented in #1248. I close this in favor of #58

**Comment by chrisnorman7** [comment]
@Gustl22 
No problem, thank you.
