### ISSUE TITLE
setPlaybackRate() is not implemented on the web

### ISSUE THREAD

**Issue by Wyctus** [bluefireteam/audioplayers#592]
Hello!

Seems like `setPlaybackRate()` is not implemented on the web yet, I got the following error when I try to use it:

`Error: PlatformException(Unimplemented, null, The audioplayers plugin for web doesn't implement the method 'setPlaybackRate')`

Is there any way I can change the speed on web?

Thanks!

**Comment by luanpotter** [comment]
Not rn, but I would love to see a PR!

**Comment by Gustl22** [comment]
Implemented via 3c043f680e291cd3a81f3d36ae58504fd5ac71e9
