### ISSUE TITLE
iOS not return duration

### ISSUE THREAD

**Issue by unger1984** [bluefireteam/audioplayers#666]
On iOS not called onDurationChanged and getDuration return 0

```dart
      await audioPlayer.setUrl('$backUrl/upload/$url', isLocal: false); // remote mp3 file
      audioPlayer.onDurationChanged.listen((d) {
        duration.value = d; // not called!!!
      });
      audioPlayer.onAudioPositionChanged.listen((p) {
        position.value = p; // work success
      });
      int sec = await audioPlayer.getDuration(); // sec =0
      await audioPlayer.resume(); // music listen normal
```

On Android this worked normal

* OS:  iOS 14.1.
* audioplayers 0.16.2
* Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
* Framework • revision 8874f21e79 (3 days ago) • 2020-10-29 14:14:35 -0700
* Engine • revision a1440ca392
* Tools • Dart 2.10.3

**Comment by unger1984** [comment]
Maybe someone will need a temporary fix:

Additional add package audiofileplayer and this code to get duration only:

```dart
Audio.loadFromRemoteUrl('$backUrl/upload/$url', onDuration: ((double seconds) {
        duration.value = Duration(seconds: seconds.toInt());
        isLoad.value = false;
      }));
```

**Comment by Luterium** [comment]
In the other hand, on iOS I'm able to use getDuration properly but when I try to use it on Android it returns 0, no matter what I do. Will try the audiofileplayer workaround as of now, thanks! Hope to see this bug fixed soon enough

**Comment by Luterium** [comment]
audiofileplayer doesn't work for release mode, unfortunately, it gives out "A problem occurred configuring root project 'audiofileplayer'."

**Comment by lvince14** [comment]
Having the same issue, the callback when debugging on iOS is never reached, works fine on android.

OS: iOS 14.0.1
audioplayers 0.17.0
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by SkilyFrance** [comment]
Hello Guys,
For me, IOS return perfectly duration but not in Android. Same problem as @Luterium on simulator.

Do you have tested android duration with getCurrentDuration() from audioplayers package in release mode ? Maybe it works. 

Else if, do you have any solution to resolve this issue ?

Thanks for help,
Guillaume

**Comment by hanyska** [comment]
someone? something?

**Comment by tamoyal** [comment]
I'm getting a duration of 0 when using `getDuration` but if I listen to the event using `onDurationChanged` I get the proper duration. However, that callback will only fire _after_ the `play` is called so it makes the library super hard to use as you have to play the file before you get an accurate duration.

**Comment by tamoyal** [comment]
I saw some errors related to reading the duration while the media player was in the wrong state. Adding a 100 millisecond delay after `setUrl` and before I read the duration seems to make this all work. So I think `setUrl`, even if you await it, returns too early. This is on Android only so far during my testing.

**Comment by Gustl22** [comment]
Should be fixed with 1.x.x. Please create a new issue when this error still occurs. In tests the duration is shown successfully: 
https://github.com/bluefireteam/audioplayers/blob/2cb51b3071676cdb0d2211bec201fc5b05314691/packages/audioplayers/example/integration_test/tabs/stream_tab.dart#L71

**Comment by anandhps** [comment]
If anybody find solution pls help me

**Comment by mavzerbay** [comment]
```
const path = 'https://cdn.pixabay.com/audio/2021/08/17/audio_4bcec6e5c7.mp3';
       
final response = await http.get(Uri.parse(path));
final tempPath = (await getTemporaryDirectory()).path;

final file = File('$tempPath/test.mp3');

await file.writeAsBytes(response.bodyBytes);

await ap.setSourceDeviceFile(
       file.path,
);
              
```

This is how I was able to get the duration of the file on iOS without playing it. I hope this helps you. Sorry for the music, I was able to find this to show :))
