### ISSUE TITLE
Ability  to cache external audio while it is playing.

### ISSUE THREAD

**Issue by TitoMitto** [bluefireteam/audioplayers#691]
Would it be possible to add a feature that enables us to cache external audio so that it doesn't have to be fetched every time.

**Full Description**
This feature will be helpful to users who have limited internet access but want to be able to play the audio once it is cached. So basically the plugin will enable us to pass a variable whether or not to cache the audio, then for subsequent requests the plugin will check if there is an already complete cache of the audio and play it. Optionally someone can also clear the cache. Using AudioCache you can save the audio locally so the plugin doesn't have to request it online if it was already cached.

**Example Code**

`AudioPlayer audioPlayer = AudioPlayer();`
`await audioPlayer.play(externalAudioUrl, cached: true);`

**Platforms**
 android, ios, web.

**Comment by MahdiPishguy** [comment]
+1

also i need to have this feature 

https://stackoverflow.com/q/65145783/1830228

**Comment by wengxianxun** [comment]
i need too

**Comment by Gustl22** [comment]
Closing in favor of #374
