### ISSUE TITLE
AudioPlayer fires onPlayerCompletion when pause is called during buffering

### ISSUE THREAD

**Issue by cubosystemsInternational** [bluefireteam/audioplayers#699]
Hi all,

First off, let me take some time to appreciate this plugin. Its a really good one and helped me in my projects. However, I do have a bug to report.

**Briefing**
The `AudioPlayer` fires `onPlayerCompletion` when the `.pause()` is called during the audio buffering.

**Full Description**
I have a playlist of URLs which I need to play in a row. The playlist plays as soon as the user opens the screen. The `AudioPlayerState` will initially be changing from `STOPPED` to `PLAYING` and my **play** button will be rendered as **pause**. At the time window where the audio is still being buffered, the user can tap on the **pause** button. (I can't disable the button due to no matching event is found by your plugin)

When this happens, the `AudioPlayer` fires the `onPlayerCompletion` event (which I handled to play the next song in the list) and they can repeat this action until the end of the playlist even before any audio is audible.

**Code to Reproduce**
https://github.com/cubosystemsInternational/audio_issue

I recreated a flutter project with a minimal code which reproduces the error. Once you run, tap on the button in the home screen and in the next screen, tap on the **pause** button as soon as you entered it. You will notice how the playlist is changing.

**Platforms**
Issue is reported in many Android mobile phones but the details of the device + development env I mention here belongs to me.

* OS: android.
* OS version: 10.
* Device: Physical Device; Samsung Galaxy A50
* flutter version: 1.20.1 (https://gist.github.com/cubosystemsInternational/8c739d5005ca8ad25f6201cb74014cff)
* audioplayers version: ^0.17.0

**Comment by Gustl22** [comment]
Can you recheck with `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
