### ISSUE TITLE
How to disable log messages when a file is played with AudioCache

### ISSUE THREAD

**Issue by DartPads** [bluefireteam/audioplayers#707]
I'm developing a game and using AudioCache to play a sound when a move is made, which is almost once or twice every second. AudioCache puts a log similar to the following every time a file is played.

D/WSP     ( 5369): Reusing soundId1 for  /data/user/0/com.example.game/cache/audio/slide.mp3 is loading=false xyz.luan.audioplayers.WrappedSoundPool@df25183
D/WSP     ( 5369): Reusing soundId1 for  /data/user/0/com.example.game/cache/audio/slide.mp3 is loading=false xyz.luan.audioplayers.WrappedSoundPool@354cf00
D/WSP     ( 5369): Reusing soundId1 for  /data/user/0/com.example.game/cache/audio/slide.mp3 is loading=false xyz.luan.audioplayers.WrappedSoundPool@c2e5339
D/WSP     ( 5369): Reusing soundId1 for  /data/user/0/com.example.game/cache/audio/slide.mp3 is loading=false xyz.luan.audioplayers.WrappedSoundPool@42afd7e

Is there a way to disable these logs under AudioCache? 

```
import 'dart:io';

import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';

import '../../model/enums.dart';
import '../../model/preferences.dart';
import '../../utils/strings.dart';

class PlaySound {
  final AudioCache audioCache = AudioCache();
  static final PlaySound _singleton = PlaySound._internal();

  factory PlaySound() {
    return _singleton;
  }

  PlaySound._internal() {
    audioCache.loadAll([Strings.sndSlide, Strings.sndGameWon]);
  }

  void play(Sounds sound) async {
    if (Preferences().getSound() && !Platform.isWindows) {
      String snd;
      switch (sound) {
        case Sounds.slide:
          snd = Strings.sndSlide;
          break;
        case Sounds.gameWon:
          snd = Strings.sndGameWon;
          break;
      }
      if (snd.isEmpty == false) {
        await audioCache.play(snd, mode: PlayerMode.LOW_LATENCY);
      }
    }
  }
}

```

Platforms : Android Emulator & Physical Devices

**Comment by najib-mrh** [comment]
same here !

**Comment by Gustl22** [comment]
Is this still a thing in `audioplayers: ^1.1.0`? Retested (Android + LowLatency), but I only got a warning, when source is loaded. But not during playing. LowLatency can only play for 5 seconds anyways. But I think I never saw the error above 1.x.x.

**Comment by Gustl22** [comment]
Closing as stale.
