### ISSUE TITLE
Audio choppy and no lock screen controls

### ISSUE THREAD

**Issue by hossam-zaki** [bluefireteam/audioplayers#741]
Hello! I hope you are doing well! I am running this plugin on an app on my iOS simulator. When I move the app to the background, the audio is stuttering, and this was the case as well when I moved it to my real phone. I enabled "Audio, Airplay, Picture in Picture" on Xcode as well. 

Also, lock screen controls don't show up. Is there a command for them to show up, or is this not built into the package. Thank you for making this, and for your help!

**Comment by hossam-zaki** [comment]
i experience the same with the example app

**Comment by hossam-zaki** [comment]
@luanpotter Do you have any experience with this?

**Comment by kashishkhullar** [comment]
I am not experiencing any stuttering in the case of Android but yes there is no lock screen or notification functionality in this package. Also the audio does not pause when I lock the screen.

**Comment by hossam-zaki** [comment]
> I am not experiencing any stuttering in the case of Android but yes there is no lock screen or notification functionality in this package. Also the audio does not pause when I lock the screen.

Thanks for the reply @kashishkhullar . Any way to get lock screen functionality using this package?

**Comment by luanpotter** [comment]
lock screen commands only for ios.
for the original issue, please check here https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#ios

**Comment by Gustl22** [comment]
I think lock screen won't be supported: https://github.com/bluefireteam/audioplayers/blob/2cb51b3071676cdb0d2211bec201fc5b05314691/feature_parity_table.md?plain=1#L74

Regarding the stuttering. I don't think there's anything we can do about. Stuttering on the simulator can come from anything (e.g. not enough performance on your Mac). Better test on a real device.
