### ISSUE TITLE
BUILD FAILED for XCode 12.4 running on MacOs 11.2 BUT works without issues on Android 

### ISSUE THREAD

**Issue by sevriugin** [bluefireteam/audioplayers#750]
Build failed for XCode 12.4 running on MacOs 11.2 BUT works without issues on Android 

Very simple program (Android Studio 4.2 Betta):

```
import 'package:flutter/material.dart';
import 'package:audioplayers/audio_cache.dart';

void main() => runApp(XylophoneApp());

class XylophoneApp extends StatelessWidget {
  final player = AudioCache();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Container(
            child: FlatButton(child: Text('Play Sound'),onPressed: () {
              player.play('note1.wav');
            },),
          ),
        ),
      ),
    );
  }
}

```

```
name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/


```

Xcode's output:
↳
    ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
    ld: warning: Could not find or use auto-linked library 'swiftDarwin'
    ld: warning: Could not find or use auto-linked library 'swiftMediaPlayer'
    ld: warning: Could not find or use auto-linked library 'swiftUIKit'
    ld: warning: Could not find or use auto-linked library 'swiftFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftsimd'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
    ld: warning: Could not find or use auto-linked library 'swiftMetal'
    ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
    ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
    ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
    ld: warning: Could not find or use auto-linked library 'swiftCore'
    ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
    ld: warning: Could not find or use auto-linked library 'swiftDispatch'
    ld: warning: Could not find or use auto-linked library 'swiftAVFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
    ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
    ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
    ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
    ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
    Undefined symbols for architecture x86_64:
      "nominal type descriptor for Foundation.NSKeyValueObservation", referenced from:
          _symbolic _____Sg 10Foundation21NSKeyValueObservationC in libaudioplayers.a(WrappedMediaPlayer.o)
      "type metadata accessor for Foundation.Notification", referenced from:
          reabstraction thunk helper from @escaping @callee_guaranteed (@in_guaranteed Foundation.Notification) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSNotification) -> () in libaudioplayers.a(WrappedMediaPlayer.o)
      "static Foundation.Notification._unconditionallyBridgeFromObjectiveC(__C.NSNotification?) -> Foundation.Notification", referenced from:
          reabstraction thunk helper from @escaping @callee_guaranteed (@in_guaranteed Foundation.Notification) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSNotification) -> () in libaudioplayers.a(WrappedMediaPlayer.o)

....

(__C.AVPlayer) -> ()) -> () in libaudioplayers.a(WrappedMediaPlayer.o)
          @nonobjc __C.AVPlayerItem.init(url: Foundation.URL) -> __C.AVPlayerItem in libaudioplayers.a(WrappedMediaPlayer.o)
      "_swift_bridgeObjectRetain", referenced from:
          _globalinit_33_26A4F4F1917E61CC91E7E09F8EAB0CFA_func3 in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.players.getter : [Swift.String : audioplayers.WrappedMediaPlayer] in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.players.setter : [Swift.String : audioplayers.WrappedMediaPlayer] in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.lastPlayerId.getter : Swift.String? in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.lastPlayerId.setter : Swift.String? in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.timeObservers.getter : [audioplayers.TimeObserver] in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          audioplayers.SwiftAudioplayersPlugin.timeObservers.setter : [audioplayers.TimeObserver] in libaudioplayers.a(SwiftAudioplayersPlugin.o)
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Pods-Runner' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'path_provider' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'audioplayers' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Runner' from project 'Runner')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by hsiaomingcheng** [comment]
i got same problem

**Comment by pratikbaid3** [comment]
I am having the same issue. Any solution yet?

**Comment by zilaiyedaren** [comment]
i got same problem on Xocde 12.5

**Comment by projectfebr** [comment]
i got same problem, v 0.19
v 0.10 - works

**Comment by Herryjoeson** [comment]
me too

**Comment by ZakariaRebouhi** [comment]
Guys , Anyone find the solution ?

**Comment by Seferi** [comment]
Same issue here...

**Comment by Gustl22** [comment]
Is it still failing with `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
