### ISSUE TITLE
Audio playback freeze/hang up on iOS

### ISSUE THREAD

**Issue by mikeesouth** [bluefireteam/audioplayers#768]
After a while of playing mp3 files from local storage with just play(), audioplayers does no longer play the files, it freezes without playing or responding with anything. What happens is that AudioPlayer.play() returns 1 and sets state to PLAYING but no sound is played, we do not get any duration, we do not get any error on onPlayerError stream, we do not get any exception, we do not get any event on durationChanged stream. It just "hangs" / freezes until we restart the app.

**Full Description**
We're using audioplayers 0.16.1 (we cannot upgrade further due to bug #671). We're playing thousands of sounds every day so our code is mostly working but we have an issue that our users are reporting manually to us: the sound is no longer played after a while and our app stops working because we wait for sound to be played and we wait forever. They have to restart the app to get audio to work again. We've tried to troubleshoot this for a long time but no real success. Earlier this week we added several new logs and so called "watchdog timers" that abort the playing if certain conditions aren't met within a given time frame.
This issue only affects iOS as far as we know, it's our primary platform but we have not been able to reproduce this once on an Android device or emulator and we have not received a single report from Android but now hundreds of reports from iOS users. We're playing rather short mp3-files, around 1-10 seconds in average.
What happens is that we do not get any "life signs" from the audioplayer after a while (it seems random when the bug occurs). We are listening to these streams: onPlayerStateChanged, onPlayerError, onDurationChanged. We're calling play() with a local mp3 file that we do know exists on disk and is fully written to disk. We receive a result 1 from play() within maximum 5 seconds, we reckon that it is almost immediate. No exception is thrown from play(). After this we wait until we either get a duration for that file through onDurationChanged or a state change to completed/paused/stopped through onPlayerStateChanged or an error through onPlayerError. But we do not get anything, no sound is played, no duration received, state is still "PLAYING" and after 10s we abort that audio player. By abort I mean that we call stop(), we remove the local file, we clear stream subscriptions etc. Then the app continues and plays the next song, it will create a new file on disk, use a new audioplayer and call play(). Again, play() returns 1 and state is set to PLAYING but nothing happens. After 10s our watchdog timer breaks again, the app queues a new sound and the same thing happens again and again and again until the user kills the app and restarts it.

**Code to Reproduce**
This is very difficult as we cannot reproduce the error. But I have created a minimal example with a clone of our audioplayers code in the file my_audio_player.dart. The thing that is not cloned from our production repo is that in production we are playing tons of *different* (short) mp3 files that can vary so maybe a corrupt mp3 file could cause the bug. If that's the case, we cannot reproduce the bug with this code.
The repro is here: https://github.com/mikeesouth/audioplayers_freeze_issue_ios
The relevant audioplayers-code is in this file: https://github.com/mikeesouth/audioplayers_freeze_issue_ios/blob/main/lib/my_audio_player.dartstops

**Log Errors**
No real logs but we do receive many errors from our end users and these are reported to a bug tracking system that we use. The errors that we see are these (these can be found in the my_audio_player.dart file above):
* "AudioPlayer did not receive a duration or complete within 10 seconds of play()" - This is by far most common (~78% of reported errors)
* "AudioPlayer did not complete within 5 seconds of duration. Duration:" - This is second most common (~19% of reported errors)
* "AudioPlayer.play() did not return with result within 5 seconds" - This has happened (~3% of reported errors)

We assume all three are related to the same underlying problem - that audioplayers lib crashes and cannot play anything more until the app is restarted.

**Files/URLs/Sources**
We are trying to extract the specific mp3 files that our end users are trying to play when the bug occurs but we do not have these files yet.

**Platforms**
* OS: We've only seen this on iOS, not on emulators and not on Android devices.
* OS version: iOS 14.4, iOS 14.3, iOS 14.2, iOS 14.0.1, iOS 13.6.1, iOS 13.4.1, iOS 13.3.1, iOS 13.2
* Device: physical iPads only, both mini and regular, air and regular, various generations
* flutter version: 1.22.6 (stable), it has occured on previous stable releases of flutter too (last 3-6 months)
* audioplayers version: 0.16.1
* peculiarities: it seems to only affect some people and it seems to be random. It happens after 1-30minutes of app use so again: feels random. We've had reports that it happens after about 50-60 mp3 files in some cases and up to ~450 files in other cases, again: feels random.

If anyone can find some kind of bug in https://github.com/mikeesouth/audioplayers_freeze_issue_ios/blob/main/lib/my_audio_player.dartstops, please let us know!

**Comment by muarachmann** [comment]
Hi sorry for the late reply... I will run this and see if I can replicate the issue on simulator or real device.

**Comment by UnCheon** [comment]
@mikeesouth Do you resolve this error? I keep getting reports from some of iOS users. They say the app freezes or shut down.

**Comment by mikeesouth** [comment]
@UnCheon Its not resolved but its at least much better now even if I still get some error reports and we keep fine tuning the error management in our sound player. We've done several steps to resolve this but in short:
Stop using AudioCache or any other audioplayers except a fixed set of players in a pool. Only use pooled audioplayers since audioplayers does not seem to dispose correctly on iOS, even audiocache seems to be "leaking" in the same manner since it creates new audioplayers internally. We're currently using 50 players in a pool and that seems to be fine.

We're using the pooled player I linked above: https://github.com/mikeesouth/audioplayers_freeze_issue_ios/blob/main/lib/my_audio_player.dart

Also, we're still using only audioplayers 0.16.1, later versions are buggy in different ways on iOS.

Hope this helps.

**Comment by RR-Reddy** [comment]
same issue here

**Comment by yanivshaked** [comment]
Same issue, going to try @mikeesouth's approach.

**Comment by Gustl22** [comment]
Can you retest with `[audioplayers ](audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
