### ISSUE TITLE
Linux platform support

### ISSUE THREAD

**Issue by maks** [bluefireteam/audioplayers#798]
This was referred to in #489 but I thought it would be better to track Linux support separately.

**Comment by srkrishnan1989** [comment]
kplayer is just wrapper for just_audio and dart_vlc ,
kplayer team made 6 platform support using  dart_vlc,
audioplayers  team can also  make 6 platform support using  dart_vlc.

**Comment by maks** [comment]
I've been using the `libao` Dart package in Dart Linux cli applications with some success, its pretty much the only option if you want to **generate** audio in Dart or modify audio during playback vs simple playback of audio files. The only issue with using libao from Dart is problems with achieving low-latency, though of course low-latency is not really possible at all with any of the more high level plugins.

**Comment by Gustl22** [comment]
Now that Windows is implemented via #1068 , I will give the Linux implementation a try.
For that I propose [Pipewire](https://docs.pipewire.org/tutorial1_8c-example.html) as the successor of PulseAudio, Jack and Alsa.
As libao is implementing all platforms, which is not what we need anymore. Also it's using PulseAudio and ALSA, I think its not worth implementing legacy services.
I did't do that much in C / C++, so I might not succeed, but let's see.

**Comment by 12people** [comment]
Thank you so much for implementing this!
