### ISSUE TITLE
Is there any schedule / plan regarding the release of bytes player in web? 

### ISSUE THREAD

**Issue by TerrenceAddison** [bluefireteam/audioplayers#823]
As the title mentioned, It is something I need in my project and wonder if there is any plan regarding it?

**Comment by erickzanardo** [comment]
There isn't anything planned for this, we could use some help with Pull requests on this.

**Comment by andreclinio** [comment]
(if I didn't understand precisely the issue, sorry!)
I wish I could help... playBytes() maybe a nice way to play files from assets as/when AudioCache is not available.

**Comment by Gustl22** [comment]
Closing in favor of #1269
