### ISSUE TITLE
PlayByte method does not work on iOS

### ISSUE THREAD

**Issue by yadames** [bluefireteam/audioplayers#860]
I need to use the `playBytes` method to play the audio, but apparently there is no implementation of this source in iOS. 

Any solution? I use version 0.18.3

Thanks

**Comment by erickzanardo** [comment]
Indeed this method is only available on Android.

At the moment there isn't a solution as this needs to be implemented. We could use some help with a pull request for this.

(you can check our [feature parity table](https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md) to check all the features availability)

**Comment by Gustl22** [comment]
Closing in favor of #1269
