### ISSUE TITLE
Audio plays after app is removed from recents

### ISSUE THREAD

**Issue by AnAnD4T1** [bluefireteam/audioplayers#869]
audio plays even after poping app from recents in android, tried calling dispose nothing worked
 in console it displays

W/FlutterJNI(20970): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: xyz.luan/audioplayers. Response ID: 0

**Comment by erickzanardo** [comment]
AudioPlayers don't automatically pauses/resumes audio, your app needs to listen to the app life cycle and manually do that.

If that isn't your specific issue, please edit the issue and follow the issue template, with some reproducible code, etc.

**Comment by AnAnD4T1** [comment]
my usecase is that, i am playing streaming audio from network, and it isnt stoping even after i completely close the app and pop it from recents menu, i have forcestop the app to stop audio from playing. Applife cycle only detect if its in recents or came back from recents. its a streaming service so i dont want it to stop when its in the background

**Comment by erickzanardo** [comment]
I see, can you provide the minimal reproducible code and all the info possible? Like flutter version, audioplayers version, etc

**Comment by anand-seeroo** [comment]
Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.631], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.0)
[√] Connected device (2 available)  

//music service file
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';
import 'package:sleepland/models/content.dart';
import 'package:sleepland/provider/ambienceprovider.dart';
import 'package:sleepland/provider/musicstatusprovider.dart';
import 'package:sleepland/provider/playlistprovider.dart';
import 'package:flutter_media_notification/flutter_media_notification.dart';

class MusicPlayerService {
  AudioPlayer ambiencePlayer = AudioPlayer();
  AudioPlayer playlistPlayer = AudioPlayer();

  AmbienceProvider _ambienceProvider = AmbienceProvider();
  PlayListProvider _playListProvider = PlayListProvider();
  static final MusicPlayerService _singleton = MusicPlayerService._internal();

  factory MusicPlayerService() {
    return _singleton;
  }

  MusicPlayerService._internal();
  // final MediaNotification notification;

  // MusicPlayerService(this.notification);

  initListeners() {}

  play(String ambience, String playlist) { //i call this function to give url to play
    print("$ambience $playlist");
    if (ambiencePlayer.state == AudioPlayerState.PAUSED &&
        playlistPlayer.state == AudioPlayerState.PAUSED) {
      resume();
    } else {
      playAmbience(ambience);
      playPlaylist(playlist);
    }
  }

  playAmbience(String uri, [bool check = false]) async {
    try {
      if (playlistPlayer.state != AudioPlayerState.PLAYING && check) {
        playPlaylist(_playListProvider.current.uri);
      }
      int i = await ambiencePlayer.play(uri);
      print(i);
    } catch (e) {
      print(e.toString());
    }
  }

  playPlaylist(String uri, [bool check = false]) async {
    try {
      if (ambiencePlayer.state != AudioPlayerState.PLAYING && check) {
        playAmbience(_ambienceProvider.current.uri);
      }

      int i = await playlistPlayer.play(uri);

      print(i);
    } catch (e) {
      print(e.toString());
    }
  }

  pause() async {
    try {
      await playlistPlayer.pause();
      await ambiencePlayer.pause();
    } catch (e) {
      print(e.toString());
    }
  }

  resume() async {
    try {
      await playlistPlayer.resume();
      await ambiencePlayer.resume();
    } catch (e) {
      print(e.toString());
    }
  }

  stop() async {
    try {
      await playlistPlayer.stop();
      await ambiencePlayer.stop();
      await hideNotification();
    } catch (e) {}
  }

  dispose() async {
    stop();
    // await playlistPlayer.dispose();
    // await ambiencePlayer.dispose();
  }

  Future<void> hideNotification() async {
    try {
      await MediaNotification.hideNotification();
    } catch (e) {
      print(e.toString());
    }
  }

  Future<void> showNotification(bool isPlaying,
      [String author, String name]) async {
    if (author == null) author = _ambienceProvider.current.name;
    if (name == null) name = _playListProvider.current.name;
    try {
      await MediaNotification.showNotification(
          title: name, author: author, isPlaying: isPlaying);
    } catch (e) {
      print("notification error $e");
    }
  }
}

**Comment by AnAnD4T1** [comment]
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';
import 'package:sleepland/models/content.dart';
import 'package:sleepland/provider/ambienceprovider.dart';
import 'package:sleepland/provider/musicstatusprovider.dart';
import 'package:sleepland/provider/playlistprovider.dart';
import 'package:flutter_media_notification/flutter_media_notification.dart';

class MusicPlayerService {
  AudioPlayer ambiencePlayer = AudioPlayer();
  AudioPlayer playlistPlayer = AudioPlayer();

  AmbienceProvider _ambienceProvider = AmbienceProvider();
  PlayListProvider _playListProvider = PlayListProvider();
  static final MusicPlayerService _singleton = MusicPlayerService._internal();

  factory MusicPlayerService() {
    return _singleton;
  }

  MusicPlayerService._internal();
  // final MediaNotification notification;

  // MusicPlayerService(this.notification);

  initListeners() {}

  play(String ambience, String playlist) {
    print("$ambience $playlist");
    if (ambiencePlayer.state == AudioPlayerState.PAUSED &&
        playlistPlayer.state == AudioPlayerState.PAUSED) {
      resume();
    } else {
      playAmbience(ambience);
      playPlaylist(playlist);
    }
  }

  playAmbience(String uri, [bool check = false]) async {
    try {
      if (playlistPlayer.state != AudioPlayerState.PLAYING && check) {
        playPlaylist(_playListProvider.current.uri);
      }
      int i = await ambiencePlayer.play(uri);
      print(i);
    } catch (e) {
      print(e.toString());
    }
  }

  playPlaylist(String uri, [bool check = false]) async {
    try {
      if (ambiencePlayer.state != AudioPlayerState.PLAYING && check) {
        playAmbience(_ambienceProvider.current.uri);
      }

      int i = await playlistPlayer.play(uri);

      print(i);
    } catch (e) {
      print(e.toString());
    }
  }

  pause() async {
    try {
      await playlistPlayer.pause();
      await ambiencePlayer.pause();
    } catch (e) {
      print(e.toString());
    }
  }

  resume() async {
    try {
      await playlistPlayer.resume();
      await ambiencePlayer.resume();
    } catch (e) {
      print(e.toString());
    }
  }

  stop() async {
    try {
      await playlistPlayer.stop();
      await ambiencePlayer.stop();
      await hideNotification();
    } catch (e) {}
  }

  dispose() async {
    stop();

    // await playlistPlayer.dispose();
    // await ambiencePlayer.dispose();
  }

  Future<void> hideNotification() async {
    try {
      await MediaNotification.hideNotification();
    } catch (e) {
      print(e.toString());
    }
  }

  Future<void> showNotification(bool isPlaying,
      [String author, String name]) async {
    if (author == null) author = _ambienceProvider.current.name;
    if (name == null) name = _playListProvider.current.name;
    try {
      await MediaNotification.showNotification(
          title: name, author: author, isPlaying: isPlaying);
    } catch (e) {
      print("notification error $e");
    }
  }
}

**Comment by AnAnD4T1** [comment]
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.631], locale
    en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Destr0\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\Destr0\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

**Comment by AnAnD4T1** [comment]
import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'package:audioplayers/audioplayers.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_media_notification/flutter_media_notification.dart';
import 'package:lottie/lottie.dart';
import 'package:provider/provider.dart';
import 'package:sleepland/helpers/page_route.dart';
import 'package:sleepland/models/content.dart';
import 'package:sleepland/provider/ambienceprovider.dart';
import 'package:sleepland/provider/musicstatusprovider.dart';
import 'package:sleepland/provider/playlistprovider.dart';
import 'package:sleepland/provider/userprovider.dart';
import 'package:sleepland/screens/ambience/ambiencepage.dart';
import 'package:sleepland/screens/playlist/playlistpage.dart';
import 'package:sleepland/screens/settings/settings.dart';
import 'package:sleepland/services/musicplayerservice.dart';
import 'package:sleepland/services/revenuecatservice.dart';
import 'package:http/http.dart' as http;

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>
    with TickerProviderStateMixin {
  AnimationController scaleController;
  final Duration duration = Duration(milliseconds: 300);
  final double radius = 10;
  final Color background = Color(0xff3b3c84);
  PageController _controller = PageController(viewportFraction: 1 / 3);
  int current = 0;
  bool isPlaying = false;
  bool isPremiumUser = false;
  MusicPlayerService _musicPlayerService;
  Content ambience;
  Content playlist;
  Timer timer;
  bool isStopped = false;
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    scaleController = AnimationController(vsync: this, duration: duration);
    _musicPlayerService = MusicPlayerService();
    _musicPlayerService.playlistPlayer.onPlayerStateChanged.listen((event) {
      if (event == AudioPlayerState.COMPLETED) {
        _musicPlayerService.playlistPlayer.seek(Duration(seconds: 0));
        _musicPlayerService.playlistPlayer.resume();
      }
    });
    _musicPlayerService.ambiencePlayer.onPlayerStateChanged.listen((event) {
      if (event == AudioPlayerState.COMPLETED) {
        _musicPlayerService.ambiencePlayer.seek(Duration(seconds: 0));
        _musicPlayerService.ambiencePlayer.resume();
      }
    });
    MediaNotification.setListener('pause', () {
      pause();
    });

    MediaNotification.setListener('play', () {
      play();
    });
  }

  @override
  void dispose() async {
    scaleController.dispose();
    await _musicPlayerService.dispose();
    WidgetsBinding.instance.removeObserver(this);
    await _musicPlayerService.ambiencePlayer.dispose();
    await _musicPlayerService.playlistPlayer.dispose();
    timer.cancel();
    super.dispose();
  }

 
  toggleScale() => scaleController.isDismissed
      ? scaleController.forward()
      : scaleController.reverse();

  double getRadius(double val) => radius * val;
  pause() {
    context.read<MusicStatusProvider>().setPlay(false);
    _musicPlayerService.pause();
    _musicPlayerService.showNotification(false, ambience.name, playlist.name);
  }

  play() {
    context.read<MusicStatusProvider>().setPlay(true);
    _musicPlayerService.play(ambience.uri, playlist.uri);
    _musicPlayerService.showNotification(true, ambience.name, playlist.name);
  }

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.of(context).size;
    var ambienceProvider = context.watch<AmbienceProvider>();
    var playlistProvider = context.watch<PlayListProvider>();
    var userProvider = context.watch<UserProvider>();
    if (ambienceProvider.current == null || playlistProvider.current == null)
      return Scaffold(body: Center(child: CircularProgressIndicator()));
    ambience = ambienceProvider.current;
    playlist = playlistProvider.current;

    startTimer(int time) {
      print("timer started $time");
      timer = Timer(Duration(minutes: time), () {
        _musicPlayerService.stop();
        context.read<MusicStatusProvider>().setPlay(false);
      });
      print(timer.isActive);
    }

    return Scaffold(
      backgroundColor: Colors.black,
      body: SafeArea(
        child: AnimatedBuilder(
            animation: scaleController,
            builder: (context, _) {
              var scale = 1 - (scaleController.value * .08);
              return Transform(
                alignment: Alignment.topCenter,
                transform: Matrix4.identity()..scale(scale),
                child: ClipRRect(
                  borderRadius:
                      BorderRadius.circular(getRadius(scaleController.value)),
                  child: Stack(
                    children: [
                      Container(
                          height: double.infinity,
                          width: double.infinity,
                          // alignment: Alignment.center,
                          child: ambienceProvider.current.background
                                  .contains("http")
                              ? Lottie.network(
                                  ambienceProvider.current.background,
                                  fit: BoxFit.cover)
                              : Lottie.asset(
                                  ambienceProvider.current.background,
                                  fit: BoxFit.cover)),
                      Container(
                        padding: EdgeInsets.all(20),
                        height: size.height,
                        child: Column(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Container(
                              child: Column(
                                children: [
                                  Align(
                                    alignment: Alignment.centerRight,
                                    child: IconButton(
                                      onPressed: () {
                                        toggleScale();
                                        Navigator.of(context).push(slideInRoute(
                                            SettingsPage(() => toggleScale())));
                                      },
                                      icon: Icon(
                                        Icons.settings,
                                        size: 30,
                                        color: Colors.white,
                                      ),
                                    ),
                                  ),
                                  Transform.rotate(
                                    angle: -math.pi / 4,
                                    child: Icon(
                                      Icons.nightlight_round,
                                      size: 60,
                                      color: Colors.white,
                                    ),
                                  ),
                                  SizedBox(height: 20),
                                  Text(
                                    ambienceProvider.current.name,
                                    style: TextStyle(
                                        fontFamily: "Nunito",
                                        color: Colors.white,
                                        fontSize: 20),
                                  ),
                                  // SizedBox(height: 10),
                                  // Container(
                                  //   width: size.width * .8,
                                  //   child: Text(
                                  //     ambienceProvider.current.description,
                                  //     style: TextStyle(
                                  //       color: Colors.white70,
                                  //       // fontWeight: FontWeight.w200,
                                  //       fontSize: 15,
                                  //     ),
                                  //     textAlign: TextAlign.center,
                                  //   ),
                                  // ),
                                  SizedBox(height: 15),
                                  Container(
                                    width: size.width * .6,
                                    height: 40,
                                    decoration: BoxDecoration(
                                        color: Colors.white10,
                                        borderRadius:
                                            BorderRadius.circular(100)),
                                    child: PageView.builder(
                                      controller: _controller,
                                      itemCount: 5,
                                      onPageChanged: (val) {
                                        // _musicPlayerService.stop();
                                        setState(() {
                                          current = val;
                                        });
                                      },
                                      itemBuilder: (context, i) => Container(
                                          alignment: Alignment.center,
                                          child: Text(
                                            "${(i + 1) * 10} Mins",
                                            style: TextStyle(
                                                color: i == current
                                                    ? Colors.white
                                                    : Colors.white38),
                                          )),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Align(
                              // alignment: Alignment.bottomCenter,
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  IconButton(
                                    onPressed: () {
                                      toggleScale();

                                      Navigator.of(context)
                                          .push(slideInRoute(PlayListPage(
                                        _musicPlayerService,
                                        () => toggleScale(),
                                        ambienceProvider.current.name,
                                      )));
                                    },
                                    icon: Icon(
                                      Icons.equalizer,
                                      color: Colors.white,
                                    ),
                                  ),
                                  SizedBox(width: 20),
                                  // Text("${context.watch<MusicStatusProvider>().isPlaying}"),
                                  context.watch<MusicStatusProvider>().isPlaying
                                      ? IconButton(
                                          iconSize: 80,
                                          onPressed: ambienceProvider.current ==
                                                      null &&
                                                  playlistProvider.current ==
                                                      null
                                              ? null
                                              : () {
                                                  pause();
                                                },
                                          icon: Icon(
                                            Icons.pause_circle_filled,
                                            color: Colors.white,
                                          ),
                                        )
                                      : IconButton(
                                          iconSize: 80,
                                          onPressed: ambienceProvider.current ==
                                                      null &&
                                                  playlistProvider.current ==
                                                      null
                                              ? null
                                              : () {
                                                  if (timer == null ||
                                                      !timer.isActive) {
                                                    print("play");
                                                    startTimer(
                                                        (current + 1) * 10);
                                                  }
                                                  play();
                                                },
                                          icon: Icon(
                                            Icons.play_circle_fill,
                                            color: Colors.white,
                                          ),
                                        ),
                                  SizedBox(width: 20),
                                  IconButton(
                                    onPressed: () {
                                      toggleScale();
                                      Navigator.of(context)
                                          .push(slideInRoute(AmbiencePage(
                                        _musicPlayerService,
                                        () => toggleScale(),
                                        playlistProvider.current.name,
                                      )));
                                    },
                                    icon: Icon(
                                      Icons.park,
                                      size: 25,
                                      color: Colors.white,
                                    ),
                                  ),
                                ],
                              ),
                            )
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }),
      ),
    );
  }
}

**Comment by vinuvirat** [comment]
i too have the same problem. i did :
```
class MainUI extends StatefulWidget {
  @override
  _MainUIState createState() => _MainUIState();
}

class _MainUIState extends State<MainUI> with WidgetsBindingObserver {
  bool setted = false;

  late AppLifecycleState _lastLifecycleState;

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance!.addObserver(this);
   }

  @override
  void dispose() {

    _audioPlayer.dispose();
    _durationSubscription?.cancel();
    _positionSubscription?.cancel();
    _playerCompleteSubscription?.cancel();
    _playerErrorSubscription?.cancel();
    _playerStateSubscription?.cancel();
    _playerControlCommandSubscription?.cancel();

    WidgetsBinding.instance!.removeObserver(this);
    super.dispose();
  }

   @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {

    if (state == AppLifecycleState.detached) {

      await _stop();      
   
 }

    setState(() {
      _lastLifecycleState = state;
    });

    print('printing lifestate');
    print(_lastLifecycleState);
  }
   
 }```

_stop() function code is:
```
Future<int> _stop() async {

    final result = await _audioPlayer.stop();
    
    if (result == 1) {
      setState(() {
        _playerState = PlayerState.STOPPED;
        _position = const Duration();
      });
    }

    print(_audioPlayer);

    return result;
  }```

**Comment by AnAnD4T1** [comment]
i even calls dispose to cancel all, it is't working

**Comment by vinuvirat** [comment]
> i even calls dispose to cancel all, it is't working

yeah

**Comment by LordofUniverse** [comment]
i am waiting for update from this problem, it is a crucial problem. i am worried

**Comment by asiaWang** [comment]
me too, my project problem is when i paly audio in new page,the state is palying,the i back to pre page,the the audio still paly in back，in play audio page，i stoped paly audio when the page is dispose,but the audio is still play,who can fix this case?

**Comment by Gustl22** [comment]
Which android version has your emulator? What audioplayers version do you use? 

Can you retest with current [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example)? 

For me it's stopping the audio stream, if I remove our example from recents. We don't even stop the stream in the example, when calling dispose. Plz provide a link to a full repo with a reproducible example or just small code snippets.

**Comment by Gustl22** [comment]
Closing as stale.
