### ISSUE TITLE
onAudioPositionChanged Custom firing time

### ISSUE THREAD

**Issue by marcodecarolisidt** [bluefireteam/audioplayers#871]
Is it possible to have a parameter that sets the firing time when the onAudioPositionChanged is excecuted?
At the moment is 200 milliseconds ... but if connected to a Slider, while playing the audio, it doesn't look smooth.
I would like to set it to 5 milliseconds for example

**Comment by XHStudios** [comment]
AudioplayersPlugin -> CMTime interval = CMTimeMakeWithSeconds(0.2, NSEC_PER_SEC).
change the number from 0.2 to 0.005
