### ISSUE TITLE
onDurationChanged returns always 0 

### ISSUE THREAD

**Issue by Nasreddine** [bluefireteam/audioplayers#877]
When I call **onDurationChanged.listen** with file from the above mentioned server, I get always 0 value.
I download the file on local host and run it locally, it worked.
The problem is only with this server, I tried other remote servers without problems. 

**Files/URLs/Sources**
https://j-eman.net/wp-content/uploads/J-eman/AyamElmeyah/02jameOthman01-01-1441/01.mp3 

**Platforms**

* OS: android
* OS version: 10
* Device: Mi 9T
* flutter version: 2.0.6 
* audioplayers version: 0.18.3

**Comment by StarBattle08** [comment]
onDurationChanged isn't even working for me on IOS while it's working fine on Android.

**Comment by shivanshssgupta** [comment]
I am facing the same issue when I use google drive urls for some files. For some files it works fine, but it shows error for other files

**Comment by Gustl22** [comment]
Can you retest with latest `audioplayers: ^1.1.0` ? Thx :)

**Comment by Gustl22** [comment]
With #1191 all should be available after setting the source.
