### ISSUE TITLE
Fatal crash on iOS - Could not cast value of type 'NSNull' to 'NSNumber'

### ISSUE THREAD

**Issue by larssn** [bluefireteam/audioplayers#885]
So it crashes on iOS immediately upon playing a sound:
```
Could not cast value of type 'NSNull' to 'NSNumber'.
 > NSNull > NSNumber
```

Not sure what line it happens on, as we don't have debug symbols, but somewhere in the `handle` function in `SwiftAudioplayersPlugin.swift`.

And sorry, I don't have time to fill out the very long bug template. Feel free to close if unacceptable.

Version: 0.18.3
Flutter: 2.0.6
iOS version(s): only seen 14.4.2 in our error logging service

Offending code:
```dart
    AudioCache cache = AudioCache(prefix: 'assets/sounds/');
    AudioPlayer audioPlayer = new AudioPlayer();
    if (Platform.isIOS) {
      audioPlayer.monitorNotificationStateChanges((AudioPlayerState value) {
        print("state => $value");
      });
    }
    cache.play('click.wav', mode: PlayerMode.LOW_LATENCY);
```

There are only two places where a cast to `NSNumber` happens.
Here: https://github.com/luanpotter/audioplayers/blob/8cd7e7be76308df9b82192ede24d8adadb8188b9/packages/audioplayers/darwin/Classes/NotificationsHandler.swift#L218
And here: https://github.com/luanpotter/audioplayers/blob/8cd7e7be76308df9b82192ede24d8adadb8188b9/packages/audioplayers/darwin/Classes/NotificationsHandler.swift#L223

**Comment by larssn** [comment]
@erickzanardo I've filled out some more info. I'll add more, as it becomes available.

**Comment by larssn** [comment]
Removing this section makes the crash go away entirely:
```dart
audioPlayer.monitorNotificationStateChanges((AudioPlayerState value) {
  print("state => $value");
});
```

**Comment by luanpotter** [comment]
Weird that it would be those lines, because if you see the param for that method is `Int`, so should never be null.

> as we don't have debug symbols
that is very interesting to hear, I am not super familiar with ios, but I think it's imperative for us to enable traces moving forward, do you know what we need to do to turn this on?

about the issue, I believe it might be because you haven't started the notf service? `monitorNotificationStateChanges` is a notification service feature, so you must call `player.startHeadlessService();`. that is not included on your sample and it's required to use any notification feature.

**Comment by larssn** [comment]
> that is very interesting to hear, I am not super familiar with ios, but I think it's imperative for us to enable traces moving forward, do you know what we need to do to turn this on?

To my knowledge you don't need to do anything; it is us that needs to upload our dSYM files to our error reporting service.

> about the issue, I believe it might be because you haven't started the notf service? `monitorNotificationStateChanges` is a notification service feature, so you must call `player.startHeadlessService();`. that is not included on your sample and it's required to use any notification feature.

I included all the code as I found it (I'm not the author of that snippet). I've since taken it out, and it no longer crashes as I mentioned above. I suppose we should leave this open, but I wouldn't say it's anything worth prioritising right now. 🙂

**Comment by Gustl22** [comment]
I think this was reimplemented since `1.x.x`. Feel free to open a new issue, if the error still occurs.
