### ISSUE TITLE
Support for getting last URL (currently playing or last played)

### ISSUE THREAD

**Issue by yanivshaked** [bluefireteam/audioplayers#891]
*One Liner*
Support for `getUrl` method which will return the last URL played (or currently playing).

**Full Description**
Use case is to be able to query the player so that it is possible to reuse it. For example in a chat application, that has many audio feeds. An audio player being used in a feed item may be forwarded by identifying it's url.

**Example Code**
```
AudioPlayer? _audioPlayer;
_audioPlayer = AudioPlayer();
_audioPlayer.play(url, isLocal: true, position: startFrom);
var playerUrl = _audioPlayer.getUrl(); // Should be identical to the above url
```

**Platforms**
All platforms should be supported.

**Comment by Gustl22** [comment]
Just can use a map to save the players with their according urls right after initializing? Also AudioCache already "caches" the urls on your device. Of course it will be a bit more faster, if you hold the player as reference. Closing, as it should be up to developer, how to handle this.
