### ISSUE TITLE
earpieceOrSpeakersToggle after phone call with speaker on

### ISSUE THREAD

**Issue by RedHappyLlama** [bluefireteam/audioplayers#896]
Hi,

Just found an issue with the earpieceOrSpeakersToggle. The issue is only present after making a phone call when the call is made with the phone’s speakerphone setting turned on. 

If you use audioplayers with the audio directed to the earpiece just after a phone call where you had the phone on speakerphone, the audio comes out of the “media” speaker and louder than usual. Clearly the phone is still set to “speakerphone” mode and therefore the audio plays as if it’s a speakerphone. If you then make another phone call with speakerphone turned off, the audio then plays correctly out of the earpiece when required.

I know it’s an issue on Android, I haven’t really been able to properly test it on iOS but I don’t think it’s an issue on iOS. Obviously not possible to test in dev environment.

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 2.0.1
    • Framework revision c5a4b4029c (3 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Platform android-30, build-tools 30.0.0-rc2
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

audioPlayers version 0.18.3.

Thanks!

**Comment by Gustl22** [comment]
Option `earpieceOrSpeakersToggle` is replaced by `AndroidAudioContext` #1240
