### ISSUE TITLE
the plugin throws exception when resource was not accessable

### ISSUE THREAD

**Issue by memetea** [bluefireteam/audioplayers#92]
when the resouce was not accessable the plugin throws an exception and it seems that I can't catch it. here's the stacktrace

`E/AudioplayersPlugin(21486): java.lang.RuntimeException: Unable to access resource
E/AudioplayersPlugin(21486): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:145)
E/AudioplayersPlugin(21486): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:54)
E/AudioplayersPlugin(21486): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:57)
E/AudioplayersPlugin(21486): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:42)`

**Comment by memetea** [comment]
here's the code

`void buttonPressed() async {
    try {
      if (playerState != AudioPlayerState.PLAYING) {
        await this.audioPlayer.play(this.widget.url);
      } else {
        await this.audioPlayer.resume();
      }
    } on PlatformException catch (e) {
      print("play ${this.widget.url} error: $e");
      hasError = true;
    }
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    Color iconColor = hasError ? Colors.grey : Colors.black;
    return FlatButton(
      child: playerState == AudioPlayerState.STOPPED
          ? Icon(Icons.play_arrow, color:iconColor)
          : Icon(Icons.pause, color:iconColor),
      onPressed: hasError ? null : buttonPressed,
    );
  }`

**Comment by erickzanardo** [comment]
But this is expected right? There is not much to do if the resource is not accessible, and since it is a RuntimeException, it will not be possible for audioplayers to identify that the exception was caused because of an inaccessible resource.

**Comment by memetea** [comment]
pass  this error through callback is a good choice

**Comment by erickzanardo** [comment]
Hum, I may has not understood correctly your issue then, is this failing silently? You not able to catch this with a try/catch statement?

**Comment by luanpotter** [comment]
I think it should throw an error but on the dart side, or at least dart-side-catchable or something. I don't think an error callback is necessary.

**Comment by praharshbhatt** [comment]
Are you using [Audio Cache Class](https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md)?

**Comment by ashishbairwa** [comment]
Did anyone get a solution yet?

**Comment by Heipi** [comment]
Audio Cache load local asset file

**Comment by themindstorm** [comment]
I am also getting the same issue. Are there any updates?

**Comment by aryan29** [comment]
Facing same issue using this plugin

**Comment by Gustl22** [comment]
Fixed via 5eeca8940e764546023567fa2f6b1bc3802f97d3 for android. Now throwing correctly on the dart side.
Can anyone confirm for ios? May needs to be added to tests.

**Comment by Gustl22** [comment]
Mark this as stale, as it's most probably fixed.
