### ISSUE TITLE
sound does not play on android (flame_audio:1.0.0-rc.1)

### ISSUE THREAD

**Issue by QiXi** [bluefireteam/audioplayers#922]
`
await FlameAudio.audioCache.loadAll(['end_player_move.ogg']);
...
FlameAudio.play('start_player_move.ogg', volume: 0.5);`
```
dependencies:
  flame_audio: ^1.0.0-rc.1 //(audioplayers: 0.19.0)
```
the result is
no sound and Logcat:
> D/WSP: Reusing soundId 0 for file:///data/user/0/...../cache/end_player_move.ogg is loading=true xyz.luan.audioplayers.WrappedSoundPool@b1905a

tested devices:
 Android 6 and Android 10

sound plays if you use the 0.1.0-rc5 dependency
```
dependencies:
  flame_audio: ^0.1.0-rc5 //(audioplayers: 0.18.3)
```

**Comment by akashb95** [comment]
I'm having the same issue using audioplayers v2.0.0 and v2.0.3.

Tested on: MacOS, iOS 14.5 (Simulator), Android 10 and Android 11. 

MacOS and iOS work as expected. With Android devices, here is no audio, as @QiXi reports.

**Comment by codetricity** [comment]
I just used it this morning with Android 11 and it worked fine.  Sound plays with AudioCache and AudioPlayer, and Bgm.  I tested on Android and Web successfully.  Does not work on Windows for me.  I'm interested if anyone has it working on Windows desktop.

in `android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.4.32'
```

in `pubspec.yaml`

```
  audioplayers: ^0.19.0
```

I also deleted `.gradle/caches` and rebuilt.  I'm not sure if that was needed, but it took me a few attempts to solve the problem.  I looked into the problem on android as someone asked a question on a [video I made as a hobby on how to use Flutter widgets with Flame](https://youtu.be/v_Yb95vdMEM).  You can see the code, including the `android` directory with working sound if it is of interest to you in the description of the video.  It's just a simple example code for a basic tutorial for kids.  I'm using Flutter stable, 2.2.2.
 
I also built a standalone app without flame to test the audio and it worked the same.

Oh, I think I had to increase the Android SDK minimum version.

in `android/app/src/build.gradle`, I put this:

```
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flame_animation"
        minSdkVersion 23
        targetSdkVersion 30
```

**Comment by Gustl22** [comment]
@akashb95 there's no `audioplayers v2.0.0` (?)

I think you should test with flame_audio: `1.3.1` again.
