### ISSUE TITLE
The playback status has changed after calling setPlaybackRate.

### ISSUE THREAD

**Issue by Code-Yeong** [bluefireteam/audioplayers#948]
The playback state changes after the paused state calls **setRate**, but the value of the **playing** variable in the WrappedMediaPlayer class is still false. So when I tried to stop it from playing by calling **pause**, it didn't work.

I looked at the [Android development documentation](https://developer.android.com/reference/android/media/MediaPlayer) and found the following introduction:

> Sets playback rate using PlaybackParams. ...  After the object is prepared, calling it with non-zero speed is equivalent to calling start().

The player starts to play after the **setRate** is called in the paused state, so the **playing** variable should be set to true, otherwise the next **pause** will not take effect.

This is the source code of the **pause** function defined in the **WrappedMediaPlayer** class：
```
    override fun pause() {
        if (playing) {
            playing = false
            player?.pause()
        }
    }
```

**Comment by luanpotter** [comment]
I tested this again on the current version of the code+example app. Calling seek no longer interferes with the resume/pause state.
