### ISSUE TITLE
Not working properly inside a Listview

### ISSUE THREAD

**Issue by sajanyamaha** [bluefireteam/audioplayers#959]
This is my structure ,

                                         ListView.builder(
                                            cacheExtent: 50.0,
                                            reverse: true,
                                            padding:
                                                const EdgeInsets.all(15),
                                            controller:
                                                _listScrollController,
                                            itemCount: Chats.length,
                                            itemBuilder: (ctx, i) {
                                              print(firebaseUID);
                                              if (Chats[i].data()['IsFile'] !=null && Chats[i].data()['IsFile'] &&
                                                  Chats[i].data()['FileType'] !=null && Chats[i].data()['FileType'] ==
                                                      'audio') {
                                                return AudioSentChat(i: i);
                                              
                                              } else
                                                return Container();
                                            },
                                          );

And Audio Sent Chat is a Stateless widget like this ,

                                       child: Container(
                                          padding: EdgeInsets.only(top: 15),
                                          height: 75,
                                          child: PlayerWidget(
                                              url: Chats[i]
                                                  .data()['FileUrl'],
                                              mode: PlayerMode
                                                  .MEDIA_PLAYER),
                                        ),

And the PlayerWidget is a Statefull widget with all the play/pause interactions , here [https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/example/lib/player_widget.dart](https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/example/lib/player_widget.dart)

Now the issue is ,

1. when a new audiofile is recorded and added to the listview (added to firebase) , the ui gets updated but when you play it all the files are duplicates , I checked the data , which is perfect and not duplicates.
2. Now when the screen is scrolled a little the and then files are played it works perfectly without any duplicates.

Observations , the intiState() inside the player_widget is not fired on Listview update .

How can this be handled , also is it a bad idea to put a statefull widget inside a listview.

**Comment by Gustl22** [comment]
As commented, I don't think it's a problem with audioplayers package.
