### ISSUE TITLE
Player state is wrong (PLAYING but it is not playing)

### ISSUE THREAD

**Issue by tamoyal** [bluefireteam/audioplayers#961]
While I cannot easily reproduce, I can confidently say the player state is sometimes wrong.

**Full Description**
My app relies on the player state to decide if it should let other audio play.
```
print(audioPlayer.state)
if (audioPlayer.state == PlayerState.PLAYING) {
  return;
}
...play audio here
```
However I notice it sometimes gets "stuck." While this is probably a sign I should change my design, I printed the state above the check and see this: `PlayerState.PLAYING`. My audio files are maximum 20 seconds so for sake of illustrating that the state is definitely wrong, I can wait 5 minutes, press the play button again and it will print the state is `PlayerState.PLAYING` before I get to any code that plays it.

iOS 14.6
Flutter 2.2.3 (stable)
This plugin: 0.19.1

**Comment by Gustl22** [comment]
Can you recheck with `audioplayers: ^1.1.0`?

**Comment by Gustl22** [comment]
Closing as stale.
