### ISSUE TITLE
Audio sometimes stops and start over without throwing errors

### ISSUE THREAD

**Issue by JideGuru** [bluefireteam/audioplayers#962]
Audio sometimes stops and start over without throwing errors

**Full Description**
Some users complained that the player stops at some point and starts over again. And when we checked the logs(Amplitude) we couldn't fine any error messages from the player.

**Code to Reproduce**
```
_audioPlayer = AudioPlayer(mode: widget.mode);
    if (kDebugMode) {
      AudioPlayer.logEnabled = true;
    }
_audioPlayer.play(widget.url,
        isLocal: widget.isLocal, position: playPosition, stayAwake: true);
_playerErrorSubscription = _audioPlayer.onPlayerError.listen((msg) {
      print('audioPlayer error : $msg');
      if (mounted)
        setState(() {
          _playerState = PlayerState.stopped;
          _duration = new Duration(seconds: 0);
          _position = new Duration(seconds: 0);
        });
      Dialogs.showAudioPlayErrorDialog(context, () {
        FirebaseCrashlytics.instance.log(msg);
        if (Platform.isAndroid) _sendErrorAnalytics(msg);
        Navigator.pop(context);
      });
    });
```

**Platforms**
* OS: android
* OS version: android 9
* Device: Samsung Galaxy S8
* flutter version: 2.2.0
* audioplayers version: 0.19.0
* release or not release: release.
* does the error occur and does it have any peculiarities: I didn't get any error message from the player. It did work fine on iOS but the issue happens on android

**Comment by Gustl22** [comment]
Can you recheck with `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
